def get_home_suburbs(): 
    home_suburbs = {
        "Select your option",
        "Hotels In City",  
        "International Airport",
        "Domestic Airport",
        "WhiteBay cruise terminal",
        "Overseas cruise terminal",
        "Artarmon",            
        "Asquith",
        "Auburn",
        "Balgowlah",
        "Balgowlah Heights",
        "Balmain",
        "Bass Hill",
        "Bankstown", 
        "Baulkham Hills",
        "Beaumont Hills",
        "Beecroft",
        "Belfield",
        "Bella Vista",
        "Belleveue Hill",
        "Belmore",
        "Berala",
        "Berowra",
        "Berowra Heights",
        "Bevely Hills",
        "Beverly Park",
        "Bexley",
        "Bexley North",
        "Bidwill",
        "Birchgrove",
        "Birrong",
        "Blackett",
        "Blacktown",
        "Bligh Park",
        "Bondi",
        "Bondi Junction",
        "Bossley Park",
        "Box Hill",
        "Breakfast Point",
        "Bronte",
        "Brookvale",
        "Bungarribee", 
        "Burwood",
        "Cabarita",
        "Cambridge Garden",
        "Cambridge Park",
        "Cammeray",
        "Canada Bay",
        "Canterbury",
        "Carlingford",
        "Castle Hill",
        "Castlecove",
        "Castlecrag",
        "Castlereagh",
        "Chatswood",
        "Cheltenham",
        "Cherrybrook",
        "Chester Hill",
        "Chullora",
        "Claremont Meadow",
        "Clyde",
        "Colebee",
        "Colyton",
        "Concord",
        "Concord West",
        "Condell Park",
        "Constitution Hill",
        "Coogee", 
        "Cranebrook",
        "Cremorne",
        "Crows Nest",
        "Croydon",
        "Croydon Park",
        "Darling Point",
        "Darlinghurst",
        "Dean Park",
        "Dee Why",
        "Denistone",
        "Dharruk",
        "Doonside",
        "Drummoyne",
        "Dulwitch Hill",
        "Dundas",
        "Dural",
        "East Killara",
        "East Lindfield",
        "East Ryde",
        "Eastern Creek",
        "Eastwood",
        "Edensor Park",
        "Elanora Heights",
        "Emerton",
        "Emu Plains",
        "Enfield",
        "Enmore",
        "Epping",
        "Ermington",
        "Erskin Park",
        "Fairlight",
        "Five Dock",
        "Forest Lodge",
        "Forestville",
        "French Forest",
        "Freshwater",
        "Galston",
        "Georges Hall",
        "Girraween",
        "Gladesville",
        "Glendenning",
        "Glenhaven",
        "Glenmore Park",
        "Glenwood",
        "Gordon",
        "Granville",
        "Greenacre",
        "Greenwich",
        "Greystanes",
        "Guildford",
        "Harberfield",
        "Harris Park",
        "Hassal Grove",
        "Henley",
        "Hebersham",
        "Holroyd",
        "Homebush",
        "Hornsby",
        "Hornsby Heights",
        "Hunters Hill",
        "Huntingwood",
        "Huntley Point",
        "Hurstville",
        "Jamisontown",
        "Jordan Springs",
        "Kellyville",
        "Keyllyville Ridge",
        "Kenthurst",
        "Killara",
        "Killarney Heights",
        "Kings Langley",
        "Kings Park",
        "Kirribilli",
        "Lalor Park",
        "Lane Cove",
        "Leichhardt",
        "Lethbridge Park",
        "Lewwisham",
        "Liberty Grove",
        "Lidcombe",
        "Lindfield",
        "Linley Point",
        "Liyfield",
        "Longueville",
        "Macquarie Park",
        "Manly",
        "Manly Vale",
        "Marayong",
        "Marsden Park",
        "Marsfield",
        "McGraths Hill",
        "Mcmahons Point",
        "Meadowbank",
        "Melrose Park",
        "Merrylands",
        "Michinbery",
        "Middle Cove",
        "Millers Point", 
        "Milpera",
        "Milsons Point",
        "Mortdale",
        "Mortlake",
        "Mosman",
        "Mt Colah",
        "Mt Druitt",
        "Mt Kuring Gai",
        "Mulgrave",
        "Naremburn",
        "Narraweena",
        "Neutral Bay",
        "Newington",
        "Normanhurst",
        "North Balowlah",
        "North Bondi",
        "North Epping",
        "North Parramatta",
        "North Rocks",
        "North Ryde",
        "North Strathfield",
        "North Sydney",
        "North Turramurra", 
        "Northbridge",
        "Northmead",
        "Northwood",
        "Oakhurst",
        "Oakville",
        "Oatland",
        "Old Toongabbie",
        "Olympic Park",
        "Orchard Hill",
        "Oxley Park",
        "Paddington",
        "Panania",
        "Pairiewood",
        "Parklea",
        "Parramatta",
        "Peakhurst",
        "Pemulway",
        "Pendle Hill",
        "Pennant Hills",
        "Penrith",
        "Plumpton",
        "Potts Point",
        "Prospect",
        "Punchbowl",
        "Putney",
        "Pymble",
        "Pyrmont",
        "Quakers Hill",
        "Regents Park",
        "Revesby",
        "Rhodes",
        "Richmond",
        "Riverston",
        "Riverview",
        "Riverwood",
        "Rooty Hill",
        "Ropes Crossing",
        "Rose Hill",
        "Roseville",
        "Roseville Chase",
        "Rouse Hill",
        "Russel Lea",
        "Rydalmere",
        "Ryde",
        "Seaforth",
        "Sefton",
        "Seven Hills",
        "Shalvey",
        "Silverwater",
        "Schofields",
        "South Turramurra",
        "South Wentworthville",
        "St Clair",
        "St Ives",
        "St Leonards",
        "St Marys",
        "St Marys North",
        "Stanhope Garden",
        "Strathfield",
        "Summer Hill",
        "Sydney (city)", 
        "Telopea",
        "Tennyson Point",
        "Terrey Hills",
        "The Ponds",
        "Thornleigh",
        "Toongabbie",
        "Top Ryde",
        "Tregear",
        "Turramurra",
        "Vineyard",
        "Wahroonga",
        "Waitara",
        "Warrawee",
        "Watsons Bay", 
        "Waverley",
        "Waverton",
        "Wentworth Point",
        "Wentworthville",
        "Werrington",
        "West Pennant Hills",
        "West Pymble",
        "West Ryde",
        "Westleigh",
        "Westmead",
        "Whalan",
        "Willmot",
        "Willoughby",
        "Winsor",
        "Winston Hill",
        "Wollstoncraft",
        "Woodcroft",
        "Woollahra",
        "Woolwich", 
        "Yagoona",
        }
    return home_suburbs

home_suburbs = get_home_suburbs() 
