from functools import lru_cache

@lru_cache(maxsize=1)
def get_more_suburbs():
    more_suburbs = {
    "Alexandria": {'price': 60, "area_type": "eastern_suburbs"},
    "Allambie Heights": {'price': 90, "area_type": "northern_beaches"},
    "Arndell Park": {'price': 120, "area_type": "outer_west"},
    "Artarmon": {'price': 60, "area_type": "north_shore"},
    "Ashfield": {'price': 60, "area_type": "inner_west"},
    "Asquith": {'price': 60, "area_type": "upper_north_shore"},
    "Auburn": {'price': 90, "area_type": "west"},
    "Balgowlah": {'price': 80, "area_type": "northern_beaches"},
    "Balgowlah Heights": {'price': 80, "area_type": "northern_beaches"},
    "Balmain": {'price': 60, "area_type": "inner_west"},
    "Banksmeadow": {'price': 80, "area_type": "eastern_suburbs"},
    "Bankstown": {'price': 60, "area_type": "west"},
    "Barangaroo": {'price': 60, "area_type": "sydney_city"},
    "Bass Hill": {'price': 60, "area_type": "west"},
    "Baulkham Hills": {'price': 100, "area_type": "north_west"},
    "Beacon Hill": {'price': 100, "area_type": "northern_beaches"},
    "Beaconsfield": {'price': 60, "area_type": "eastern_suburbs"},
    "Beaumont Hills": {'price': 100, "area_type": "north_west"},
    "Beauty Point": {'price': 90, "area_type": "north_shore"},
    "Beecroft": {'price': 100, "area_type": "upper_north_shore"},
    "Belfield": {'price': 60, "area_type": "west"},
    "Bella Vista": {'price': 110, "area_type": "north_west"},
    "Bellevue Hill": {'price': 60, "area_type": "eastern_suburbs"},
    "Belmore": {'price': 60, "area_type": "west"},
    "Belrose": {'price': 100, "area_type": "northern_beaches"},
    "Berala": {'price': 80, "area_type": "west"},
    "Berowra": {'price': 130, "area_type": "upper_north_shore"},
    "Berowra Heights": {'price': 140, "area_type": "upper_north_shore"},
    "Berowra Waters": {'price': 150, "area_type": "upper_north_shore"},
    "Beverly Hills": {'price': 60, "area_type": "west"},
    "Beverly Park": {'price': 60, "area_type": "west"},
    "Bexley": {'price': 60, "area_type": "west"},
    "Bexley North": {'price': 60, "area_type": "west"},
    "Bidwill": {'price': 160, "area_type": "outer_west"},
    "Birchgrove": {'price': 70, "area_type": "inner_west"},
    "Birrong": {'price': 70, "area_type": "west"},
    "Blackett": {'price': 140, "area_type": "outer_west"},
    "Blacktown": {'price': 100, "area_type": "outer_west"},
    "Bligh Park": {'price': 170, "area_type": "outer_west"},
    "Bondi": {'price': 80, "area_type": "eastern_suburbs"},
    "Bondi Beach": {'price': 80, "area_type": "eastern_suburbs"},
    "Bondi Junction": {'price': 60, "area_type": "eastern_suburbs"},
    "Botany": {'price': 70, "area_type": "eastern_suburbs"},
    "Box Hill": {'price': 170, "area_type": "outer_west"},
    "Breakfast Point": {'price': 80, "area_type": "inner_west"},
    "Bronte": {'price': 60, "area_type": "eastern_suburbs"},
    "Brooklyn": {'price': 160, "area_type": "upper_north_shore"},
    "Brookvale": {'price': 100, "area_type": "northern_beaches"},
    "Burwood": {'price': 60, "area_type": "west"},
    "Cabarita": {'price': 70, "area_type": "inner_west"},
    "Caddens": {'price': 170, "area_type": "outer_west"},
    "Cambridge Gardens": {'price': 170, "area_type": "outer_west"},
    "Cambridge Park": {'price': 170, "area_type": "outer_west"},
    "Camellia": {'price': 80, "area_type": "central_west"},
    "Cammeray": {'price': 70, "area_type": "north_shore"},
    "Camperdown": {'price': 60, "area_type": "inner_west"},
    "Canada Bay": {'price': 70, "area_type": "inner_west"},
    "Carlingford": {'price': 90, "area_type": "north_west"},
    "Castle Cove": {'price': 70, "area_type": "north_shore"},
    "Castle Hill": {'price': 100, "area_type": "north_west"},
    "Castlecrag": {'price': 70, "area_type": "north_shore"},
    "Castlereagh": {'price': 150, "area_type": "outer_west"},
    "Chatswood": {'price': 70, "area_type": "north_shore"},
    "Chatswood West": {'price': 80, "area_type": "north_shore"},
    "Cheltenham": {'price': 90, "area_type": "north_west"},
    "Cherrybrook": {'price': 110, "area_type": "north_west"},
    "Chester Hill": {'price': 80, "area_type": "west"},
    "Chifley": {'price': 90, "area_type": "eastern_suburbs"},
    "Chippendale": {'price': 50, "area_type": "eastern_suburbs"},
    "Chiswick": {'price': 70, "area_type": "inner_west"},
    "Chullora": {'price': 80, "area_type": "west"},
    "Clovelly": {'price': 70, "area_type": "eastern_suburbs"},
    "Clyde": {'price': 60, "area_type": "central_west"},
    "Colebee": {'price': 130, "area_type": "outer_west"},
    "Collaroy": {'price': 110, "area_type": "northern_beaches"},
    "Collaroy Plateau": {'price': 110, "area_type": "northern_beaches"},
    "Colyton": {'price': 140, "area_type": "outer_west"},
    "Concord": {'price': 70, "area_type": "inner_west"},
    "Concord West": {'price': 70, "area_type": "inner_west"},
    "Condell Park": {'price': 70, "area_type": "west"},
    "Constitution Hill": {'price': 80, "area_type": "central_west"},
    "Coogee": {'price': 60, "area_type": "eastern_suburbs"},
    "Cowan": {'price': 150, "area_type": "upper_north_shore"},
    "Cranebrook": {'price': 180, "area_type": "outer_west"},
    "Cremorne": {'price': 60, "area_type": "north_shore"},
    "Cremorne Point": {'price': 70, "area_type": "north_shore"},
    "Cromer": {'price': 100, "area_type": "northern_beaches"},
    "Crows Nest": {'price': 60, "area_type": "north_shore"},
    "Curl Curl": {'price': 100, "area_type": "northern_beaches"},
    "Darling Point": {'price': 50, "area_type": "sydney_city"},
    "Darlinghurst": {'price': 50, "area_type": "sydney_city"},
    "Davidson": {'price': 100, "area_type": "northern_beaches"},
    "Dean Park": {'price': 120, "area_type": "outer_west"},
    "Dee Why": {'price': 80, "area_type": "northern_beaches"},
    "Denistone": {'price': 70, "area_type": "north_west"},
    "Denistone East": {'price': 80, "area_type": "north_west"},
    "Dharruk": {'price': 120, "area_type": "outer_west"},
    "Doonside": {'price': 110, "area_type": "outer_west"},
    "Double Bay": {'price': 60, "area_type": "eastern_suburbs"},
    "Drummoyne": {'price': 60, "area_type": "inner_west"},
    "Dulwich Hill": {'price': 60, "area_type": "inner_west"},
    "Dundas": {'price': 70, "area_type": "central_west"},
    "Dundas Valley": {'price': 80, "area_type": "central_west"},
    "Dural": {'price': 100, "area_type": "north_west"},
    "East Killara": {'price': 80, "area_type": "north_shore"},
    "East Lindfield": {'price': 70, "area_type": "north_shore"},
    "East Ryde": {'price': 70, "area_type": "north_west"},
    "Eastern Creek": {'price': 130, "area_type": "outer_west"},
    "Eastgardens": {'price': 70, "area_type": "eastern_suburbs"},
    "Eastlakes": {'price': 60, "area_type": "eastern_suburbs"},
    "Eastwood": {'price': 80, "area_type": "north_west"},
    "Edgecliff": {'price': 60, "area_type": "eastern_suburbs"},
    "Elanora Heights": {'price': 100, "area_type": "northern_beaches"},
    "Emerton": {'price': 150, "area_type": "outer_west"},
    "Emu Plains": {'price': 190, "area_type": "outer_west"},
    "Enfield": {'price': 50, "area_type": "west"},
    "Enmore": {'price': 50, "area_type": "inner_west"},
    "Epping": {'price': 80, "area_type": "north_west"},
    "Ermington": {'price': 80, "area_type": "central_west"},
    "Eveleigh": {'price': 50, "area_type": "eastern_suburbs"},
    "Fairlight": {'price': 70, "area_type": "northern_beaches"},
    "Five Dock": {'price': 60, "area_type": "inner_west"},
    "Forest Lodge": {'price': 60, "area_type": "inner_west"},
    "Forestville": {'price': 80, "area_type": "northern_beaches"},
    "Frenchs Forest": {'price': 90, "area_type": "northern_beaches"},
    "Freshwater": {'price': 100, "area_type": "northern_beaches"},
    "Galston": {'price': 130, "area_type": "north_west"},
    "Georges Hall": {'price': 60, "area_type": "west"},
    "Girraween": {'price': 90, "area_type": "central_west"},
    "Gladesville": {'price': 60, "area_type": "north_west"},
    "Glebe": {'price': 60, "area_type": "sydney_city"},
    "Glendenning": {'price': 110, "area_type": "outer_west"},
    "Glenhaven": {'price': 110, "area_type": "north_west"},
    "Glenmore Park": {'price': 190, "area_type": "outer_west"},
    "Glenwood": {'price': 120, "area_type": "north_west"},
    "Gordon": {'price': 80, "area_type": "north_shore"},
    "Granville": {'price': 80, "area_type": "central_west"},
    "Greenacre": {'price': 60, "area_type": "west"},
    "Greenwich": {'price': 60, "area_type": "north_shore"},
    "Greystanes": {'price': 90, "area_type": "central_west"},
    "Guildford": {'price': 80, "area_type": "west"},
    "Guildford West": {'price': 80, "area_type": "west"},
    "Haberfield": {'price': 60, "area_type": "inner_west"},
    "Harris Park": {'price': 80, "area_type": "central_west"},
    "Hassall Grove": {'price': 130, "area_type": "outer_west"},
    "Haymarket": {'price': 60, "area_type": "sydney_city"},
    "Hebersham": {'price': 110, "area_type": "outer_west"},
    "Henley": {'price': 60, "area_type": "north_west"},
    "Hillsdale": {'price': 70, "area_type": "eastern_suburbs"},
    "Homebush": {'price': 60, "area_type": "west"},
    "Homebush West": {'price': 60, "area_type": "west"},
    "Hornsby": {'price': 100, "area_type": "upper_north_shore"},
    "Hornsby Heights": {'price': 110, "area_type": "upper_north_shore"},
    "Hotels In City": {'price': 60, "area_type": "sydney_city"},
    "Huntingwood": {'price': 120, "area_type": "outer_west"},
    "Huntleys Cove": {'price': 60, "area_type": "north_west"},
    "Huntleys Point": {'price': 60, "area_type": "north_west"},
    "Hurstville": {'price': 50, "area_type": "west"},
    "Ingleside": {'price': 140, "area_type": "northern_beaches"},
    "Jamisontown": {'price': 190, "area_type": "outer_west"},
    "Jordan Springs": {'price': 180, "area_type": "outer_west"},
    "Kellyville": {'price': 110, "area_type": "north_west"},
    "Kellyville Ridge": {'price': 120, "area_type": "north_west"},
    "Kensington": {'price': 70, "area_type": "eastern_suburbs"},
    "Kenthurst": {'price': 140, "area_type": "north_west"},
    "Killara": {'price': 80, "area_type": "north_shore"},
    "Killarney Heights": {'price': 80, "area_type": "northern_beaches"},
    "Kings Langley": {'price': 110, "area_type": "north_west"},
    "Kings Park": {'price': 120, "area_type": "north_west"},
    "Kingsford": {'price': 70, "area_type": "eastern_suburbs"},
    "Kingswood": {'price': 170, "area_type": "outer_west"},
    "Kirribilli": {'price': 60, "area_type": "north_shore"},
    "Kurraba Point": {'price': 70, "area_type": "north_shore"},
    "La Perouse": {'price': 100, "area_type": "eastern_suburbs"},
    "Lakemba": {'price': 60, "area_type": "west"},
    "Lalor Park": {'price': 120, "area_type": "north_west"},
    "Lane Cove": {'price': 70, "area_type": "north_shore"},
    "Lane Cove North": {'price': 70, "area_type": "north_shore"},
    "Lane Cove West": {'price': 70, "area_type": "north_shore"},
    "Lansdowne": {'price': 80, "area_type": "west"},
    "Lavender Bay": {'price': 70, "area_type": "north_shore"},
    "Leichhardt": {'price': 60, "area_type": "inner_west"},
    "Lethbridge Park": {'price': 100, "area_type": "outer_west"},
    "Liberty Grove": {'price': 60, "area_type": "inner_west"},
    "Lidcombe": {'price': 60, "area_type": "west"},
    "Lilyfield": {'price': 50, "area_type": "inner_west"},
    "Lindfield": {'price': 70, "area_type": "north_shore"},
    "Linley Point": {'price': 60, "area_type": "north_shore"},
    "Little Bay": {'price': 100, "area_type": "eastern_suburbs"},
    "Londonderry": {'price': 180, "area_type": "outer_west"},
    "Longueville": {'price': 80, "area_type": "north_shore"},
    "Macquarie Park": {'price': 80, "area_type": "north_west"},
    "Malabar": {'price': 90, "area_type": "eastern_suburbs"},
    "Manly": {'price': 90, "area_type": "northern_beaches"},
    "Manly Vale": {'price': 90, "area_type": "northern_beaches"},
    "Marayong": {'price': 140, "area_type": "outer_west"},
    "Maroubra": {'price': 80, "area_type": "eastern_suburbs"},
    "Maroubra Junction": {'price': 80, "area_type": "eastern_suburbs"},
    "Marrickville": {'price': 60, "area_type": "inner_west"},
    "Marsden Park": {'price': 160, "area_type": "outer_west"},
    "Marsfield": {'price': 80, "area_type": "north_west"},
    "Mascot": {'price': 70, "area_type": "eastern_suburbs"},
    "Matraville": {'price': 90, "area_type": "eastern_suburbs"},
    "McGraths Hill": {'price': 160, "area_type": "outer_west"},
    "McMahons Point": {'price': 70, "area_type": "north_shore"},
    "Meadowbank": {'price': 80, "area_type": "north_west"},
    "Melrose Park": {'price': 80, "area_type": "north_west"},
    "Merrylands": {'price': 100, "area_type": "central_west"},
    "Merrylands West": {'price': 100, "area_type": "central_west"},
    "Middle Cove": {'price': 70, "area_type": "north_shore"},
    "Millers Point": {'price': 70, "area_type": "sydney_city"},
    "Milperra": {'price': 60, "area_type": "west"},
    "Milsons Point": {'price': 70, "area_type": "sydney_city"},
    "Minchinbury": {'price': 160, "area_type": "outer_west"},
    "Mona Vale": {'price': 130, "area_type": "northern_beaches"},
    "Mortdale": {'price': 80, "area_type": "west"},
    "Mosman": {'price': 80, "area_type": "north_shore"},
    "Mount Colah": {'price': 120, "area_type": "upper_north_shore"},
    "Mount Kuring-gai": {'price': 120, "area_type": "upper_north_shore"},
    "Mt Druitt": {'price': 150, "area_type": "outer_west"},
    "Mulgrave": {'price': 160, "area_type": "outer_west"},
    "Naremburn": {'price': 70, "area_type": "north_shore"},
    "Narrabeen": {'price': 120, "area_type": "northern_beaches"},
    "Narraweena": {'price': 110, "area_type": "northern_beaches"},
    "Neutral Bay": {'price': 70, "area_type": "north_shore"},
    "Newington": {'price': 80, "area_type": "central_west"},
    "Newtown": {'price': 60, "area_type": "inner_west"},
    "Normanhurst": {'price': 100, "area_type": "upper_north_shore"},
    "North Balgowlah": {'price': 90, "area_type": "northern_beaches"},
    "North Bondi": {'price': 70, "area_type": "eastern_suburbs"},
    "North Curl Curl": {'price': 110, "area_type": "northern_beaches"},
    "North Epping": {'price': 90, "area_type": "north_west"},
    "North Kellyville": {'price': 130, "area_type": "north_west"},
    "North Manly": {'price': 90, "area_type": "northern_beaches"},
    "North Parramatta": {'price': 90, "area_type": "central_west"},
    "North Richmond": {'price': 190, "area_type": "outer_west"},
    "North Ryde": {'price': 80, "area_type": "north_west"},
    "North Strathfield": {'price': 70, "area_type": "west"},
    "North Sydney": {'price': 70, "area_type": "north_shore"},
    "North Turramurra": {'price': 100, "area_type": "north_shore"},
    "North Wahroonga": {'price': 110, "area_type": "upper_north_shore"},
    "North Willoughby": {'price': 70, "area_type": "north_shore"},
    "Northbridge": {'price': 70, "area_type": "north_shore"},
    "Northmead": {'price': 100, "area_type": "central_west"},
    "Northwood": {'price': 70, "area_type": "north_shore"},
    "Oakhurst": {'price': 150, "area_type": "outer_west"},
    "Oakville": {'price': 170, "area_type": "outer_west"},
    "Oatlands": {'price': 90, "area_type": "central_west"},
    "Old Guildford": {'price': 80, "area_type": "west"},
    "Old Toongabbie": {'price': 100, "area_type": "central_west"},
    "Olympic Park": {'price': 70, "area_type": "central_west"},
    "Orchard Hills": {'price': 150, "area_type": "outer_west"},
    "Oxley Park": {'price': 150, "area_type": "outer_west"},
    "Paddington": {'price': 70, "area_type": "sydney_city"},
    "Padstow": {'price': 70, "area_type": "west"},
    "Pagewood": {'price': 70, "area_type": "eastern_suburbs"},
    "Panania": {'price': 80, "area_type": "west"},
    "Parklea": {'price': 110, "area_type": "north_west"},
    "Parramatta": {'price': 90, "area_type": "central_west"},
    "Peakhurst": {'price': 70, "area_type": "west"},
    "Pemulwuy": {'price': 100, "area_type": "central_west"},
    "Pendle Hill": {'price': 100, "area_type": "central_west"},
    "Pennant Hills": {'price': 100, "area_type": "upper_north_shore"},
    "Penrith": {'price': 190, "area_type": "outer_west"},
    "Penshurst": {'price': 70, "area_type": "west"},
    "Petersham": {'price': 60, "area_type": "inner_west"},
    "Pitt Town": {'price': 200, "area_type": "outer_west"},
    "Plumpton": {'price': 150, "area_type": "outer_west"},
    "Point Piper": {'price': 70, "area_type": "eastern_suburbs"},
    "Potts Hill": {'price': 70, "area_type": "west"},
    "Potts Point": {'price': 70, "area_type": "sydney_city"},
    "Prospect": {'price': 100, "area_type": "outer_west"},
    "Punchbowl": {'price': 70, "area_type": "west"},
    "Putney": {'price': 80, "area_type": "north_west"},
    "Pymble": {'price': 90, "area_type": "north_shore"},
    "Pyrmont": {'price': 60, "area_type": "sydney_city"},
    "Quakers Hill": {'price': 140, "area_type": "outer_west"},
    "Queens Park": {'price': 60, "area_type": "eastern_suburbs"},
    "Randwick": {'price': 60, "area_type": "eastern_suburbs"},
    "Randwick North": {'price': 60, "area_type": "eastern_suburbs"},
    "Randwick West": {'price': 60, "area_type": "eastern_suburbs"},
    "Redfern": {'price': 50, "area_type": "eastern_suburbs"},
    "Regents Park": {'price': 80, "area_type": "west"},
    "Revesby": {'price': 70, "area_type": "west"},
    "Rhodes": {'price': 70, "area_type": "inner_west"},
    "Richmond": {'price': 180, "area_type": "outer_west"},
    "Riverstone": {'price': 150, "area_type": "outer_west"},
    "Riverview": {'price': 70, "area_type": "north_shore"},
    "Riverwood": {'price': 80, "area_type": "west"},
    "Ropes Crossing": {'price': 160, "area_type": "outer_west"},
    "Rose Bay": {'price': 70, "area_type": "eastern_suburbs"},
    "Rosebery": {'price': 60, "area_type": "eastern_suburbs"},
    "Rosehill": {'price': 80, "area_type": "central_west"},
    "Roselands": {'price': 60, "area_type": "west"},
    "Roseville": {'price': 80, "area_type": "north_shore"},
    "Roseville Chase": {'price': 80, "area_type": "north_shore"},
    "Rouse Hill": {'price': 150, "area_type": "north_west"},
    "Rozelle": {'price': 60, "area_type": "inner_west"},
    "Russell Lea": {'price': 70, "area_type": "inner_west"},
    "Rydalmere": {'price': 90, "area_type": "central_west"},
    "Ryde": {'price': 80, "area_type": "north_west"},
    "Schofields": {'price': 150, "area_type": "outer_west"},
    "Seaforth": {'price': 90, "area_type": "northern_beaches"},
    "Sefton": {'price': 80, "area_type": "west"},
    "Seven Hills": {'price': 100, "area_type": "north_west"},
    "Shalvey": {'price': 150, "area_type": "outer_west"},
    "Silverwater": {'price': 70, "area_type": "central_west"},
    "South Coogee": {'price': 70, "area_type": "eastern_suburbs"},
    "South Penrith": {'price': 190, "area_type": "outer_west"},
    "South Turramurra": {'price': 100, "area_type": "north_shore"},
    "South Wentworthville": {'price': 100, "area_type": "central_west"},
    "South Windsor": {'price': 240, "area_type": "outer_west"},
    "St Clair": {'price': 130, "area_type": "outer_west"},
    "St Ives": {'price': 90, "area_type": "north_shore"},
    "St Ives Chase": {'price': 100, "area_type": "north_shore"},
    "St Leonards": {'price': 60, "area_type": "north_shore"},
    "St Marys": {'price': 150, "area_type": "outer_west"},
    "St Marys North": {'price': 160, "area_type": "outer_west"},
    "Stanhope Gardens": {'price': 130, "area_type": "north_west"},
    "Stanmore": {'price': 60, "area_type": "inner_west"},
    "Strathfield": {'price': 70, "area_type": "west"},
    "Summer Hill": {'price': 60, "area_type": "inner_west"},
    "Surry Hills": {'price': 60, "area_type": "sydney_city"},
    "Sydney CBD": {'price': 60, "area_type": "sydney_city"},
    "Sydney City": {'price': 60, "area_type": "sydney_city"},
    "Tamarama": {'price': 70, "area_type": "eastern_suburbs"},
    "Telopea": {'price': 90, "area_type": "central_west"},
    "Tennyson Point": {'price': 80, "area_type": "north_west"},
    "Terrey Hills": {'price': 110, "area_type": "northern_beaches"},
    "The Ponds": {'price': 140, "area_type": "north_west"},
    "The Rocks": {'price': 60, "area_type": "sydney_city"},
    "Thornleigh": {'price': 100, "area_type": "upper_north_shore"},
    "Toongabbie": {'price': 100, "area_type": "central_west"},
    "Tregear": {'price': 130, "area_type": "outer_west"},
    "Turramurra": {'price': 100, "area_type": "north_shore"},
    "Ultimo": {'price': 60, "area_type": "sydney_city"},
    "Vaucluse": {'price': 80, "area_type": "eastern_suburbs"},
    "Villawood": {'price': 80, "area_type": "west"},
    "Vineyard": {'price': 160, "area_type": "outer_west"},
    "Wahroonga": {'price': 100, "area_type": "upper_north_shore"},
    "Waitara": {'price': 100, "area_type": "upper_north_shore"},
    "Wareemba": {'price': 70, "area_type": "inner_west"},
    "Warrawee": {'price': 100, "area_type": "upper_north_shore"},
    "Warriewood": {'price': 120, "area_type": "northern_beaches"},
    "Waterloo": {'price': 60, "area_type": "eastern_suburbs"},
    "Watsons Bay": {'price': 80, "area_type": "eastern_suburbs"},
    "Waverley": {'price': 70, "area_type": "eastern_suburbs"},
    "Waverton": {'price': 70, "area_type": "north_shore"},
    "Wentworthville": {'price': 90, "area_type": "central_west"},
    "Werrington": {'price': 160, "area_type": "outer_west"},
    "Werrington County": {'price': 160, "area_type": "outer_west"},
    "West Pennant Hills": {'price': 100, "area_type": "upper_north_shore"},
    "West Pymble": {'price': 90, "area_type": "north_shore"},
    "West Ryde": {'price': 80, "area_type": "north_west"},
    "Westleigh": {'price': 100, "area_type": "north_west"},
    "Westmead": {'price': 90, "area_type": "central_west"},
    "Whalan": {'price': 160, "area_type": "outer_west"},
    "Wheeler Heights": {'price': 100, "area_type": "northern_beaches"},
    "Wiley Park": {'price': 60, "area_type": "west"},
    "Willmot": {'price': 190, "area_type": "outer_west"},
    "Willoughby": {'price': 70, "area_type": "north_shore"},
    "Willoughby East": {'price': 70, "area_type": "north_shore"},
    "Winston Hills": {'price': 100, "area_type": "north_west"},
    "Wollstonecraft": {'price': 70, "area_type": "north_shore"},
    "Woollahra": {'price': 60, "area_type": "eastern_suburbs"},
    "Woolloomooloo": {'price': 60, "area_type": "sydney_city"},
    "Yagoona": {'price': 90, "area_type": "west"},
    "Zetland": {'price': 60, "area_type": "eastern_suburbs"}
}
    return more_suburbs
