def get_more_suburbs():  
    more_suburbs = {
        "Artarmon": {'price': 60},
        "Hotels In City": {'price': 60},    
        "Asquith": {'price': 60},
        "Auburn": {'price': 90},
        "Balgowlah": {'price': 80},
        "Balgowlah Heights": {'price': 80},
        "Balmain": {'price': 60},
        "Bass Hill": {'price': 60},
        "Bankstown": {'price': 60}, 
        "Baulkham Hills": {'price': 100},
        "Beaumont Hills": {'price': 100},
        "Beecroft": {'price': 100},
        "Belfield": {'price': 60},
        "Bella Vista": {'price': 110},
        "Belleveue Hill": {'price': 60},
        "Belmore": {'price': 60},
        "Berala": {'price': 80},
        "Berowra": {'price': 130},
        "Berowra Heights": {'price': 140},
        "Bevely Hills": {'price': 60},
        "Beverly Park": {'price': 60},
        "Bexley": {'price': 60},
        "Bexley North": {'price': 60},
        "Bidwill": {'price': 160},
        "Birchgrove": {'price': 70},
        "Birrong": {'price': 70},
        "Blackett": {'price': 140},
        "Blacktown": {'price': 100},
        "Bligh Park": {'price': 170},
        "Bondi": {'price': 80},
        "Bondi Junction": {'price': 60},
        "Bossley Park": {'price': 100},
        "Box Hill": {'price': 170},
        "Breakfast Point": {'price': 80},
        "Bronte": {'price': 60},
        "Brookvale": {'price': 100},
        "Bungarribee": {'price': 110}, 
        "Burwood": {'price': 60},
        "Cabarita": {'price': 70},
        "Cambridge Garden": {'price': 170},
        "Cambridge Park": {'price': 170},
        "Cammeray": {'price': 70},
        "Canada Bay": {'price': 70},
        "Canterbury": {'price': 60},
        "Carlingford": {'price': 90},
        "Castle Hill": {'price': 100},
        "Castlecove": {'price': 70},
        "Castlecrag": {'price': 70},
        "Castlereagh": {'price': 150},
        "Chatswood": {'price': 70},
        "Cheltenham": {'price': 90},
        "Cherrybrook": {'price': 110},
        "Chester Hill": {'price': 80},
        "Chullora": {'price': 80},
        "Claremont Meadow": {'price': 160},
        "Clyde": {'price': 60},
        "Colebee": {'price': 130},
        "Colyton": {'price': 140},
        "Concord": {'price': 70},
        "Concord West": {'price': 70},
        "Condell Park": {'price': 70},
        "Constitution Hill": {'price': 80},
        "Coogee": {'price': 60}, 
        "Cranebrook": {'price': 180},
        "Cremorne": {'price': 60},
        "Crows Nest": {'price': 60},
        "Croydon": {'price': 60},
        "Croydon Park": {'price': 60},
        "Darling Point": {'price': 50},
        "Darlinghurst": {'price': 50},
        "Dean Park": {'price': 120},
        "Dee Why": {'price': 80},
        "Denistone": {'price': 70},
        "Dharruk": {'price': 120},
        "Doonside": {'price': 110},
        "Drummoyne": {'price': 60},
        "Dulwitch Hill": {'price': 60},
        "Dundas": {'price': 70},
        "Dural": {'price': 100},
        "East Killara": {'price': 80},
        "East Lindfield": {'price': 70},
        "East Ryde": {'price': 70},
        "Eastern Creek": {'price': 130},
        "Eastwood": {'price': 80},
        "Edensor Park": {'price': 100},
        "Elanora Heights": {'price': 100},
        "Emerton": {'price': 150},
        "Emu Plains": {'price': 190},
        "Enfield": {'price': 50},
        "Enmore": {'price': 50},
        "Epping": {'price': 80},
        "Ermington": {'price': 80},
        "Erskin Park": {'price': 130},
        "Fairlight": {'price': 70},
        "Five Dock": {'price': 60},
        "Forest Lodge": {'price': 50},
        "Forestville": {'price': 80},
        "French Forest": {'price': 90},
        "Freshwater": {'price': 100},
        "Galston": {'price': 130},
        "Georges Hall": {'price': 60},
        "Girraween": {'price': 90},
        "Gladesville": {'price': 60},
        "Glendenning": {'price': 110},
        "Glenhaven": {'price': 110},
        "Glenmore Park": {'price': 190},
        "Glenwood": {'price': 120},
        "Gordon": {'price': 80},
        "Granville": {'price': 80},
        "Greenacre": {'price': 60},
        "Greenwich": {'price': 60},
        "Greystanes": {'price': 90},
        "Guildford": {'price': 80},
        "Harberfield": {'price': 60},
        "Harris Park": {'price': 80},
        "Hassal Grove": {'price': 130},
        "Henley": {'price': 60},
        "Hebersham": {'price': 110},
        "Holroyd": {'price': 80},
        "Homebush": {'price': 60},
        "Hornsby": {'price': 100},
        "Hornsby Heights": {'price': 110},
        "Hunters Hill": {'price': 70},
        "Huntingwood": {'price': 120},
        "Huntley Point": {'price': 60},
        "Hurstville": {'price': 50},
        "Jamisontown": {'price': 190},
        "Jordan Springs": {'price': 180},
        "Kellyville": {'price': 110},
        "Keyllyville Ridge": {'price': 120},
        "Kenthurst": {'price': 140},
        "Killara": {'price': 80},
        "Killarney Heights": {'price': 80},
        "Kings Langley": {'price': 110},
        "Kings Park": {'price': 120},
        "Kirribilli": {'price': 60},
        "Lalor Park": {'price': 120},
        "Lane Cove": {'price': 70},
        "Leichhardt": {'price': 60},
        "Lethbridge Park": {'price': 100},
        "Lewwisham": {'price': 50},
        "Liberty Grove": {'price': 60},
        "Lidcombe": {'price': 60},
        "Lindfield": {'price': 70},
        "Linley Point": {'price': 60},
        "Liyfield": {'price': 50},
        "Longueville": {'price': 80},
        "Macquarie Park": {'price': 80},
        "Manly": {'price': 90},
        "Manly Vale": {'price': 90},
        "Marayong": {'price': 140},
        "Marsden Park": {'price': 160},
        "Marsfield": {'price': 80},
        "McGraths Hill": {'price': 160},
        "Mcmahons Point": {'price': 70},
        "Meadowbank": {'price': 80},
        "Melrose Park": {'price': 80},
        "Merrylands": {'price': 100},
        "Michinbery": {'price': 160},
        "Middle Cove": {'price': 70},
        "Millers Point": {'price': 70}, 
        "Milpera": {'price': 60},
        "Milsons Point": {'price': 70},
        "Mortdale": {'price': 80},
        "Mortlake": {'price': 60},
        "Mosman": {'price': 80},
        "Mt Colah": {'price': 120},
        "Mt Druitt": {'price': 150},
        "Mt Kuring Gai": {'price': 120},
        "Mulgrave": {'price': 160},
        "Naremburn": {'price': 70},
        "Narraweena": {'price': 110},
        "Neutral Bay": {'price': 70},
        "Newington": {'price': 80},
        "Normanhurst": {'price': 100},
        "North Balowlah": {'price': 90},
        "North Bondi": {'price': 70},
        "North Epping": {'price': 90},
        "North Parramatta": {'price': 90},
        "North Rocks": {'price': 100},
        "North Ryde": {'price': 80},
        "North Strathfield": {'price': 70},
        "North Sydney": {'price': 70},
        "North Turramurra": {'price': 100}, 
        "Northbridge": {'price': 70},
        "Northmead": {'price': 100},
        "Northwood": {'price': 70},
        "Oakhurst": {'price': 150},
        "Oakville": {'price': 170},
        "Oatland": {'price': 90},
        "Old Toongabbie": {'price': 100},
        "Olympic Park": {'price': 70},
        "Orchard Hill": {'price': 150},
        "Oxley Park": {'price': 150},
        "Paddington": {'price': 70},
        "Panania": {'price': 80},
        "Pairiewood": {'price': 110},
        "Parklea": {'price': 110},
        "Parramatta": {'price': 90},
        "Peakhurst": {'price': 70},
        "Pemulway": {'price': 100},
        "Pendle Hill": {'price': 100},
        "Pennant Hills": {'price': 100},
        "Penrith": {'price': 190},
        "Plumpton": {'price': 150},
        "Potts Point": {'price': 70},
        "Prospect": {'price': 100},
        "Punchbowl": {'price': 70},
        "Putney": {'price': 80},
        "Pymble": {'price': 90},
        "Pyrmont": {'price': 60},
        "Quakers Hill": {'price': 140},
        "Regents Park": {'price': 80},
        "Revesby": {'price': 70},
        "Rhodes": {'price': 70},
        "Richmond": {'price': 180},
        "Riverston": {'price': 150},
        "Riverview": {'price': 70},
        "Riverwood": {'price': 80},
        "Rooty Hill": {'price': 150},
        "Ropes Crossing": {'price': 160},
        "Rose Hill": {'price': 80},
        "Roseville": {'price': 80},
        "Roseville Chase": {'price': 80},
        "Rouse Hill": {'price': 150},
        "Russel Lea": {'price': 70},
        "Rydalmere": {'price': 90},
        "Ryde": {'price': 80},
        "Seaforth": {'price': 90},
        "Sefton": {'price': 80},
        "Seven Hills": {'price': 100},
        "Shalvey": {'price': 150},
        "Silverwater": {'price': 70},
        "Schofields": {'price': 150},
        "South Turramurra": {'price': 100},
        "South Wentworthville": {'price': 100},
        "St Clair": {'price': 130},
        "St Ives": {'price': 90},
        "St Leonards": {'price': 60},
        "St Marys": {'price': 150},
        "St Marys North": {'price': 160},
        "Stanhope Garden": {'price': 130},
        "Strathfield": {'price': 70},
        "Summer Hill": {'price': 60},
        "Sydney City": {'price': 60}, 
        "Telopea": {'price': 90},
        "Tennyson Point": {'price': 80},
        "Terrey Hills": {'price': 110},
        "The Ponds": {'price': 140},
        "Thornleigh": {'price': 100},
        "Toongabbie": {'price': 100},
        "Top Ryde": {'price': 80},
        "Tregear": {'price': 130},
        "Turramurra": {'price': 100},
        "Vineyard": {'price': 160},
        "Wahroonga": {'price': 100},
        "Waitara": {'price': 100},
        "Warrawee": {'price': 100},
        "Watsons Bay": {'price': 80}, 
        "Waverley": {'price': 70},
        "Waverton": {'price': 70},
        "Wentworth Point": {'price': 70},
        "Wentworthville": {'price': 90},
        "Werrington": {'price': 160},
        "West Pennant Hills": {'price': 100},
        "West Pymble": {'price': 90},
        "West Ryde": {'price': 80},
        "Westleigh": {'price': 100},
        "Westmead": {'price': 90},
        "Whalan": {'price': 160},
        "Willmot": {'price': 190},
        "Willoughby": {'price': 70},
        "Winsor": {'price': 240},
        "Winston Hill": {'price': 100},
        "Wollstoncraft": {'price': 70},
        "Woodcroft": {'price': 120},
        "Woollahra": {'price': 60},
        "Woolwich": {'price': 80}, 
        "Yagoona": {'price': 90},
        }
    return more_suburbs

more_suburbs = get_more_suburbs() 
