def get_more_suburbs():
    more_suburbs = {
        # Sydney City
        "Darling Point": {'price': 50, "area_type": "sydney_city"},
        "Darlinghurst": {'price': 50, "area_type": "sydney_city"},
        "Enmore": {'price': 50, "area_type": "sydney_city"},
        "Leichhardt": {'price': 60, "area_type": "sydney_city"},
        "Millers Point": {'price': 70, "area_type": "sydney_city"},
        "Milsons Point": {'price': 70, "area_type": "sydney_city"},
        "Potts Point": {'price': 70, "area_type": "sydney_city"},
        "Pyrmont": {'price': 60, "area_type": "sydney_city"},
        "Sydney City": {'price': 60, "area_type": "sydney_city"},
        "Watsons Bay": {'price': 80, "area_type": "sydney_city"},
        "Woollahra": {'price': 60, "area_type": "sydney_city"},

        # North Shore
        "Artarmon": {'price': 60, "area_type": "north_shore"},
        "Asquith": {'price': 60, "area_type": "north_shore"},
        "Chatswood": {'price': 70, "area_type": "north_shore"},
        "Kirribilli": {'price': 60, "area_type": "north_shore"},
        "Lane Cove": {'price': 70, "area_type": "north_shore"},
        "North Sydney": {'price': 70, "area_type": "north_shore"},
        "St Leonards": {'price': 60, "area_type": "north_shore"},
        "St Ives": {'price': 90, "area_type": "north_shore"},
        "Mosman": {'price': 80, "area_type": "north_shore"},
        "Neutral Bay": {'price': 70, "area_type": "north_shore"},
        "Crows Nest": {'price': 60, "area_type": "north_shore"},

        # Northern Beaches
        "Balgowlah": {'price': 80, "area_type": "northern_beaches"},
        "Balgowlah Heights": {'price': 80, "area_type": "northern_beaches"},
        "Brookvale": {'price': 100, "area_type": "northern_beaches"},
        "Castle Cove": {'price': 70, "area_type": "northern_beaches"},
        "Dee Why": {'price': 80, "area_type": "northern_beaches"},
        "Freshwater": {'price': 100, "area_type": "northern_beaches"},
        "Fairlight": {'price': 70, "area_type": "northern_beaches"},
        "Bondi": {'price': 80, "area_type": "eastern_suburbs"},
        "North Bondi": {'price': 70, "area_type": "eastern_suburbs"},
        "Coogee": {'price': 60, "area_type": "eastern_suburbs"},
        "Bronte": {'price': 60, "area_type": "eastern_suburbs"},
        "Breakfast Point": {'price': 80, "area_type": "eastern_suburbs"},

        # West Sydney
        "Auburn": {'price': 90, "area_type": "west_sydney"},
        "Bass Hill": {'price': 60, "area_type": "west_sydney"},
        "Bankstown": {'price': 60, "area_type": "west_sydney"},
        "Belfield": {'price': 60, "area_type": "west_sydney"},
        "Belmore": {'price': 60, "area_type": "west_sydney"},
        "Berala": {'price': 80, "area_type": "west_sydney"},
        "Bellevue Hill": {'price': 60, "area_type": "west_sydney"},
        "Beverly Park": {'price': 60, "area_type": "west_sydney"},
        "Bexley": {'price': 60, "area_type": "west_sydney"},
        "Bexley North": {'price': 60, "area_type": "west_sydney"},
        "Birchgrove": {'price': 70, "area_type": "west_sydney"},
        "Birrong": {'price': 70, "area_type": "west_sydney"},
        "Bossley Park": {'price': 100, "area_type": "west_sydney"},
        "Burwood": {'price': 60, "area_type": "west_sydney"},
        "Cabarita": {'price': 70, "area_type": "west_sydney"},
        "Cammeray": {'price': 70, "area_type": "west_sydney"},
        "Canada Bay": {'price': 70, "area_type": "west_sydney"},
        "Canterbury": {'price': 60, "area_type": "west_sydney"},
        "Castlecrag": {'price': 70, "area_type": "west_sydney"},
        "Chester Hill": {'price': 80, "area_type": "west_sydney"},
        "Chullora": {'price': 80, "area_type": "west_sydney"},
        "Clyde": {'price': 60, "area_type": "west_sydney"},
        "Concord": {'price': 70, "area_type": "west_sydney"},
        "Concord West": {'price': 70, "area_type": "west_sydney"},
        "Condell Park": {'price': 70, "area_type": "west_sydney"},
        "Constitution Hill": {'price': 80, "area_type": "west_sydney"},
        "Croydon": {'price': 60, "area_type": "west_sydney"},
        "Croydon Park": {'price': 60, "area_type": "west_sydney"},
        "Dean Park": {'price': 120, "area_type": "west_sydney"},
        "Drummoyne": {'price': 60, "area_type": "west_sydney"},
        "Dulwich Hill": {'price': 60, "area_type": "west_sydney"},
        "Dundas": {'price': 70, "area_type": "west_sydney"},
        "Eastwood": {'price': 80, "area_type": "west_sydney"},
        "Edensor Park": {'price': 100, "area_type": "west_sydney"},
        "Enfield": {'price': 50, "area_type": "west_sydney"},
        "Ermington": {'price': 80, "area_type": "west_sydney"},
        "Five Dock": {'price': 60, "area_type": "west_sydney"},
        "Forest Lodge": {'price': 50, "area_type": "west_sydney"},
        "Forestville": {'price': 80, "area_type": "west_sydney"},
        "Georges Hall": {'price': 60, "area_type": "west_sydney"},
        "Gladesville": {'price': 60, "area_type": "west_sydney"},
        "Guildford": {'price': 80, "area_type": "west_sydney"},
        "Harberfield": {'price': 60, "area_type": "west_sydney"},
        "Harris Park": {'price': 80, "area_type": "west_sydney"},
        "Henley": {'price': 60, "area_type": "west_sydney"},
        "Holroyd": {'price': 80, "area_type": "west_sydney"},
        "Homebush": {'price': 60, "area_type": "west_sydney"},
        "Huntley Point": {'price': 60, "area_type": "west_sydney"},
        "Hurstville": {'price': 50, "area_type": "west_sydney"},
        "Lalor Park": {'price': 120, "area_type": "west_sydney"},
        "Lethbridge Park": {'price': 100, "area_type": "west_sydney"},
        "Lewisham": {'price': 50, "area_type": "west_sydney"},
        "Lidcombe": {'price': 60, "area_type": "west_sydney"},
        "Linley Point": {'price': 60, "area_type": "west_sydney"},
        "Longueville": {'price': 80, "area_type": "west_sydney"},
        "Mcmahons Point": {'price': 70, "area_type": "west_sydney"},
        "Meadowbank": {'price': 80, "area_type": "west_sydney"},
        "Melrose Park": {'price': 80, "area_type": "west_sydney"},
        "Merrylands": {'price': 100, "area_type": "west_sydney"},
        "Middle Cove": {'price': 70, "area_type": "west_sydney"},
        "Milpera": {'price': 60, "area_type": "west_sydney"},
        "Mortdale": {'price': 80, "area_type": "west_sydney"},
        "Mortlake": {'price': 60, "area_type": "west_sydney"},
        "Naremburn": {'price': 70, "area_type": "west_sydney"},
        "Newington": {'price': 80, "area_type": "west_sydney"},
        "Northbridge": {'price': 70, "area_type": "west_sydney"},
        "Northmead": {'price': 100, "area_type": "west_sydney"},
        "Northwood": {'price': 70, "area_type": "west_sydney"},
        "Oatland": {'price': 90, "area_type": "west_sydney"},
        "Old Toongabbie": {'price': 100, "area_type": "west_sydney"},
        "Olympic Park": {'price': 70, "area_type": "west_sydney"},
        "Panania": {'price': 80, "area_type": "west_sydney"},
        "Peakhurst": {'price': 70, "area_type": "west_sydney"},
        "Pemulway": {'price': 100, "area_type": "west_sydney"},
        "Prospect": {'price': 100, "area_type": "west_sydney"},
        "Punchbowl": {'price': 70, "area_type": "west_sydney"},
        "Regents Park": {'price': 80, "area_type": "west_sydney"},
        "Revesby": {'price': 70, "area_type": "west_sydney"},
        "Rhodes": {'price': 70, "area_type": "west_sydney"},
        "Riverview": {'price': 70, "area_type": "west_sydney"},
        "Riverwood": {'price': 80, "area_type": "west_sydney"},
        "Sefton": {'price': 80, "area_type": "west_sydney"},
        "Summer Hill": {'price': 60, "area_type": "west_sydney"},
        "Toongabbie": {'price': 100, "area_type": "west_sydney"},
        "Waverley": {'price': 70, "area_type": "west_sydney"},
        "Waverton": {'price': 70, "area_type": "west_sydney"},
        "Wentworth Point": {'price': 70, "area_type": "west_sydney"},
        "Wentworthville": {'price': 90, "area_type": "west_sydney"},
        "Westleigh": {'price': 100, "area_type": "west_sydney"},
        "Westmead": {'price': 90, "area_type": "west_sydney"},
        "Waitara": {'price': 100, "area_type": "west_sydney"},
        "Warrawee": {'price': 100, "area_type": "west_sydney"},
        "Wollstoncraft": {'price': 70, "area_type": "west_sydney"},
        "Woolwich": {'price': 80, "area_type": "west_sydney"},
        "Yagoona": {'price': 90, "area_type": "west_sydney"},

        # North West Sydney
        "Baulkham Hills": {'price': 100, "area_type": "north_west_sydney"},
        "Beaumont Hills": {'price': 100, "area_type": "north_west_sydney"},
        "Beecroft": {'price': 100, "area_type": "north_west_sydney"},
        "Bella Vista": {'price': 110, "area_type": "north_west_sydney"},
        "Berowra": {'price': 130, "area_type": "north_west_sydney"},
        "Berowra Heights": {'price': 140, "area_type": "north_west_sydney"},
        "Bidwill": {'price': 160, "area_type": "north_west_sydney"},
        "Blackett": {'price': 140, "area_type": "north_west_sydney"},
        "Blacktown": {'price': 100, "area_type": "north_west_sydney"},
        "Bligh Park": {'price': 170, "area_type": "north_west_sydney"},
        "Bungarribee": {'price': 110, "area_type": "north_west_sydney"},
        "Cambridge Garden": {'price': 170, "area_type": "north_west_sydney"},
        "Cambridge Park": {'price': 170, "area_type": "north_west_sydney"},
        "Carlingford": {'price': 90, "area_type": "north_west_sydney"},
        "Castle Hill": {'price': 100, "area_type": "north_west_sydney"},
        "Castlereagh": {'price': 150, "area_type": "north_west_sydney"},
        "Cherrybrook": {'price': 110, "area_type": "north_west_sydney"},
        "Colebee": {'price': 130, "area_type": "north_west_sydney"},
        "Colyton": {'price': 140, "area_type": "north_west_sydney"},
        "Constitution Hill": {'price': 80, "area_type": "north_west_sydney"},
        "Cranebrook": {'price': 180, "area_type": "north_west_sydney"},
        "Denistone": {'price': 70, "area_type": "north_west_sydney"},
        "Dharruk": {'price': 120, "area_type": "north_west_sydney"},
        "Doonside": {'price': 110, "area_type": "north_west_sydney"},
        "Dural": {'price': 100, "area_type": "north_west_sydney"},
        "East Killara": {'price': 80, "area_type": "north_west_sydney"},
        "East Lindfield": {'price': 70, "area_type": "north_west_sydney"},
        "East Ryde": {'price': 70, "area_type": "north_west_sydney"},
        "Eastern Creek": {'price': 130, "area_type": "north_west_sydney"},
        "Elanora Heights": {'price': 100, "area_type": "north_west_sydney"},
        "Emerton": {'price': 150, "area_type": "north_west_sydney"},
        "Emu Plains": {'price': 190, "area_type": "north_west_sydney"},
        "Epping": {'price': 80, "area_type": "north_west_sydney"},
        "Erskine Park": {'price': 130, "area_type": "north_west_sydney"},
        "Frenchs Forest": {'price': 90, "area_type": "north_west_sydney"},
        "Galston": {'price': 130, "area_type": "north_west_sydney"},
        "Girraween": {'price': 90, "area_type": "north_west_sydney"},
        "Glendenning": {'price': 110, "area_type": "north_west_sydney"},
        "Glenhaven": {'price': 110, "area_type": "north_west_sydney"},
        "Glenmore Park": {'price': 190, "area_type": "north_west_sydney"},
        "Glenwood": {'price': 120, "area_type": "north_west_sydney"},
        "Gordon": {'price': 80, "area_type": "north_west_sydney"},
        "Greystanes": {'price': 90, "area_type": "north_west_sydney"},
        "Hassall Grove": {'price': 130, "area_type": "north_west_sydney"},
        "Hebersham": {'price': 110, "area_type": "north_west_sydney"},
        "Hornsby": {'price': 100, "area_type": "north_west_sydney"},
        "Hornsby Heights": {'price': 110, "area_type": "north_west_sydney"},
        "Hunters Hill": {'price': 70, "area_type": "north_west_sydney"},
        "Huntingwood": {'price': 120, "area_type": "north_west_sydney"},
        "Jamisontown": {'price': 190, "area_type": "north_west_sydney"},
        "Jordan Springs": {'price': 180, "area_type": "north_west_sydney"},
        "Kellyville": {'price': 110, "area_type": "north_west_sydney"},
        "Kellyville Ridge": {'price': 120, "area_type": "north_west_sydney"},
        "Kenthurst": {'price': 140, "area_type": "north_west_sydney"},
        "Killara": {'price': 80, "area_type": "north_west_sydney"},
        "Killarney Heights": {'price': 80, "area_type": "north_west_sydney"},
        "Kings Langley": {'price': 110, "area_type": "north_west_sydney"},
        "Kings Park": {'price': 120, "area_type": "north_west_sydney"},
        "Macquarie Park": {'price': 80, "area_type": "north_west_sydney"},
        "Manly": {'price': 90, "area_type": "north_west_sydney"},
        "Manly Vale": {'price': 90, "area_type": "north_west_sydney"},
        "Marsden Park": {'price': 160, "area_type": "north_west_sydney"},
        "McGraths Hill": {'price': 160, "area_type": "north_west_sydney"},
        "Michinbury": {'price': 160, "area_type": "north_west_sydney"},
        "Mt Colah": {'price': 120, "area_type": "north_west_sydney"},
        "Mt Druitt": {'price': 150, "area_type": "north_west_sydney"},
        "Mt Kuring-gai": {'price': 120, "area_type": "north_west_sydney"},
        "Mulgrave": {'price': 160, "area_type": "north_west_sydney"},
        "Narraweena": {'price': 110, "area_type": "north_west_sydney"},
        "Normanhurst": {'price': 100, "area_type": "north_west_sydney"},
        "North Balwyn": {'price': 90, "area_type": "north_west_sydney"},
        "North Epping": {'price': 90, "area_type": "north_west_sydney"},
        "North Parramatta": {'price': 90, "area_type": "north_west_sydney"},
        "North Rocks": {'price': 100, "area_type": "north_west_sydney"},
        "North Ryde": {'price': 80, "area_type": "north_west_sydney"},
        "North Strathfield": {'price': 70, "area_type": "north_west_sydney"},
        "North Turramurra": {'price': 100, "area_type": "north_west_sydney"},
        "Oakhurst": {'price': 150, "area_type": "north_west_sydney"},
        "Oakville": {'price': 170, "area_type": "north_west_sydney"},
        "Orchard Hill": {'price': 150, "area_type": "north_west_sydney"},
        "Oxley Park": {'price': 150, "area_type": "north_west_sydney"},
        "Pairiewood": {'price': 110, "area_type": "north_west_sydney"},
        "Parklea": {'price': 110, "area_type": "north_west_sydney"},
        "Parramatta": {'price': 90, "area_type": "north_west_sydney"},
        "Pendle Hill": {'price': 100, "area_type": "north_west_sydney"},
        "Pennant Hills": {'price': 100, "area_type": "north_west_sydney"},
        "Penrith": {'price': 190, "area_type": "north_west_sydney"},
        "Plumpton": {'price': 150, "area_type": "north_west_sydney"},
        "Quakers Hill": {'price': 140, "area_type": "north_west_sydney"},
        "Rouse Hill": {'price': 150, "area_type": "north_west_sydney"},
        "Rose Hill": {'price': 80, "area_type": "north_west_sydney"},
        "Roseville": {'price': 80, "area_type": "north_west_sydney"},
        "Roseville Chase": {'price': 80, "area_type": "north_west_sydney"},
        "Rydalmere": {'price': 90, "area_type": "north_west_sydney"},
        "Ryde": {'price': 80, "area_type": "north_west_sydney"},
        "Seaforth": {'price': 90, "area_type": "north_west_sydney"},
        "Seven Hills": {'price': 100, "area_type": "north_west_sydney"},
        "Shalvey": {'price': 150, "area_type": "north_west_sydney"},
        "Schofields": {'price': 150, "area_type": "north_west_sydney"},
        "South Turramurra": {'price': 100, "area_type": "north_west_sydney"},
        "South Wentworthville": {'price': 100, "area_type": "north_west_sydney"},
        "St Clair": {'price': 130, "area_type": "north_west_sydney"},
        "Stanhope Garden": {'price': 130, "area_type": "north_west_sydney"},
        "Telopea": {'price': 90, "area_type": "north_west_sydney"},
        "Terrey Hills": {'price': 110, "area_type": "north_west_sydney"},
        "Thornleigh": {'price': 100, "area_type": "north_west_sydney"},
        "Top Ryde": {'price': 80, "area_type": "north_west_sydney"},
        "Tregear": {'price': 130, "area_type": "north_west_sydney"},
        "Turramurra": {'price': 100, "area_type": "north_west_sydney"},
        "Vineyard": {'price': 160, "area_type": "north_west_sydney"},
        "Wahroonga": {'price': 100, "area_type": "north_west_sydney"},
        "Willmot": {'price': 190, "area_type": "north_west_sydney"},
        "Winsor": {'price': 240, "area_type": "north_west_sydney"},
        "Winston Hill": {'price': 100, "area_type": "north_west_sydney"},
        "Woodcroft": {'price': 120, "area_type": "north_west_sydney"},
    }
    return more_suburbs

more_suburbs = get_more_suburbs()

