def get_home_suburbs(): 
    home_suburbs = [
        "Alexandria",
        "Allambie Heights",
        "Arndell Park",
        "Artarmon",
        "Ashfield",
        "Asquith",
        "Auburn",
        "Balgowlah",
        "Balgowlah Heights",
        "Balmain",
        "Banksmeadow",
        "Bankstown",
        "Barangaroo",
        "Bass Hill",
        "Baulkham Hills",
        "Beaconsfield",
        "Beacon Hill",
        "Beaumont Hills",
        "Beauty Point",
        "Beecroft",
        "Belfield",
        "Bella Vista",
        "Bellevue Hill",
        "Belmore",
        "Belrose",
        "Berala",
        "Berowra",
        "Berowra Heights",
        "Berowra Waters",
        "Beverly Hills",
        "Beverly Park",
        "Bexley",
        "Bexley North",
        "Bidwill",
        "Birchgrove",
        "Birrong",
        "Blackett",
        "Blacktown",
        "Bligh Park",
        "Bondi",
        "Bondi Beach",
        "Bondi Junction",
        "Botany",
        "Box Hill",
        "Breakfast Point",
        "Bronte",
        "Brooklyn",
        "Brookvale",
        "Burwood",
        "Cabarita",
        "Caddens",
        "Cambridge Gardens",
        "Cambridge Park",
        "Camellia",
        "Cammeray",
        "Camperdown",
        "Canada Bay",
        "Carlingford",
        "Castle Cove",
        "Castle Hill",
        "Castlecrag",
        "Castlereagh",
        "Chatswood",
        "Chatswood West",
        "Cheltenham",
        "Cherrybrook",
        "Chester Hill",
        "Chifley",
        "Chippendale",
        "Chiswick",
        "Chullora",
        "Clovelly",
        "Clyde",
        "Colebee",
        "Collaroy",
        "Collaroy Plateau",
        "Colyton",
        "Concord",
        "Concord West",
        "Condell Park",
        "Constitution Hill",
        "Coogee",
        "Cowan",
        "Cranebrook",
        "Cremorne",
        "Cremorne Point",
        "Cromer",
        "Crows Nest",
        "Curl Curl",
        "Darling Point",
        "Darlinghurst",
        "Davidson",
        "Dean Park",
        "Dee Why",
        "Denistone",
        "Denistone East",
        "Dharruk",
        "Doonside",
        "Double Bay",
        "Drummoyne",
        "Dulwich Hill",
        "Dundas",
        "Dundas Valley",
        "Dural",
        "East Killara",
        "East Lindfield",
        "East Ryde",
        "Eastern Creek",
        "Eastgardens",
        "Eastlakes",
        "Eastwood",
        "Edgecliff",
        "Elanora Heights",
        "Emerton",
        "Emu Plains",
        "Enfield",
        "Enmore",
        "Epping",
        "Ermington",
        "Eveleigh",
        "Fairlight",
        "Five Dock",
        "Forest Lodge",
        "Forestville",
        "Frenchs Forest",
        "Freshwater",
        "Galston",
        "Georges Hall",
        "Girraween",
        "Gladesville",
        "Glebe",
        "Glendenning",
        "Glenhaven",
        "Glenmore Park",
        "Glenwood",
        "Gordon",
        "Granville",
        "Greenacre",
        "Greenwich",
        "Greystanes",
        "Guildford",
        "Guildford West",
        "Haberfield",
        "Harris Park",
        "Hassall Grove",
        "Haymarket",
        "Hebersham",
        "Henley",
        "Hillsdale",
        "Homebush",
        "Homebush West",
        "Hornsby",
        "Hornsby Heights",
        "Hotels In City",
        "Huntingwood",
        "Huntleys Cove",
        "Huntleys Point",
        "Hurstville",
        "Ingleside",
        "Jamisontown",
        "Jordan Springs",
        "Kellyville",
        "Kellyville Ridge",
        "Kensington",
        "Kenthurst",
        "Killara",
        "Killarney Heights",
        "Kings Langley",
        "Kings Park",
        "Kingsford",
        "Kingswood",
        "Kirribilli",
        "Kurraba Point",
        "La Perouse",
        "Lakemba",
        "Lalor Park",
        "Lane Cove",
        "Lane Cove North",
        "Lane Cove West",
        "Lansdowne",
        "Lavender Bay",
        "Leichhardt",
        "Lethbridge Park",
        "Liberty Grove",
        "Lidcombe",
        "Lilyfield",
        "Lindfield",
        "Linley Point",
        "Little Bay",
        "Londonderry",
        "Longueville",
        "Macquarie Park",
        "Malabar",
        "Manly",
        "Manly Vale",
        "Marayong",
        "Maroubra",
        "Maroubra Junction",
        "Marrickville",
        "Marsden Park",
        "Marsfield",
        "Mascot",
        "Matraville",
        "McGraths Hill",
        "McMahons Point",
        "Meadowbank",
        "Melrose Park",
        "Merrylands",
        "Merrylands West",
        "Middle Cove",
        "Millers Point",
        "Milperra",
        "Milsons Point",
        "Minchinbury",
        "Mona Vale",
        "Mortdale",
        "Mosman",
        "Mount Colah",
        "Mount Kuring-gai",
        "Mt Druitt",
        "Mulgrave",
        "Naremburn",
        "Narrabeen",
        "Narraweena",
        "Neutral Bay",
        "Newington",
        "Newtown",
        "Normanhurst",
        "North Balgowlah",
        "North Bondi",
        "North Curl Curl",
        "North Epping",
        "North Kellyville",
        "North Manly",
        "North Parramatta",
        "North Richmond",
        "North Ryde",
        "North Strathfield",
        "North Sydney",
        "North Turramurra",
        "North Wahroonga",
        "North Willoughby",
        "Northbridge",
        "Northmead",
        "Northwood",
        "Oakhurst",
        "Oakville",
        "Oatlands",
        "Old Guildford",
        "Old Toongabbie",
        "Olympic Park",
        "Orchard Hills",
        "Oxley Park",
        "Paddington",
        "Padstow",
        "Pagewood",
        "Panania",
        "Parklea",
        "Parramatta",
        "Peakhurst",
        "Pemulwuy",
        "Pendle Hill",
        "Pennant Hills",
        "Penrith",
        "Penshurst",
        "Petersham",
        "Pitt Town",
        "Plumpton",
        "Point Piper",
        "Potts Hill",
        "Potts Point",
        "Prospect",
        "Punchbowl",
        "Putney",
        "Pymble",
        "Pyrmont",
        "Quakers Hill",
        "Queens Park",
        "Randwick",
        "Randwick North",
        "Randwick West",
        "Redfern",
        "Regents Park",
        "Revesby",
        "Rhodes",
        "Richmond",
        "Riverstone",
        "Riverview",
        "Riverwood",
        "Rooty Hill",
        "Ropes Crossing",
        "Rose Bay",
        "Rosebery",
        "Rosehill",
        "Roselands",
        "Roseville",
        "Roseville Chase",
        "Rouse Hill",
        "Rozelle",
        "Russell Lea",
        "Rydalmere",
        "Ryde",
        "Schofields",
        "Seaforth",
        "Sefton",
        "Seven Hills",
        "Shalvey",
        "Silverwater",
        "South Coogee",
        "South Penrith",
        "South Turramurra",
        "South Wentworthville",
        "South Windsor",
        "St Clair",
        "St Ives",
        "St Ives Chase",
        "St Leonards",
        "St Marys",
        "St Marys North",
        "Stanhope Gardens",
        "Stanmore",
        "Strathfield",
        "Summer Hill",
        "Surry Hills",
        "Sydney CBD",
        "Sydney City",
        "Tamarama",
        "Telopea",
        "Tennyson Point",
        "Terrey Hills",
        "The Ponds",
        "The Rocks",
        "Thornleigh",
        "Toongabbie",
        "Tregear",
        "Turramurra",
        "Ultimo",
        "Vaucluse",
        "Villawood",
        "Vineyard",
        "Wahroonga",
        "Waitara",
        "Wareemba",
        "Warrawee",
        "Warriewood",
        "Waterloo",
        "Watsons Bay",
        "Waverley",
        "Waverton",
        "Wentworthville",
        "Werrington",
        "Werrington County",
        "West Pennant Hills",
        "West Pymble",
        "West Ryde",
        "Westleigh",
        "Westmead",
        "Whalan",
        "Wheeler Heights",
        "Wiley Park",
        "Willmot",
        "Willoughby",
        "Willoughby East",
        "Windsor",
        "Winston Hills",
        "Wollstonecraft",
        "Woollahra",
        "Woolloomooloo",
        "Yagoona",
        "Zetland"
    ]    
    return home_suburbs

