from functools import lru_cache

@lru_cache(maxsize=1)
def get_more_suburbs():
    more_suburbs = {
        # --- 1. SYDNEY CITY & CBD ---
        "Sydney City": {'price': 60, "area_type": "sydney_city"},
        "Sydney CBD": {'price': 60, "area_type": "sydney_city"},
        "Hotels In City": {'price': 60, "area_type": "sydney_city"},
        "Darlinghurst": {'price': 50, "area_type": "sydney_city"},
        "Darling Point": {'price': 50, "area_type": "sydney_city"},
        "Pyrmont": {'price': 60, "area_type": "sydney_city"},
        "Surry Hills": {'price': 60, "area_type": "sydney_city"},
        "Ultimo": {'price': 60, "area_type": "sydney_city"},
        "Barangaroo": {'price': 60, "area_type": "sydney_city"},
        "Millers Point": {'price': 70, "area_type": "sydney_city"},
        "Milsons Point": {'price': 70, "area_type": "sydney_city"},
        "Potts Point": {'price': 70, "area_type": "sydney_city"},
        "The Rocks": {'price': 60, "area_type": "sydney_city"},
        "Paddington": {'price': 70, "area_type": "sydney_city"},
        "Woolloomooloo": {'price': 60, "area_type": "sydney_city"},
        "Haymarket": {'price': 60, "area_type": "sydney_city"},
        "Glebe": {'price': 60, "area_type": "sydney_city"},

        # --- 2. INNER WEST ---
        "Ashfield": {'price': 60, "area_type": "inner_west"},
        "Balmain": {'price': 60, "area_type": "inner_west"},
        "Birchgrove": {'price': 70, "area_type": "inner_west"},
        "Breakfast Point": {'price': 80, "area_type": "inner_west"},
        "Cabarita": {'price': 70, "area_type": "inner_west"},
        "Camperdown": {'price': 60, "area_type": "inner_west"},
        "Canada Bay": {'price': 70, "area_type": "inner_west"},
        "Chiswick": {'price': 70, "area_type": "inner_west"},
        "Concord": {'price': 70, "area_type": "inner_west"},
        "Concord West": {'price': 70, "area_type": "inner_west"},
        "Drummoyne": {'price': 60, "area_type": "inner_west"},
        "Dulwich Hill": {'price': 60, "area_type": "inner_west"},
        "Enmore": {'price': 50, "area_type": "inner_west"},
        "Five Dock": {'price': 60, "area_type": "inner_west"},
        "Haberfield": {'price': 60, "area_type": "inner_west"},
        "Leichhardt": {'price': 60, "area_type": "inner_west"},
        "Lilyfield": {'price': 50, "area_type": "inner_west"},
        "Marrickville": {'price': 60, "area_type": "inner_west"},
        "Newtown": {'price': 60, "area_type": "inner_west"},
        "Petersham": {'price': 60, "area_type": "inner_west"},
        "Rhodes": {'price': 70, "area_type": "inner_west"},
        "Rozelle": {'price': 60, "area_type": "inner_west"},
        "Russell Lea": {'price': 70, "area_type": "inner_west"},
        "Stanmore": {'price': 60, "area_type": "inner_west"},
        "Summer Hill": {'price': 60, "area_type": "inner_west"},
        "Wareemba": {'price': 70, "area_type": "inner_west"},
        "Liberty Grove": {'price': 60, "area_type": "inner_west"},

        # --- 3. CENTRAL WEST (Parramatta & Surrounds) ---
        "Parramatta": {'price': 90, "area_type": "central_west"},
        "North Parramatta": {'price': 90, "area_type": "central_west"},
        "Westmead": {'price': 90, "area_type": "central_west"},
        "Northmead": {'price': 100, "area_type": "central_west"},
        "Granville": {'price': 80, "area_type": "central_west"},
        "Harris Park": {'price': 80, "area_type": "central_west"},
        "Merrylands": {'price': 100, "area_type": "central_west"},
        "Merrylands West": {'price': 100, "area_type": "central_west"},
        "Wentworthville": {'price': 90, "area_type": "central_west"},
        "South Wentworthville": {'price': 100, "area_type": "central_west"},
        "Toongabbie": {'price': 100, "area_type": "central_west"},
        "Old Toongabbie": {'price': 100, "area_type": "central_west"},
        "Pendle Hill": {'price': 100, "area_type": "central_west"},
        "Greystanes": {'price': 90, "area_type": "central_west"},
        "Pemulwuy": {'price': 100, "area_type": "central_west"},
        "Clyde": {'price': 60, "area_type": "central_west"},
        "Rosehill": {'price': 80, "area_type": "central_west"},
        "Rydalmere": {'price': 90, "area_type": "central_west"},
        "Ermington": {'price': 80, "area_type": "central_west"},
        "Dundas": {'price': 70, "area_type": "central_west"},
        "Dundas Valley": {'price': 80, "area_type": "central_west"},
        "Telopea": {'price': 90, "area_type": "central_west"},
        "Silverwater": {'price': 70, "area_type": "central_west"},
        "Newington": {'price': 80, "area_type": "central_west"},
        "Olympic Park": {'price': 70, "area_type": "central_west"},
        "Constitution Hill": {'price': 80, "area_type": "central_west"},
        "Girraween": {'price': 90, "area_type": "central_west"},
        "Oatlands": {'price': 90, "area_type": "central_west"},
        "Camellia": {'price': 80, "area_type": "central_west"},

        # --- 4. WEST (Canterbury-Bankstown & South West) ---
        "Auburn": {'price': 90, "area_type": "west"},
        "Bankstown": {'price': 60, "area_type": "west"},
        "Bass Hill": {'price': 60, "area_type": "west"},
        "Berala": {'price': 80, "area_type": "west"},
        "Beverly Hills": {'price': 60, "area_type": "west"},
        "Beverly Park": {'price': 60, "area_type": "west"},
        "Bexley": {'price': 60, "area_type": "west"},
        "Bexley North": {'price': 60, "area_type": "west"},
        "Birrong": {'price': 70, "area_type": "west"},
        "Chester Hill": {'price': 80, "area_type": "west"},
        "Chullora": {'price': 80, "area_type": "west"},
        "Greenacre": {'price': 60, "area_type": "west"},
        "Guildford": {'price': 80, "area_type": "west"},
        "Guildford West": {'price': 80, "area_type": "west"},
        "Lidcombe": {'price': 60, "area_type": "west"},
        "Revesby": {'price': 70, "area_type": "west"},
        "Yagoona": {'price': 90, "area_type": "west"},
        "Panania": {'price': 80, "area_type": "west"},
        "Riverwood": {'price': 80, "area_type": "west"},
        "Sefton": {'price': 80, "area_type": "west"},
        "Punchbowl": {'price': 70, "area_type": "west"},
        "Belmore": {'price': 60, "area_type": "west"},
        "Belfield": {'price': 60, "area_type": "west"},
        "Lakemba": {'price': 60, "area_type": "west"},
        "Wiley Park": {'price': 60, "area_type": "west"},
        "Roselands": {'price': 60, "area_type": "west"},
        "Burwood": {'price': 60, "area_type": "west"},
        "Homebush": {'price': 60, "area_type": "west"},
        "Homebush West": {'price': 60, "area_type": "west"},
        "Strathfield": {'price': 70, "area_type": "west"},
        "North Strathfield": {'price': 70, "area_type": "west"},
        "Enfield": {'price': 50, "area_type": "west"},
        "Hurstville": {'price': 50, "area_type": "west"},
        "Mortdale": {'price': 80, "area_type": "west"},
        "Penshurst": {'price': 70, "area_type": "west"},
        "Peakhurst": {'price': 70, "area_type": "west"},
        "Padstow": {'price': 70, "area_type": "west"},
        "Condell Park": {'price': 70, "area_type": "west"},
        "Georges Hall": {'price': 60, "area_type": "west"},
        "Milperra": {'price': 60, "area_type": "west"},
        "Regents Park": {'price': 80, "area_type": "west"},
        "Potts Hill": {'price': 70, "area_type": "west"},
        "Villawood": {'price': 80, "area_type": "west"},
        "Lansdowne": {'price': 80, "area_type": "west"},
        "Old Guildford": {'price': 80, "area_type": "west"},

        # --- 5. NORTH WEST (Hills District & Ryde Area) ---
        "Castle Hill": {'price': 100, "area_type": "north_west"},
        "Baulkham Hills": {'price': 100, "area_type": "north_west"},
        "Bella Vista": {'price': 110, "area_type": "north_west"},
        "Beaumont Hills": {'price': 100, "area_type": "north_west"},
        "Cherrybrook": {'price': 110, "area_type": "north_west"},
        "Kellyville": {'price': 110, "area_type": "north_west"},
        "Kellyville Ridge": {'price': 120, "area_type": "north_west"},
        "Rouse Hill": {'price': 150, "area_type": "north_west"},
        "North Kellyville": {'price': 130, "area_type": "north_west"},
        "Glenhaven": {'price': 110, "area_type": "north_west"},
        "Dural": {'price': 100, "area_type": "north_west"},
        "Kenthurst": {'price': 140, "area_type": "north_west"},
        "Galston": {'price': 130, "area_type": "north_west"},
        "Westleigh": {'price': 100, "area_type": "north_west"},
        "Winston Hills": {'price': 100, "area_type": "north_west"},
        "Glenwood": {'price': 120, "area_type": "north_west"},
        "Stanhope Gardens": {'price': 130, "area_type": "north_west"},
        "The Ponds": {'price': 140, "area_type": "north_west"},
        "Parklea": {'price': 110, "area_type": "north_west"},
        "Kings Langley": {'price': 110, "area_type": "north_west"},
        "Kings Park": {'price': 120, "area_type": "north_west"},
        "Lalor Park": {'price': 120, "area_type": "north_west"},
        "Seven Hills": {'price': 100, "area_type": "north_west"},
        "Epping": {'price': 80, "area_type": "north_west"},
        "North Epping": {'price': 90, "area_type": "north_west"},
        "Eastwood": {'price': 80, "area_type": "north_west"},
        "Marsfield": {'price': 80, "area_type": "north_west"},
        "Macquarie Park": {'price': 80, "area_type": "north_west"},
        "North Ryde": {'price': 80, "area_type": "north_west"},
        "Ryde": {'price': 80, "area_type": "north_west"},
        "West Ryde": {'price': 80, "area_type": "north_west"},
        "East Ryde": {'price': 70, "area_type": "north_west"},
        "Carlingford": {'price': 90, "area_type": "north_west"},
        "Cheltenham": {'price': 90, "area_type": "north_west"},
        "Denistone": {'price': 70, "area_type": "north_west"},
        "Denistone East": {'price': 80, "area_type": "north_west"},
        "Meadowbank": {'price': 80, "area_type": "north_west"},
        "Melrose Park": {'price': 80, "area_type": "north_west"},
        "Putney": {'price': 80, "area_type": "north_west"},
        "Gladesville": {'price': 60, "area_type": "north_west"},
        "Henley": {'price': 60, "area_type": "north_west"},
        "Huntleys Cove": {'price': 60, "area_type": "north_west"},
        "Huntleys Point": {'price': 60, "area_type": "north_west"},
        "Tennyson Point": {'price': 80, "area_type": "north_west"},

        # --- 6. OUTER WEST (Blacktown, Penrith & Hawkesbury) ---
        "Blacktown": {'price': 100, "area_type": "outer_west"},
        "Marayong": {'price': 140, "area_type": "outer_west"},
        "Quakers Hill": {'price': 140, "area_type": "outer_west"},
        "Doonside": {'price': 110, "area_type": "outer_west"},
        "Rooty Hill": {'price': 150, "area_type": "outer_west"},
        "Mt Druitt": {'price': 150, "area_type": "outer_west"},
        "St Marys": {'price': 150, "area_type": "outer_west"},
        "St Marys North": {'price': 160, "area_type": "outer_west"},
        "St Clair": {'price': 130, "area_type": "outer_west"},
        "Minchinbury": {'price': 160, "area_type": "outer_west"},
        "Plumpton": {'price': 150, "area_type": "outer_west"},
        "Oakhurst": {'price': 150, "area_type": "outer_west"},
        "Glendenning": {'price': 110, "area_type": "outer_west"},
        "Schofields": {'price': 150, "area_type": "outer_west"},
        "Marsden Park": {'price': 160, "area_type": "outer_west"},
        "Riverstone": {'price': 150, "area_type": "outer_west"},
        "Vineyard": {'price': 160, "area_type": "outer_west"},
        "Box Hill": {'price': 170, "area_type": "outer_west"},
        "Penrith": {'price': 190, "area_type": "outer_west"},
        "South Penrith": {'price': 190, "area_type": "outer_west"},
        "Emu Plains": {'price': 190, "area_type": "outer_west"},
        "Glenmore Park": {'price': 190, "area_type": "outer_west"},
        "Jamisontown": {'price': 190, "area_type": "outer_west"},
        "Jordan Springs": {'price': 180, "area_type": "outer_west"},
        "Cranebrook": {'price': 180, "area_type": "outer_west"},
        "Werrington": {'price': 160, "area_type": "outer_west"},
        "Werrington County": {'price': 160, "area_type": "outer_west"},
        "Windsor": {'price': 240, "area_type": "outer_west"},
        "South Windsor": {'price': 240, "area_type": "outer_west"},
        "Bligh Park": {'price': 170, "area_type": "outer_west"},
        "Richmond": {'price': 180, "area_type": "outer_west"},
        "North Richmond": {'price': 190, "area_type": "outer_west"},
        "Hebersham": {'price': 110, "area_type": "outer_west"},
        "Whalan": {'price': 160, "area_type": "outer_west"},
        "Bidwill": {'price': 160, "area_type": "outer_west"},
        "Blackett": {'price': 140, "area_type": "outer_west"},
        "Shalvey": {'price': 150, "area_type": "outer_west"},
        "Tregear": {'price': 130, "area_type": "outer_west"},
        "Willmot": {'price': 190, "area_type": "outer_west"},
        "Emerton": {'price': 150, "area_type": "outer_west"},
        "Lethbridge Park": {'price': 100, "area_type": "outer_west"},
        "Dharruk": {'price': 120, "area_type": "outer_west"},
        "Colebee": {'price': 130, "area_type": "outer_west"},
        "Dean Park": {'price': 120, "area_type": "outer_west"},
        "Hassall Grove": {'price': 130, "area_type": "outer_west"},
        "Huntingwood": {'price': 120, "area_type": "outer_west"},
        "Eastern Creek": {'price': 130, "area_type": "outer_west"},
        "Arndell Park": {'price': 120, "area_type": "outer_west"},
        "Prospect": {'price': 100, "area_type": "outer_west"},
        "Colyton": {'price': 140, "area_type": "outer_west"},
        "Oxley Park": {'price': 150, "area_type": "outer_west"},
        "Ropes Crossing": {'price': 160, "area_type": "outer_west"},
        "Cambridge Park": {'price': 170, "area_type": "outer_west"},
        "Cambridge Gardens": {'price': 170, "area_type": "outer_west"},
        "Kingswood": {'price': 170, "area_type": "outer_west"},
        "Caddens": {'price': 170, "area_type": "outer_west"},
        "Orchard Hills": {'price': 150, "area_type": "outer_west"},
        "Castlereagh": {'price': 150, "area_type": "outer_west"},
        "Londonderry": {'price': 180, "area_type": "outer_west"},
        "Oakville": {'price': 170, "area_type": "outer_west"},
        "Mulgrave": {'price': 160, "area_type": "outer_west"},
        "McGraths Hill": {'price': 160, "area_type": "outer_west"},
        "Pitt Town": {'price': 200, "area_type": "outer_west"},

        # --- 7. UPPER NORTH SHORE (Hornsby Area) ---
        "Hornsby": {'price': 100, "area_type": "upper_north_shore"},
        "Hornsby Heights": {'price': 110, "area_type": "upper_north_shore"},
        "Asquith": {'price': 60, "area_type": "upper_north_shore"},
        "Waitara": {'price': 100, "area_type": "upper_north_shore"},
        "Wahroonga": {'price': 100, "area_type": "upper_north_shore"},
        "North Wahroonga": {'price': 110, "area_type": "upper_north_shore"},
        "Warrawee": {'price': 100, "area_type": "upper_north_shore"},
        "Thornleigh": {'price': 100, "area_type": "upper_north_shore"},
        "Pennant Hills": {'price': 100, "area_type": "upper_north_shore"},
        "West Pennant Hills": {'price': 100, "area_type": "upper_north_shore"},
        "Beecroft": {'price': 100, "area_type": "upper_north_shore"},
        "Normanhurst": {'price': 100, "area_type": "upper_north_shore"},
        "Mount Colah": {'price': 120, "area_type": "upper_north_shore"},
        "Mount Kuring-gai": {'price': 120, "area_type": "upper_north_shore"},
        "Berowra": {'price': 130, "area_type": "upper_north_shore"},
        "Berowra Heights": {'price': 140, "area_type": "upper_north_shore"},
        "Berowra Waters": {'price': 150, "area_type": "upper_north_shore"},
        "Cowan": {'price': 150, "area_type": "upper_north_shore"},
        "Brooklyn": {'price': 160, "area_type": "upper_north_shore"},

        # --- 8. LOWER NORTH SHORE ---
        "Artarmon": {'price': 60, "area_type": "north_shore"},
        "Chatswood": {'price': 70, "area_type": "north_shore"},
        "Chatswood West": {'price': 80, "area_type": "north_shore"},
        "Willoughby": {'price': 70, "area_type": "north_shore"},
        "Willoughby East": {'price': 70, "area_type": "north_shore"},
        "North Willoughby": {'price': 70, "area_type": "north_shore"},
        "Lane Cove": {'price': 70, "area_type": "north_shore"},
        "Lane Cove North": {'price': 70, "area_type": "north_shore"},
        "Lane Cove West": {'price': 70, "area_type": "north_shore"},
        "Linley Point": {'price': 60, "area_type": "north_shore"},
        "Longueville": {'price': 80, "area_type": "north_shore"},
        "Northwood": {'price': 70, "area_type": "north_shore"},
        "Riverview": {'price': 70, "area_type": "north_shore"},
        "St Leonards": {'price': 60, "area_type": "north_shore"},
        "Crows Nest": {'price': 60, "area_type": "north_shore"},
        "Naremburn": {'price': 70, "area_type": "north_shore"},
        "Wollstonecraft": {'price': 70, "area_type": "north_shore"},
        "Greenwich": {'price': 60, "area_type": "north_shore"},
        "Neutral Bay": {'price': 70, "area_type": "north_shore"},
        "North Sydney": {'price': 70, "area_type": "north_shore"},
        "Kirribilli": {'price': 60, "area_type": "north_shore"},
        "McMahons Point": {'price': 70, "area_type": "north_shore"},
        "Lavender Bay": {'price': 70, "area_type": "north_shore"},
        "Waverton": {'price': 70, "area_type": "north_shore"},
        "Kurraba Point": {'price': 70, "area_type": "north_shore"},
        "Cremorne": {'price': 60, "area_type": "north_shore"},
        "Cremorne Point": {'price': 70, "area_type": "north_shore"},
        "Mosman": {'price': 80, "area_type": "north_shore"},
        "Beauty Point": {'price': 90, "area_type": "north_shore"},
        "Castle Cove": {'price': 70, "area_type": "north_shore"},
        "Castlecrag": {'price': 70, "area_type": "north_shore"},
        "Middle Cove": {'price': 70, "area_type": "north_shore"},
        "Northbridge": {'price': 70, "area_type": "north_shore"},
        "Cammeray": {'price': 70, "area_type": "north_shore"},
        "Gordon": {'price': 80, "area_type": "north_shore"},
        "Killara": {'price': 80, "area_type": "north_shore"},
        "East Killara": {'price': 80, "area_type": "north_shore"},
        "Lindfield": {'price': 70, "area_type": "north_shore"},
        "East Lindfield": {'price': 70, "area_type": "north_shore"},
        "Pymble": {'price': 90, "area_type": "north_shore"},
        "West Pymble": {'price': 90, "area_type": "north_shore"},
        "Turramurra": {'price': 100, "area_type": "north_shore"},
        "North Turramurra": {'price': 100, "area_type": "north_shore"},
        "South Turramurra": {'price': 100, "area_type": "north_shore"},
        "St Ives": {'price': 90, "area_type": "north_shore"},
        "St Ives Chase": {'price': 100, "area_type": "north_shore"},
        "Roseville": {'price': 80, "area_type": "north_shore"},
        "Roseville Chase": {'price': 80, "area_type": "north_shore"},

        # --- 9. NORTHERN BEACHES ---
        "Manly": {'price': 90, "area_type": "northern_beaches"},
        "North Manly": {'price': 90, "area_type": "northern_beaches"},
        "Manly Vale": {'price': 90, "area_type": "northern_beaches"},
        "Dee Why": {'price': 80, "area_type": "northern_beaches"},
        "Brookvale": {'price': 100, "area_type": "northern_beaches"},
        "Balgowlah": {'price': 80, "area_type": "northern_beaches"},
        "Balgowlah Heights": {'price': 80, "area_type": "northern_beaches"},
        "North Balgowlah": {'price': 90, "area_type": "northern_beaches"},
        "Freshwater": {'price': 100, "area_type": "northern_beaches"},
        "Fairlight": {'price': 70, "area_type": "northern_beaches"},
        "Narraweena": {'price': 110, "area_type": "northern_beaches"},
        "Seaforth": {'price': 90, "area_type": "northern_beaches"},
        "Curl Curl": {'price': 100, "area_type": "northern_beaches"},
        "North Curl Curl": {'price': 110, "area_type": "northern_beaches"},
        "Allambie Heights": {'price': 90, "area_type": "northern_beaches"},
        "Beacon Hill": {'price': 100, "area_type": "northern_beaches"},
        "Frenchs Forest": {'price': 90, "area_type": "northern_beaches"},
        "Forestville": {'price': 80, "area_type": "northern_beaches"},
        "Killarney Heights": {'price': 80, "area_type": "northern_beaches"},
        "Belrose": {'price': 100, "area_type": "northern_beaches"},
        "Davidson": {'price': 100, "area_type": "northern_beaches"},
        "Terrey Hills": {'price': 110, "area_type": "northern_beaches"},
        "Cromer": {'price': 100, "area_type": "northern_beaches"},
        "Wheeler Heights": {'price': 100, "area_type": "northern_beaches"},
        "Collaroy": {'price': 110, "area_type": "northern_beaches"},
        "Collaroy Plateau": {'price': 110, "area_type": "northern_beaches"},
        "Narrabeen": {'price': 120, "area_type": "northern_beaches"},
        "Warriewood": {'price': 120, "area_type": "northern_beaches"},
        "Mona Vale": {'price': 130, "area_type": "northern_beaches"},
        "Ingleside": {'price': 140, "area_type": "northern_beaches"},
        "Elanora Heights": {'price': 100, "area_type": "northern_beaches"},

        # --- 10. EASTERN SUBURBS ---
        "Bondi": {'price': 80, "area_type": "eastern_suburbs"},
        "Bondi Junction": {'price': 60, "area_type": "eastern_suburbs"},
        "Bondi Beach": {'price': 80, "area_type": "eastern_suburbs"},
        "North Bondi": {'price': 70, "area_type": "eastern_suburbs"},
        "Coogee": {'price': 60, "area_type": "eastern_suburbs"},
        "South Coogee": {'price': 70, "area_type": "eastern_suburbs"},
        "Bellevue Hill": {'price': 60, "area_type": "eastern_suburbs"},
        "Bronte": {'price': 60, "area_type": "eastern_suburbs"},
        "Woollahra": {'price': 60, "area_type": "eastern_suburbs"},
        "Watsons Bay": {'price': 80, "area_type": "eastern_suburbs"},
        "Vaucluse": {'price': 80, "area_type": "eastern_suburbs"},
        "Rose Bay": {'price': 70, "area_type": "eastern_suburbs"},
        "Double Bay": {'price': 60, "area_type": "eastern_suburbs"},
        "Point Piper": {'price': 70, "area_type": "eastern_suburbs"},
        "Edgecliff": {'price': 60, "area_type": "eastern_suburbs"},
        "Randwick": {'price': 60, "area_type": "eastern_suburbs"},
        "Randwick North": {'price': 60, "area_type": "eastern_suburbs"},
        "Randwick West": {'price': 60, "area_type": "eastern_suburbs"},
        "Clovelly": {'price': 70, "area_type": "eastern_suburbs"},
        "Waverley": {'price': 70, "area_type": "eastern_suburbs"},
        "Tamarama": {'price': 70, "area_type": "eastern_suburbs"},
        "Queens Park": {'price': 60, "area_type": "eastern_suburbs"},
        "Kingsford": {'price': 70, "area_type": "eastern_suburbs"},
        "Kensington": {'price': 70, "area_type": "eastern_suburbs"},
        "Maroubra": {'price': 80, "area_type": "eastern_suburbs"},
        "Maroubra Junction": {'price': 80, "area_type": "eastern_suburbs"},
        "Matraville": {'price': 90, "area_type": "eastern_suburbs"},
        "Malabar": {'price': 90, "area_type": "eastern_suburbs"},
        "Chifley": {'price': 90, "area_type": "eastern_suburbs"},
        "Little Bay": {'price': 100, "area_type": "eastern_suburbs"},
        "La Perouse": {'price': 100, "area_type": "eastern_suburbs"},
        "Botany": {'price': 70, "area_type": "eastern_suburbs"},
        "Banksmeadow": {'price': 80, "area_type": "eastern_suburbs"},
        "Pagewood": {'price': 70, "area_type": "eastern_suburbs"},
        "Eastgardens": {'price': 70, "area_type": "eastern_suburbs"},
        "Hillsdale": {'price': 70, "area_type": "eastern_suburbs"},
        "Eastlakes": {'price': 60, "area_type": "eastern_suburbs"},
        "Rosebery": {'price': 60, "area_type": "eastern_suburbs"},
        "Mascot": {'price': 70, "area_type": "eastern_suburbs"},
        "Waterloo": {'price': 60, "area_type": "eastern_suburbs"},
        "Zetland": {'price': 60, "area_type": "eastern_suburbs"},
        "Alexandria": {'price': 60, "area_type": "eastern_suburbs"},
        "Beaconsfield": {'price': 60, "area_type": "eastern_suburbs"},
        "Redfern": {'price': 50, "area_type": "eastern_suburbs"},
        "Eveleigh": {'price': 50, "area_type": "eastern_suburbs"},
        "Chippendale": {'price': 50, "area_type": "eastern_suburbs"},
    }
    return more_suburbs
