def get_home_suburbs(): 
    home_suburbs = [
        # --- 1. SYDNEY CITY & CBD ---
        "Sydney City",
        "Sydney CBD",
        "Hotels In City",
        "Sydney Intl Airport",
        "Sydney Domestic Airport",
        "White Bay Cruise Terminal",
        "Overseas Passenger Terminal",
        "Darlinghurst",
        "Darling Point",
        "Pyrmont",
        "Surry Hills",
        "Ultimo",
        "Barangaroo",
        "Millers Point",
        "Milsons Point",
        "Potts Point",
        "The Rocks",
        "Paddington",
        "Woolloomooloo",
        "Haymarket",
        "Glebe",

        # --- 2. INNER WEST ---
        "Ashfield",
        "Balmain",
        "Birchgrove",
        "Breakfast Point",
        "Cabarita",
        "Camperdown",
        "Canada Bay",
        "Chiswick",
        "Concord",
        "Concord West",
        "Drummoyne",
        "Dulwich Hill",
        "Enmore",
        "Five Dock",
        "Haberfield",
        "Leichhardt",
        "Lilyfield",
        "Marrickville",
        "Newtown",
        "Petersham",
        "Rhodes",
        "Rozelle",
        "Russell Lea",
        "Stanmore",
        "Summer Hill",
        "Wareemba",
        "Liberty Grove",

        # --- 3. CENTRAL WEST (Parramatta & Surrounds) ---
        "Parramatta",
        "North Parramatta",
        "Westmead",
        "Northmead",
        "Granville",
        "Harris Park",
        "Merrylands",
        "Merrylands West",
        "Wentworthville",
        "South Wentworthville",
        "Toongabbie",
        "Old Toongabbie",
        "Pendle Hill",
        "Greystanes",
        "Pemulwuy",
        "Clyde",
        "Rosehill",
        "Rydalmere",
        "Ermington",
        "Dundas",
        "Dundas Valley",
        "Telopea",
        "Silverwater",
        "Newington",
        "Olympic Park",
        "Constitution Hill",
        "Girraween",
        "Oatlands",
        "Camellia",

        # --- 4. WEST (Canterbury-Bankstown & South West) ---
        "Auburn",
        "Bankstown",
        "Bass Hill",
        "Berala",
        "Beverly Hills",
        "Beverly Park",
        "Bexley",
        "Bexley North",
        "Birrong",
        "Chester Hill",
        "Chullora",
        "Greenacre",
        "Guildford",
        "Guildford West",
        "Lidcombe",
        "Revesby",
        "Yagoona",
        "Panania",
        "Riverwood",
        "Sefton",
        "Punchbowl",
        "Belmore",
        "Belfield",
        "Lakemba",
        "Wiley Park",
        "Roselands",
        "Burwood",
        "Homebush",
        "Homebush West",
        "Strathfield",
        "North Strathfield",
        "Enfield",
        "Hurstville",
        "Mortdale",
        "Penshurst",
        "Peakhurst",
        "Padstow",
        "Condell Park",
        "Georges Hall",
        "Milperra",
        "Regents Park",
        "Potts Hill",
        "Villawood",
        "Lansdowne",
        "Old Guildford",

        # --- 5. NORTH WEST (Hills District & Ryde Area) ---
        "Castle Hill",
        "Baulkham Hills",
        "Bella Vista",
        "Beaumont Hills",
        "Cherrybrook",
        "Kellyville",
        "Kellyville Ridge",
        "Rouse Hill",
        "North Kellyville",
        "Glenhaven",
        "Dural",
        "Kenthurst",
        "Galston",
        "Westleigh",
        "Winston Hills",
        "Glenwood",
        "Stanhope Gardens",
        "The Ponds",
        "Parklea",
        "Kings Langley",
        "Kings Park",
        "Lalor Park",
        "Seven Hills",
        "Epping",
        "North Epping",
        "Eastwood",
        "Marsfield",
        "Macquarie Park",
        "North Ryde",
        "Ryde",
        "West Ryde",
        "East Ryde",
        "Carlingford",
        "Cheltenham",
        "Denistone",
        "Denistone East",
        "Meadowbank",
        "Melrose Park",
        "Putney",
        "Gladesville",
        "Henley",
        "Huntleys Cove",
        "Huntleys Point",
        "Tennyson Point",

        # --- 6. OUTER WEST (Blacktown, Penrith & Hawkesbury) ---
        "Blacktown",
        "Marayong",
        "Quakers Hill",
        "Doonside",
        "Rooty Hill",
        "Mt Druitt",
        "St Marys",
        "St Marys North",
        "St Clair",
        "Minchinbury",
        "Plumpton",
        "Oakhurst",
        "Glendenning",
        "Schofields",
        "Marsden Park",
        "Riverstone",
        "Vineyard",
        "Box Hill",
        "Penrith",
        "South Penrith",
        "Emu Plains",
        "Glenmore Park",
        "Jamisontown",
        "Jordan Springs",
        "Cranebrook",
        "Werrington",
        "Werrington County",
        "Windsor",
        "South Windsor",
        "Bligh Park",
        "Richmond",
        "North Richmond",
        "Hebersham",
        "Whalan",
        "Bidwill",
        "Blackett",
        "Shalvey",
        "Tregear",
        "Willmot",
        "Emerton",
        "Lethbridge Park",
        "Dharruk",
        "Colebee",
        "Dean Park",
        "Hassall Grove",
        "Huntingwood",
        "Eastern Creek",
        "Arndell Park",
        "Prospect",
        "Colyton",
        "Oxley Park",
        "Ropes Crossing",
        "Cambridge Park",
        "Cambridge Gardens",
        "Kingswood",
        "Caddens",
        "Orchard Hills",
        "Castlereagh",
        "Londonderry",
        "Oakville",
        "Mulgrave",
        "McGraths Hill",
        "Pitt Town",

        # --- 7. UPPER NORTH SHORE (Hornsby Area) ---
        "Hornsby",
        "Hornsby Heights",
        "Asquith",
        "Waitara",
        "Wahroonga",
        "North Wahroonga",
        "Warrawee",
        "Thornleigh",
        "Pennant Hills",
        "West Pennant Hills",
        "Beecroft",
        "Normanhurst",
        "Mount Colah",
        "Mount Kuring-gai",
        "Berowra",
        "Berowra Heights",
        "Berowra Waters",
        "Cowan",
        "Brooklyn",

        # --- 8. LOWER NORTH SHORE ---
        "Artarmon",
        "Chatswood",
        "Chatswood West",
        "Willoughby",
        "Willoughby East",
        "North Willoughby",
        "Lane Cove",
        "Lane Cove North",
        "Lane Cove West",
        "Linley Point",
        "Longueville",
        "Northwood",
        "Riverview",
        "St Leonards",
        "Crows Nest",
        "Naremburn",
        "Wollstonecraft",
        "Greenwich",
        "Neutral Bay",
        "North Sydney",
        "Kirribilli",
        "McMahons Point",
        "Lavender Bay",
        "Waverton",
        "Kurraba Point",
        "Cremorne",
        "Cremorne Point",
        "Mosman",
        "Beauty Point",
        "Castle Cove",
        "Castlecrag",
        "Middle Cove",
        "Northbridge",
        "Cammeray",
        "Gordon",
        "Killara",
        "East Killara",
        "Lindfield",
        "East Lindfield",
        "Pymble",
        "West Pymble",
        "Turramurra",
        "North Turramurra",
        "South Turramurra",
        "St Ives",
        "St Ives Chase",
        "Roseville",
        "Roseville Chase",

        # --- 9. NORTHERN BEACHES ---
        "Manly",
        "North Manly",
        "Manly Vale",
        "Dee Why",
        "Brookvale",
        "Balgowlah",
        "Balgowlah Heights",
        "North Balgowlah",
        "Freshwater",
        "Fairlight",
        "Narraweena",
        "Seaforth",
        "Curl Curl",
        "North Curl Curl",
        "Allambie Heights",
        "Beacon Hill",
        "Frenchs Forest",
        "Forestville",
        "Killarney Heights",
        "Belrose",
        "Davidson",
        "Terrey Hills",
        "Cromer",
        "Wheeler Heights",
        "Collaroy",
        "Collaroy Plateau",
        "Narrabeen",
        "Warriewood",
        "Mona Vale",
        "Ingleside",
        "Elanora Heights",

        # --- 10. EASTERN SUBURBS ---
        "Bondi",
        "Bondi Junction",
        "Bondi Beach",
        "North Bondi",
        "Coogee",
        "South Coogee",
        "Bellevue Hill",
        "Bronte",
        "Woollahra",
        "Watsons Bay",
        "Vaucluse",
        "Rose Bay",
        "Double Bay",
        "Point Piper",
        "Edgecliff",
        "Randwick",
        "Randwick North",
        "Randwick West",
        "Clovelly",
        "Waverley",
        "Tamarama",
        "Queens Park",
        "Kingsford",
        "Kensington",
        "Maroubra",
        "Maroubra Junction",
        "Matraville",
        "Malabar",
        "Chifley",
        "Little Bay",
        "La Perouse",
        "Botany",
        "Banksmeadow",
        "Pagewood",
        "Eastgardens",
        "Hillsdale",
        "Eastlakes",
        "Rosebery",
        "Mascot",
        "Waterloo",
        "Zetland",
        "Alexandria",
        "Beaconsfield",
        "Redfern",
        "Eveleigh",
        "Chippendale",
    ]    
    return home_suburbs

home_suburbs = get_home_suburbs() 
