from django.urls import path
from . import views
from .views import paypal_ipn, create_stripe_checkout_session
from django.shortcuts import redirect
from django.views.generic import RedirectView


app_name = "basecamp"

urlpatterns = [
    path('', views.home, name='home'),
    path('about_us/', views.about_us, name='about_us'),
    path('maxi-taxi/choose-suburb/', views.more_suburbs_maxi_taxi, name='more_suburbs_maxi_taxi'),
    path('maxi-taxi/<slug:suburb>/', views.maxi_taxi, name='maxi_taxi_suburb'),
    path('maxi-taxi/', views.maxi_taxi, name='maxi_taxi'),
    path('airport-shuttle-<slug:suburb>/', views.airport_shuttle, name='airport_shuttle_suburb'),  
    path('airport-transfer-<slug:suburb>/', views.airport_transfer, name='airport_transfer_suburb'),  
    path('airport-transfers-<slug:suburb>/', RedirectView.as_view(url='/sydney-airport-transfer/%(suburb)s/', permanent=True), name='old_airport_transfers_redirect'),
    path('sydney-airport-transfer/<slug:suburb>/', views.airport_transfer, name='sydney_airport_transfer_suburb'),    
    path('sydney-airport-shuttle/', views.sydney_airport_shuttle, name='sydney_airport_shuttle'),
    path('sydney-airport-transfer/', views.sydney_airport_transfer, name='sydney_airport_transfer'),
    path('sydney-cruise-transfer/', views.sydney_cruise_transfer, name='sydney_cruise_transfer'),
    path('arrival_guide/', views.arrival_guide, name='arrival_guide'),
    path('booking/', views.booking, name="booking"),
    path('booking_detail/', views.booking_detail, name="booking_detail"),
    path('confirmation/', views.confirmation, name="confirmation"),
    path('confirmation_detail/', views.confirmation_detail, name='confirmation_detail'),
    path('confirm_booking/', views.confirm_booking, name="confirm_booking"),
    path('confirm_booking_detail/', views.confirm_booking_detail, name='confirm_booking_detail'),
    path('create_stripe_checkout_session/', create_stripe_checkout_session, name='create_stripe_checkout_session'),
    path('cruise_booking/', views.cruise_booking, name="cruise_booking"),
    path('cruise_booking_detail/', views.cruise_booking_detail, name='cruise_booking_detail'),
    path('cruise_inquiry/', views.cruise_inquiry, name="cruise_inquiry"),
    path('error/', views.error, name='error'),
    path('email_dispatch/', views.email_dispatch, name='email_dispatch'),
    path('email_dispatch_detail/', views.email_dispatch_detail, name='email_dispatch_detail'),
    path('email_error_confirmbooking/', views.email_error_confirmbooking, name='email_error_confirmbooking'),
    path('home/', RedirectView.as_view(url='/', permanent=True)),
    path('home_error/', views.home_error, name='home_error'),
    path('information/', views.information, name='information'),
    path('invoice-6gv4vPYs/', views.invoice, name="invoice"),
    path('invoice_detail/', views.invoice_detail, name='invoice_detail'),
    path('inquiry/', views.inquiry, name="inquiry"),
    path('inquiry1/', views.inquiry1, name="inquiry1"),
    path('inquiry2/', views.inquiry2, name="inquiry2"),
    path('inquiry_details/', views.inquiry_details, name='inquiry_details'),
    path('inquiry_details1/', views.inquiry_details1, name='inquiry_details1'),
    path('inquiry_details2/', views.inquiry_details2, name='inquiry_details2'),
    path('inquiry_done/', views.inquiry_done, name='inquiry_done'),
    path('meeting_point/', views.meeting_point, name='meeting_point'),
    path('more_suburbs_maxi_taxi/', views.more_suburbs_maxi_taxi, name='more_suburbs_maxi_taxi'),
    path('more_suburbs/', views.more_suburbs, name='more_suburbs'),
    path('more_suburbs1/', views.more_suburbs1, name='more_suburbs1'),
    path('p2p/', views.p2p, name="p2p"),
    path('p2p_booking/', views.p2p_booking, name="p2p_booking"),
    path('p2p_booking_detail/', views.p2p_booking_detail, name="p2p_booking_detail"),
    path('p2p_detail/', views.p2p_detail, name='p2p_detail'),
    path('p2p_single/', views.p2p_single, name="p2p_single"),    
    path('payment_cancel/', views.payment_cancel, name='payment_cancel'),   
    path('payment_options/', views.payment_options, name='payment_options'),
    path('payment_options1/', views.payment_options1, name='payment_options1'),
    path('payonline/', views.payonline, name='payonline'),
    path('payonline_stripe/', views.payonline_stripe, name='payonline_stripe'),
    path('paypal_ipn/', paypal_ipn, name='paypal_ipn'),    
    path('price_detail/', views.price_detail, name='price_detail'),
    path('privacy/', views.privacy, name='privacy'),
    path('recaptcha-verify/', views.recaptcha_verify, name='recaptcha_verify'),
    path('return_cruise_fields/', views.return_cruise_fields, name='return_cruise_fields'),
    path('return_flight_fields/', views.return_flight_fields, name='return_flight_fields'),
    path('return_trip/', views.return_trip, name="return_trip"),
    path('return_trip_detail/', views.return_trip_detail, name="return_trip_detail"),
    path('sending_email_first/', views.sending_email_first, name="sending_email_first"),
    path('sending_email_first_detail/', views.sending_email_first_detail, name="sending_email_first_detail"),
    path('sending_email_second/', views.sending_email_second, name="sending_email_second"),
    path('sending_email_second_detail/', views.sending_email_second_detail, name="sending_email_second_detail"),
    path('sending_email_input_data/', views.sending_email_input_data, name="sending_email_input_data"),
    path('sending_email_input_data_detail/', views.sending_email_input_data_detail, name="sending_email_input_data_detail"),
    path('service/', views.service, name='service'),
    path('success/', views.success, name='success'),
    path('terms/', views.terms, name='terms'),
    path('wrong_date_today/', views.wrong_date_today, name='wrong_date_today'),
    path('pay/stripe/', lambda request: redirect('https://buy.stripe.com/7sIcP940RbKH7LO6ow'), name='pay_stripe'),

]


