from django.urls import path
from . import views
from .views import paypal_ipn, server_error
from basecamp.area import suburbs

app_name = "basecamp"

handler500 = server_error

urlpatterns = [
    path('', views.index),
    path('about_us/', views.about_us),
    path('airport-transfer-artarmon/', views.artarmon),
    path('airport-transfers-asquith/', views.asquith),
    path('airport-transfers-blacktown/', views.blacktown),
    path('airport-transfers-chatswood/', views.chatswood),
    path('airport-transfers-doonside/', views.doonside),
    path('airport-transfers-eastwood/', views.eastwood),
    path('airport-transfers-epping/', views.epping),
    path('airport-transfers-gordon/', views.gordon),
    path('airport-transfers-hornsby/', views.hornsby),
    path('airport-transfers-lane-cove/', views.lane_cove),
    path('airport-transfers-linfield/', views.linfield),
    path('airport-transfers-macquarie-park/', views.macquarie_park),
    path('airport-transfers-marsfield/', views.marsfield),
    path('airport-transfers-middle-cove/', views.middle_cove),
    path('airport-transfers-mini-bus/', views.mini_bus),
    path('airport-transfers-mount-kuring-gai/', views.mount_kuring_gai),
    path('airport-transfers-north-shore/', views.north_shore),
    path('airport-transfers-north-west/', views.north_west),
    path('airport-transfers-normanhurst/', views.normanhurst),
    path('airport-transfers-parramatta/', views.parramatta),
    path('airport-transfers-pennant-hills/', views.pennant_hills),
    path('airport-transfers-pymble/', views.pymble),
    path('airport-transfers-roseville/', views.roseville),
    path('airport-transfers-ryde/', views.ryde),
    path('airport-transfers-st-ives/', views.st_ives),
    path('airport-transfers-sydney-city/', views.sydney_city),
    path('airport-transfers-thornleigh/', views.thornleigh),
    path('airport-transfers-toongabbie/', views.toongabbie),
    path('airport-transfers-turramurra/', views.turramurra),
    path('airport-transfers-wahroonga/', views.wahroonga),
    path('airport-transfers-waitara/', views.waitara),
    path('airport-transfers-warrawee/', views.warrawee),
    path('airport-transfers-west-pymble/', views.west_pymble),
    path('airport-transfers-westleigh/', views.westleigh),
    path('airport-transfers-willoughby/', views.willoughby),
    path('booking/', views.booking, name="booking"),
    path('booking_detail/', views.booking_detail),
    path('booking_form/', views.booking_form, name="booking_form"),
    path('booking_form_detail/', views.booking_form_detail),
    path('confirmation/', views.confirmation, name="confirmation"),
    path('confirmation_detail/', views.confirmation_detail, name='confirmation_detail'),
    path('confirm_booking/', views.confirm_booking, name="confirm_booking"),
    path('confirm_booking_detail/', views.confirm_booking_detail),
    path('cruise_booking/', views.cruise_booking, name="cruise_booking"),
    path('cruise_booking_detail/', views.cruise_booking_detail),
    path('cruise_date_error/', views.cruise_date_error, name='cruise_date_error'),
    path('cruise_inquiry/', views.cruise_inquiry, name="cruise_inquiry"),
    path('cruise_inquiry_detail/', views.cruise_inquiry_detail),
    path('cruise_inquiry_detail_1/', views.cruise_inquiry_detail_1),
    path('cruise_inquiry_1/', views.cruise_inquiry_1, name="cruise_inquiry_1"),
    path('date_error/', views.date_error, name='date_error'),
    path('flight_date_detail/', views.flight_date_detail),
    path('flight_date_error/', views.flight_date_error, name='flight_date_error'),
    path('home/', views.home, name='home'),
    path('information/', views.information),
    path('invoice/', views.invoice, name="invoice"),
    path('invoice_detail/', views.invoice_detail),
    path('inquiry/', views.inquiry, name="inquiry"),
    path('inquiry1/', views.inquiry1, name="inquiry1"),
    path('inquiry2/', views.inquiry2, name="inquiry2"),
    path('inquiry_details/', views.inquiry_details),
    path('inquiry_details1/', views.inquiry_details1),
    path('inquiry_details2/', views.inquiry_details2),
    path('inquiry_done/', views.inquiry_done, name='inquiry_done'),
    path('meeting_point/', views.meeting_point),
    path('p2p/', views.p2p, name="p2p"),
    path('p2p_detail/', views.p2p_detail),
    path('p2p_single/', views.p2p_single, name="p2p_single"),
    path('p2p_single_detail/', views.p2p_single_detail),
    path('payonline/', views.payonline, name='payonline'),
    path('paypal_ipn/', paypal_ipn, name='paypal_ipn'),
    path('paypal_notice/', views.paypal_notice, name='paypal_notice'),
    path('pickup_adjustment/', views.pickup_adjustment, name='pickup_adjustment'),
    path('pickup_adjustment_detail/', views.pickup_adjustment_detail),
    path('price_detail/', views.price_detail),
    path('return_cruise_fields/', views.return_cruise_fields, name='return_cruise_fields'),
    path('return_flight_fields/', views.return_flight_fields, name='return_flight_fields'),
    path('return_trip/', views.return_trip, name="return_trip"),
    path('return_trip_detail/', views.return_trip_detail),
    path('save_data_only/', views.save_data_only, name="save_data_only"),
    path('save_data_only_detail/', views.save_data_only_detail),
    path('sending_email_first/', views.sending_email_first, name="sending_email_first"),
    path('sending_email_first_detail/', views.sending_email_first_detail),
    path('sending_email_second/', views.sending_email_second, name="sending_email_second"),
    path('sending_email_second_detail/', views.sending_email_second_detail),
    path('sending_email_input_data/', views.sending_email_input_data),
    path('sending_email_input_data_detail/', views.sending_email_input_data_detail),
    path('sitemap/', views.sitemap),
    path('soyoung/', views.soyoung),
    path('terms/', views.terms),
    path('yoosung/', views.yoosung),
]
