from django.urls import path
from . import views
from .views import paypal_ipn, create_stripe_checkout_session, server_error

app_name = "basecamp"

handler500 = server_error

urlpatterns = [
    path('', views.index, name='index'),
    path('about_us/', views.about_us, name='about_us'),
    path('airport-shuttle-<str:suburb>/', views.airport_shuttle, name='airport_shuttle'),
    path('airport-transfers-<str:suburb>/', views.airport_transfers, name='airport_transfers'),
    path('booking/', views.booking, name="booking"),
    path('booking_detail/', views.booking_detail, name="booking_detail"),
    path('cancel/', views.cancel, name="cancel"), 
    path('confirmation/', views.confirmation, name="confirmation"),
    path('confirmation_detail/', views.confirmation_detail, name='confirmation_detail'),
    path('confirmation_multiplebookings/', views.confirmation_multiplebookings, name='confirmation_multiplebookings'),
    path('confirm_booking/', views.confirm_booking, name="confirm_booking"),
    path('confirm_booking_detail/', views.confirm_booking_detail, name='confirm_booking_detail'),
    path('create_stripe_checkout_session/', create_stripe_checkout_session, name='create_stripe_checkout_session'),
    path('cruise_booking/', views.cruise_booking, name="cruise_booking"),
    path('cruise_booking_detail/', views.cruise_booking_detail, name='cruise_booking_detail'),
    path('cruise_inquiry/', views.cruise_inquiry, name="cruise_inquiry"),
    path('date_error/', views.date_error, name='date_error'),
    path('error/', views.error, name='error'),
    path('email_dispatch/', views.email_dispatch, name='email_dispatch'),
    path('email_dispatch_detail/', views.email_dispatch_detail, name='email_dispatch_detail'),
    path('flight_date_detail/', views.flight_date_detail, name='flight_date_detail'),
    path('flight_date_error/', views.flight_date_error, name='flight_date_error'),
    path('home/', views.home, name='home'),
    path('information/', views.information, name='information'),
    path('invoice/', views.invoice, name="invoice"),
    path('invoice_detail/', views.invoice_detail, name='invoice_detail'),
    path('inquiry/', views.inquiry, name="inquiry"),
    path('inquiry1/', views.inquiry1, name="inquiry1"),
    path('inquiry2/', views.inquiry2, name="inquiry2"),
    path('inquiry_details/', views.inquiry_details, name='inquiry_details'),
    path('inquiry_details1/', views.inquiry_details1, name='inquiry_details1'),
    path('inquiry_details2/', views.inquiry_details2, name='inquiry_details2'),
    path('inquiry_done/', views.inquiry_done, name='inquiry_done'),
    path('meeting_point/', views.meeting_point, name='meeting_point'),
    path('more_suburbs/', views.more_suburbs, name='more_suburbs'),
    path('more_suburbs1/', views.more_suburbs1, name='more_suburbs1'),
    path('p2p/', views.p2p, name="p2p"),
    path('p2p_booking/', views.p2p_booking, name="p2p_booking"),
    path('p2p_booking_detail/', views.p2p_booking_detail, name="p2p_booking_detail"),
    path('p2p_detail/', views.p2p_detail, name='p2p_detail'),
    path('p2p_single/', views.p2p_single, name="p2p_single"),    
    path('payment_cancel/', views.payment_cancel, name='payment_cancel'),   
    path('payment_options/', views.payment_options, name='payment_options'),
    path('payonline/', views.payonline, name='payonline'),
    path('payonline_stripe/', views.payonline_stripe, name='payonline_stripe'),
    path('paypal_ipn/', paypal_ipn, name='paypal_ipn'),    
    path('price_detail/', views.price_detail, name='price_detail'),
    path('privacy/', views.privacy, name='privacy'),
    path('return_cruise_fields/', views.return_cruise_fields, name='return_cruise_fields'),
    path('return_flight_fields/', views.return_flight_fields, name='return_flight_fields'),
    path('return_trip/', views.return_trip, name="return_trip"),
    path('return_trip_detail/', views.return_trip_detail, name="return_trip_detail"),
    path('save_data_only/', views.save_data_only, name="save_data_only"),
    path('save_data_only_detail/', views.save_data_only_detail, name="save_data_only_detail"),
    path('sending_email_first/', views.sending_email_first, name="sending_email_first"),
    path('sending_email_first_detail/', views.sending_email_first_detail, name="sending_email_first_detail"),
    path('sending_email_second/', views.sending_email_second, name="sending_email_second"),
    path('sending_email_second_detail/', views.sending_email_second_detail, name="sending_email_second_detail"),
    path('sending_email_input_data/', views.sending_email_input_data, name="sending_email_input_data"),
    path('sending_email_input_data_detail/', views.sending_email_input_data_detail, name="sending_email_input_data_detail"),
    path('service/', views.service, name='service'),
    path('sitemap/', views.sitemap, name='sitemap'),
    path('success/', views.success, name='success'),
    path('terms/', views.terms, name='terms'),
]
