# Generated by Django 5.2.4 on 2026-02-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easygo_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(default='https://g.page/r/CaNU_31hewLaEAI/review', max_length=100),
        ),
    ]
