# Generated by Django 5.2.12 on 2026-03-24 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Categories')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Tag')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Post')),
                ('slug', models.SlugField(allow_unicode=True, help_text='Used in URL. Auto-generated from title if left blank.', max_length=220, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary displayed on list pages (300 characters max)', max_length=300, verbose_name='Excerpt')),
                ('content', models.TextField(verbose_name='Content (HTML)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='articles/thumbnails/%Y/%m/', verbose_name='Thumbnail')),
                ('meta_title', models.CharField(blank=True, help_text='Overrides title in search results (max 70 chars).', max_length=70, verbose_name='SEO Post')),
                ('meta_description', models.CharField(blank=True, help_text='Displayed in Google search results (max 160 chars).', max_length=160, verbose_name='SEO Description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Status')),
                ('is_featured', models.BooleanField(default=False, help_text='Pin this post at the top of the blog listing.', verbose_name='Featured Post')),
                ('posted_to_google', models.BooleanField(default=False, verbose_name='Posted to Google Business')),
                ('posted_to_facebook', models.BooleanField(default=False, verbose_name='Posted to Facebook')),
                ('posted_to_instagram', models.BooleanField(default=False, verbose_name='Posted to Instagram')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='articles.category', verbose_name='Category')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='articles.tag', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
