# Generated by Django 5.2.12 on 2026-04-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail_query',
            field=models.CharField(blank=True, help_text='Search keyword for Unsplash', max_length=100, verbose_name='Thumbnail Query'),
        ),
    ]
