# Generated by Django 5.2.4 on 2026-04-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_post_thumbnail_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gmb_content',
            field=models.TextField(blank=True, help_text='비워두면 AI가 자동으로 1500자 이내로 요약합니다.', max_length=1500, null=True, verbose_name='GMB content'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_source_url',
            field=models.URLField(blank=True, help_text='Original Unsplash image URL for GMB posting.', max_length=500, verbose_name='Thumbnail Source URL'),
        ),
    ]
