# Generated by Django 5.2.13 on 2026-04-27 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_increase_meta_description_max_length'),
        ('regions', '0008_region_add_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='regions.region', verbose_name='Region'),
        ),
    ]
