"""
Sydney suburb price comparison: current vs $3/km from SYD (Kingsford Smith, Mascot).
Minimum $60, rounded to nearest $5.
Run from the easygo project root.
"""

# Driving distances (km) from Sydney Airport (Mascot NSW 2020)
# Estimated via road routes — used to calculate new shuttle prices.

DISTANCES = {
    # ── Eastern Suburbs ──────────────────────────────────────────────────
    "Alexandria": 5,
    "Banksmeadow": 5,
    "Beaconsfield": 5,
    "Bellevue Hill": 10,
    "Bondi": 12,
    "Bondi Beach": 12,
    "Bondi Junction": 9,
    "Botany": 4,
    "Bronte": 11,
    "Chifley": 13,
    "Chippendale": 6,
    "Clovelly": 11,
    "Coogee": 9,
    "Double Bay": 9,
    "Eastgardens": 7,
    "Eastlakes": 5,
    "Edgecliff": 9,
    "Eveleigh": 5,
    "Hillsdale": 9,
    "Kensington": 6,
    "Kingsford": 7,
    "La Perouse": 19,
    "Little Bay": 15,
    "Malabar": 13,
    "Maroubra": 11,
    "Maroubra Junction": 11,
    "Mascot": 3,
    "Matraville": 10,
    "North Bondi": 12,
    "Pagewood": 7,
    "Point Piper": 9,
    "Queens Park": 8,
    "Randwick": 7,
    "Randwick North": 7,
    "Randwick West": 7,
    "Redfern": 6,
    "Rosebery": 5,
    "Rose Bay": 10,
    "South Coogee": 10,
    "Tamarama": 11,
    "Vaucluse": 14,
    "Waterloo": 5,
    "Watsons Bay": 16,
    "Waverley": 9,
    "Woollahra": 8,
    "Zetland": 5,

    # ── Sydney City ───────────────────────────────────────────────────────
    "Barangaroo": 9,
    "Darling Point": 9,
    "Darlinghurst": 6,
    "Glebe": 8,
    "Haymarket": 5,
    "Hotels In City": 7,
    "Millers Point": 8,
    "Milsons Point": 10,
    "Paddington": 8,
    "Potts Point": 7,
    "Pyrmont": 8,
    "Surry Hills": 6,
    "Sydney CBD": 7,
    "Sydney City": 7,
    "The Rocks": 8,
    "Ultimo": 8,
    "Woolloomooloo": 7,

    # ── Inner West ────────────────────────────────────────────────────────
    "Ashfield": 12,
    "Balmain": 11,
    "Birchgrove": 12,
    "Breakfast Point": 15,
    "Cabarita": 15,
    "Camperdown": 8,
    "Canada Bay": 13,
    "Chiswick": 14,
    "Concord": 15,
    "Concord West": 16,
    "Drummoyne": 12,
    "Dulwich Hill": 9,
    "Enmore": 7,
    "Five Dock": 13,
    "Forest Lodge": 8,
    "Haberfield": 11,
    "Leichhardt": 10,
    "Liberty Grove": 14,
    "Lilyfield": 10,
    "Marrickville": 9,
    "Newtown": 8,
    "Petersham": 9,
    "Rhodes": 17,
    "Rozelle": 10,
    "Russell Lea": 13,
    "Stanmore": 9,
    "Summer Hill": 11,
    "Wareemba": 14,

    # ── North Shore ───────────────────────────────────────────────────────
    "Artarmon": 14,
    "Beauty Point": 15,
    "Cammeray": 12,
    "Castle Cove": 16,
    "Castlecrag": 14,
    "Chatswood": 14,
    "Chatswood West": 15,
    "Cremorne": 11,
    "Cremorne Point": 12,
    "Crows Nest": 10,
    "East Killara": 20,
    "East Lindfield": 18,
    "Gordon": 22,
    "Greenwich": 14,
    "Killara": 19,
    "Kirribilli": 9,
    "Kurraba Point": 10,
    "Lane Cove": 15,
    "Lane Cove North": 16,
    "Lane Cove West": 15,
    "Lavender Bay": 9,
    "Lindfield": 18,
    "Linley Point": 16,
    "Longueville": 16,
    "McMahons Point": 9,
    "Middle Cove": 16,
    "Mosman": 13,
    "Naremburn": 12,
    "Neutral Bay": 10,
    "North Sydney": 10,
    "North Turramurra": 26,
    "North Willoughby": 13,
    "Northbridge": 13,
    "Northwood": 14,
    "Pymble": 23,
    "Riverview": 15,
    "Roseville": 18,
    "Roseville Chase": 19,
    "South Turramurra": 24,
    "St Ives": 28,
    "St Ives Chase": 28,
    "St Leonards": 11,
    "Turramurra": 24,
    "Waverton": 10,
    "West Pymble": 22,
    "Willoughby": 13,
    "Willoughby East": 13,
    "Wollstonecraft": 10,

    # ── Upper North Shore ─────────────────────────────────────────────────
    "Asquith": 33,
    "Beecroft": 27,
    "Berowra": 48,
    "Berowra Heights": 50,
    "Berowra Waters": 53,
    "Brooklyn": 57,
    "Cowan": 56,
    "Hornsby": 32,
    "Hornsby Heights": 33,
    "Mount Colah": 37,
    "Mount Kuring-gai": 39,
    "Normanhurst": 28,
    "North Wahroonga": 27,
    "Pennant Hills": 28,
    "Thornleigh": 30,
    "Wahroonga": 26,
    "Waitara": 31,
    "Warrawee": 28,
    "West Pennant Hills": 30,

    # ── Northern Beaches ──────────────────────────────────────────────────
    "Allambie Heights": 22,
    "Balgowlah": 18,
    "Balgowlah Heights": 18,
    "Beacon Hill": 24,
    "Belrose": 26,
    "Brookvale": 23,
    "Collaroy": 28,
    "Collaroy Plateau": 28,
    "Cromer": 26,
    "Curl Curl": 24,
    "Davidson": 25,
    "Dee Why": 24,
    "Elanora Heights": 29,
    "Fairlight": 18,
    "Forestville": 22,
    "Frenchs Forest": 23,
    "Freshwater": 22,
    "Ingleside": 36,
    "Killarney Heights": 22,
    "Manly": 18,
    "Manly Vale": 20,
    "Mona Vale": 36,
    "Narrabeen": 32,
    "Narraweena": 27,
    "North Balgowlah": 19,
    "North Curl Curl": 25,
    "North Manly": 20,
    "Seaforth": 18,
    "Terrey Hills": 29,
    "Warriewood": 35,
    "Wheeler Heights": 27,

    # ── North West ────────────────────────────────────────────────────────
    "Cheltenham": 28,
    "Eastwood": 20,
    "Baulkham Hills": 30,
    "Beaumont Hills": 34,
    "Bella Vista": 33,
    "Carlingford": 22,
    "Castle Hill": 30,
    "Cherrybrook": 30,
    "Denistone": 18,
    "Denistone East": 18,
    "Dural": 34,
    "East Ryde": 16,
    "Epping": 20,
    "Galston": 38,
    "Gladesville": 13,
    "Glenhaven": 34,
    "Glenwood": 34,
    "Henley": 14,
    "Huntleys Cove": 14,
    "Huntleys Point": 14,
    "Kellyville": 36,
    "Kellyville Ridge": 37,
    "Kenthurst": 42,
    "Kings Langley": 32,
    "Kings Park": 34,
    "Lalor Park": 29,
    "Macquarie Park": 18,
    "Marsfield": 18,
    "Meadowbank": 18,
    "Melrose Park": 17,
    "North Epping": 25,
    "North Kellyville": 39,
    "North Ryde": 17,
    "Parklea": 35,
    "Putney": 16,
    "Rouse Hill": 42,
    "Ryde": 17,
    "Seven Hills": 28,
    "Stanhope Gardens": 39,
    "Tennyson Point": 16,
    "The Ponds": 40,
    "West Ryde": 17,
    "Westleigh": 31,
    "Winston Hills": 30,

    # ── Central West ──────────────────────────────────────────────────────
    "Camellia": 18,
    "Clyde": 18,
    "Constitution Hill": 24,
    "Dundas": 21,
    "Dundas Valley": 21,
    "Ermington": 20,
    "Girraween": 27,
    "Granville": 19,
    "Greystanes": 26,
    "Harris Park": 20,
    "Merrylands": 24,
    "Merrylands West": 24,
    "Newington": 17,
    "North Parramatta": 22,
    "Northmead": 25,
    "Oatlands": 24,
    "Old Toongabbie": 26,
    "Olympic Park": 15,
    "Parramatta": 22,
    "Pemulwuy": 27,
    "Pendle Hill": 26,
    "Rosehill": 21,
    "Rydalmere": 20,
    "Silverwater": 17,
    "South Wentworthville": 25,
    "Telopea": 22,
    "Toongabbie": 26,
    "Wentworthville": 25,
    "Westmead": 22,

    # ── West ─────────────────────────────────────────────────────────────
    "Auburn": 18,
    "Bankstown": 17,
    "Bass Hill": 21,
    "Belfield": 15,
    "Belmore": 16,
    "Berala": 19,
    "Beverly Hills": 17,
    "Beverly Park": 16,
    "Bexley": 13,
    "Bexley North": 15,
    "Birrong": 20,
    "Burwood": 12,
    "Chester Hill": 21,
    "Chullora": 17,
    "Condell Park": 19,
    "Enfield": 12,
    "Georges Hall": 19,
    "Greenacre": 16,
    "Guildford": 23,
    "Guildford West": 24,
    "Homebush": 14,
    "Homebush West": 14,
    "Hurstville": 13,
    "Lakemba": 16,
    "Lansdowne": 19,
    "Lidcombe": 17,
    "Milperra": 19,
    "Mortdale": 17,
    "North Strathfield": 14,
    "Old Guildford": 23,
    "Padstow": 21,
    "Panania": 22,
    "Peakhurst": 17,
    "Penshurst": 16,
    "Potts Hill": 19,
    "Punchbowl": 17,
    "Regents Park": 19,
    "Revesby": 21,
    "Riverwood": 18,
    "Roselands": 15,
    "Sefton": 21,
    "Strathfield": 14,
    "Villawood": 25,
    "Wiley Park": 16,
    "Yagoona": 19,

    # ── Outer West ────────────────────────────────────────────────────────
    "Quakers Hill": 38,
    "Arndell Park": 46,
    "Bidwill": 53,
    "Blackett": 46,
    "Blacktown": 33,
    "Bligh Park": 58,
    "Box Hill": 57,
    "Caddens": 54,
    "Cambridge Gardens": 58,
    "Cambridge Park": 57,
    "Castlereagh": 55,
    "Colebee": 44,
    "Colyton": 47,
    "Cranebrook": 60,
    "Dean Park": 39,
    "Dharruk": 41,
    "Doonside": 37,
    "Eastern Creek": 42,
    "Emerton": 50,
    "Emu Plains": 66,
    "Glendenning": 38,
    "Glenmore Park": 64,
    "Glenorie": 47,
    "Hassall Grove": 43,
    "Hebersham": 41,
    "Huntingwood": 39,
    "Jamisontown": 64,
    "Jordan Springs": 57,
    "Kingswood": 59,
    "Lethbridge Park": 33,
    "Londonderry": 59,
    "Marayong": 34,
    "Marsden Park": 52,
    "McGraths Hill": 56,
    "Minchinbury": 43,
    "Mt Druitt": 50,
    "Mulgrave": 57,
    "North Richmond": 67,
    "Oakhurst": 50,
    "Oakville": 58,
    "Orchard Hills": 52,
    "Oxley Park": 50,
    "Penrith": 65,
    "Pitt Town": 66,
    "Plumpton": 47,
    "Prospect": 35,
    "Richmond": 62,
    "Riverstone": 52,
    "Ropes Crossing": 57,
    "Rooty Hill": 40,
    "St Clair": 44,
    "St Marys": 49,
    "St Marys North": 50,
    "Schofields": 50,
    "Shalvey": 48,
    "South Penrith": 65,
    "South Windsor": 68,
    "Tregear": 46,
    "Vineyard": 58,
    "Werrington": 56,
    "Werrington County": 56,
    "Whalan": 50,
    "Willmot": 54,
    "Windsor": 62,
}


def new_price(km):
    raw = km * 3
    minimum = 60
    raw = max(raw, minimum)
    # Round to nearest 5
    return round(raw / 5) * 5


def main():
    from basecamp.management.commands.import_sydney_suburbs import SYDNEY_SUBURBS

    rows = []
    missing = []

    for name, data in sorted(SYDNEY_SUBURBS.items()):
        old = data['price']
        if name not in DISTANCES:
            missing.append(name)
            continue
        km = DISTANCES[name]
        new = new_price(km)
        diff = new - old
        rows.append((name, old, km, new, diff))

    # ── Summary counts ─────────────────────────────────────────────────
    up   = [r for r in rows if r[4] > 0]
    down = [r for r in rows if r[4] < 0]
    same = [r for r in rows if r[4] == 0]

    print(f"\nTotal suburbs: {len(rows)}  |  Up: {len(up)}  Down: {len(down)}  Same: {len(same)}")
    if missing:
        print(f"WARNING — no distance for: {', '.join(missing)}")

    # ── Full comparison table (only changed rows, sorted by diff desc) ─
    changed = [r for r in rows if r[4] != 0]
    changed.sort(key=lambda r: (-abs(r[4]), r[0]))

    print(f"\n{'Suburb':<28} {'Old':>5} {'km':>4} {'New':>5} {'Diff':>6}  Zone")
    print("-" * 72)
    for name, old, km, new, diff in changed:
        zone = SYDNEY_SUBURBS[name]['zone']
        sign = f"+{diff}" if diff > 0 else str(diff)
        print(f"{name:<28} ${old:>4}  {km:>3}  ${new:>4}  {sign:>5}   {zone}")

    print(f"\n── No change ({len(same)} suburbs) ───────────────────────────────────")
    for name, old, km, new, diff in sorted(same, key=lambda r: r[0]):
        print(f"  {name:<28} ${old}  ({km}km)")


if __name__ == '__main__':
    import sys, os
    sys.path.insert(0, os.path.dirname(__file__))
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'easygo.settings')
    import django
    django.setup()
    main()
