from decimal import Decimal

from django.core.management.base import BaseCommand
from django.utils.text import slugify

# ---------------------------------------------------------------------------
# Source data (previously hardcoded in area_full.py, area.py, suburb_utils.py)
# ---------------------------------------------------------------------------

SYDNEY_SUBURBS = {
    "Alexandria": {'price': 60, "zone": "eastern_suburbs"},
    "Allambie Heights": {'price': 90, "zone": "northern_beaches"},
    "Arndell Park": {'price': 120, "zone": "outer_west"},
    "Artarmon": {'price': 60, "zone": "north_shore"},
    "Ashfield": {'price': 60, "zone": "inner_west"},
    "Asquith": {'price': 60, "zone": "upper_north_shore"},
    "Auburn": {'price': 90, "zone": "west"},
    "Balgowlah": {'price': 80, "zone": "northern_beaches"},
    "Balgowlah Heights": {'price': 80, "zone": "northern_beaches"},
    "Balmain": {'price': 60, "zone": "inner_west"},
    "Banksmeadow": {'price': 80, "zone": "eastern_suburbs"},
    "Bankstown": {'price': 60, "zone": "west"},
    "Barangaroo": {'price': 60, "zone": "sydney_city"},
    "Bass Hill": {'price': 60, "zone": "west"},
    "Baulkham Hills": {'price': 100, "zone": "north_west"},
    "Beacon Hill": {'price': 100, "zone": "northern_beaches"},
    "Beaconsfield": {'price': 60, "zone": "eastern_suburbs"},
    "Beaumont Hills": {'price': 100, "zone": "north_west"},
    "Beauty Point": {'price': 90, "zone": "north_shore"},
    "Beecroft": {'price': 100, "zone": "upper_north_shore"},
    "Belfield": {'price': 60, "zone": "west"},
    "Bella Vista": {'price': 110, "zone": "north_west"},
    "Bellevue Hill": {'price': 60, "zone": "eastern_suburbs"},
    "Belmore": {'price': 60, "zone": "west"},
    "Belrose": {'price': 100, "zone": "northern_beaches"},
    "Berala": {'price': 80, "zone": "west"},
    "Berowra": {'price': 130, "zone": "upper_north_shore"},
    "Berowra Heights": {'price': 140, "zone": "upper_north_shore"},
    "Berowra Waters": {'price': 150, "zone": "upper_north_shore"},
    "Beverly Hills": {'price': 60, "zone": "west"},
    "Beverly Park": {'price': 60, "zone": "west"},
    "Bexley": {'price': 60, "zone": "west"},
    "Bexley North": {'price': 60, "zone": "west"},
    "Bidwill": {'price': 160, "zone": "outer_west"},
    "Birchgrove": {'price': 70, "zone": "inner_west"},
    "Birrong": {'price': 70, "zone": "west"},
    "Blackett": {'price': 140, "zone": "outer_west"},
    "Blacktown": {'price': 100, "zone": "outer_west"},
    "Bligh Park": {'price': 170, "zone": "outer_west"},
    "Bondi": {'price': 80, "zone": "eastern_suburbs"},
    "Bondi Beach": {'price': 80, "zone": "eastern_suburbs"},
    "Bondi Junction": {'price': 60, "zone": "eastern_suburbs"},
    "Botany": {'price': 70, "zone": "eastern_suburbs"},
    "Box Hill": {'price': 170, "zone": "outer_west"},
    "Breakfast Point": {'price': 80, "zone": "inner_west"},
    "Bronte": {'price': 60, "zone": "eastern_suburbs"},
    "Brooklyn": {'price': 160, "zone": "upper_north_shore"},
    "Brookvale": {'price': 100, "zone": "northern_beaches"},
    "Burwood": {'price': 60, "zone": "west"},
    "Cabarita": {'price': 70, "zone": "inner_west"},
    "Caddens": {'price': 170, "zone": "outer_west"},
    "Cambridge Gardens": {'price': 170, "zone": "outer_west"},
    "Cambridge Park": {'price': 170, "zone": "outer_west"},
    "Camellia": {'price': 80, "zone": "central_west"},
    "Cammeray": {'price': 70, "zone": "north_shore"},
    "Camperdown": {'price': 60, "zone": "inner_west"},
    "Canada Bay": {'price': 70, "zone": "inner_west"},
    "Carlingford": {'price': 90, "zone": "north_west"},
    "Castle Cove": {'price': 70, "zone": "north_shore"},
    "Castle Hill": {'price': 100, "zone": "north_west"},
    "Castlecrag": {'price': 70, "zone": "north_shore"},
    "Castlereagh": {'price': 150, "zone": "outer_west"},
    "Chatswood": {'price': 70, "zone": "north_shore"},
    "Chatswood West": {'price': 80, "zone": "north_shore"},
    "Cheltenham": {'price': 90, "zone": "north_west"},
    "Cherrybrook": {'price': 110, "zone": "north_west"},
    "Chester Hill": {'price': 80, "zone": "west"},
    "Chifley": {'price': 90, "zone": "eastern_suburbs"},
    "Chippendale": {'price': 50, "zone": "eastern_suburbs"},
    "Chiswick": {'price': 70, "zone": "inner_west"},
    "Chullora": {'price': 80, "zone": "west"},
    "Clovelly": {'price': 70, "zone": "eastern_suburbs"},
    "Clyde": {'price': 60, "zone": "central_west"},
    "Colebee": {'price': 130, "zone": "outer_west"},
    "Collaroy": {'price': 110, "zone": "northern_beaches"},
    "Collaroy Plateau": {'price': 110, "zone": "northern_beaches"},
    "Colyton": {'price': 140, "zone": "outer_west"},
    "Concord": {'price': 70, "zone": "inner_west"},
    "Concord West": {'price': 70, "zone": "inner_west"},
    "Condell Park": {'price': 70, "zone": "west"},
    "Constitution Hill": {'price': 80, "zone": "central_west"},
    "Coogee": {'price': 60, "zone": "eastern_suburbs"},
    "Cowan": {'price': 150, "zone": "upper_north_shore"},
    "Cranebrook": {'price': 180, "zone": "outer_west"},
    "Cremorne": {'price': 60, "zone": "north_shore"},
    "Cremorne Point": {'price': 70, "zone": "north_shore"},
    "Cromer": {'price': 100, "zone": "northern_beaches"},
    "Crows Nest": {'price': 60, "zone": "north_shore"},
    "Curl Curl": {'price': 100, "zone": "northern_beaches"},
    "Darling Point": {'price': 50, "zone": "sydney_city"},
    "Darlinghurst": {'price': 50, "zone": "sydney_city"},
    "Davidson": {'price': 100, "zone": "northern_beaches"},
    "Dean Park": {'price': 120, "zone": "outer_west"},
    "Dee Why": {'price': 80, "zone": "northern_beaches"},
    "Denistone": {'price': 70, "zone": "north_west"},
    "Denistone East": {'price': 80, "zone": "north_west"},
    "Dharruk": {'price': 120, "zone": "outer_west"},
    "Doonside": {'price': 110, "zone": "outer_west"},
    "Double Bay": {'price': 60, "zone": "eastern_suburbs"},
    "Drummoyne": {'price': 60, "zone": "inner_west"},
    "Dulwich Hill": {'price': 60, "zone": "inner_west"},
    "Dundas": {'price': 70, "zone": "central_west"},
    "Dundas Valley": {'price': 80, "zone": "central_west"},
    "Dural": {'price': 100, "zone": "north_west"},
    "East Killara": {'price': 80, "zone": "north_shore"},
    "East Lindfield": {'price': 70, "zone": "north_shore"},
    "East Ryde": {'price': 70, "zone": "north_west"},
    "Eastern Creek": {'price': 130, "zone": "outer_west"},
    "Eastgardens": {'price': 70, "zone": "eastern_suburbs"},
    "Eastlakes": {'price': 60, "zone": "eastern_suburbs"},
    "Eastwood": {'price': 80, "zone": "north_west"},
    "Edgecliff": {'price': 60, "zone": "eastern_suburbs"},
    "Elanora Heights": {'price': 100, "zone": "northern_beaches"},
    "Emerton": {'price': 150, "zone": "outer_west"},
    "Emu Plains": {'price': 190, "zone": "outer_west"},
    "Enfield": {'price': 50, "zone": "west"},
    "Enmore": {'price': 50, "zone": "inner_west"},
    "Epping": {'price': 80, "zone": "north_west"},
    "Ermington": {'price': 80, "zone": "central_west"},
    "Eveleigh": {'price': 50, "zone": "eastern_suburbs"},
    "Fairlight": {'price': 70, "zone": "northern_beaches"},
    "Five Dock": {'price': 60, "zone": "inner_west"},
    "Forest Lodge": {'price': 60, "zone": "inner_west"},
    "Forestville": {'price': 80, "zone": "northern_beaches"},
    "Frenchs Forest": {'price': 90, "zone": "northern_beaches"},
    "Freshwater": {'price': 100, "zone": "northern_beaches"},
    "Galston": {'price': 130, "zone": "north_west"},
    "Georges Hall": {'price': 60, "zone": "west"},
    "Girraween": {'price': 90, "zone": "central_west"},
    "Gladesville": {'price': 60, "zone": "north_west"},
    "Glebe": {'price': 60, "zone": "sydney_city"},
    "Glendenning": {'price': 110, "zone": "outer_west"},
    "Glenhaven": {'price': 110, "zone": "north_west"},
    "Glenmore Park": {'price': 190, "zone": "outer_west"},
    "Glenorie": {'price': 140, "zone": "outer_west"},
    "Glenwood": {'price': 120, "zone": "north_west"},
    "Gordon": {'price': 80, "zone": "north_shore"},
    "Granville": {'price': 80, "zone": "central_west"},
    "Greenacre": {'price': 60, "zone": "west"},
    "Greenwich": {'price': 60, "zone": "north_shore"},
    "Greystanes": {'price': 90, "zone": "central_west"},
    "Guildford": {'price': 80, "zone": "west"},
    "Guildford West": {'price': 80, "zone": "west"},
    "Haberfield": {'price': 60, "zone": "inner_west"},
    "Harris Park": {'price': 80, "zone": "central_west"},
    "Hassall Grove": {'price': 130, "zone": "outer_west"},
    "Haymarket": {'price': 60, "zone": "sydney_city"},
    "Hebersham": {'price': 110, "zone": "outer_west"},
    "Henley": {'price': 60, "zone": "north_west"},
    "Hillsdale": {'price': 70, "zone": "eastern_suburbs"},
    "Homebush": {'price': 60, "zone": "west"},
    "Homebush West": {'price': 60, "zone": "west"},
    "Hornsby": {'price': 100, "zone": "upper_north_shore"},
    "Hornsby Heights": {'price': 110, "zone": "upper_north_shore"},
    "Hotels In City": {'price': 60, "zone": "sydney_city"},
    "Huntingwood": {'price': 120, "zone": "outer_west"},
    "Huntleys Cove": {'price': 60, "zone": "north_west"},
    "Huntleys Point": {'price': 60, "zone": "north_west"},
    "Hurstville": {'price': 50, "zone": "west"},
    "Ingleside": {'price': 140, "zone": "northern_beaches"},
    "Jamisontown": {'price': 190, "zone": "outer_west"},
    "Jordan Springs": {'price': 180, "zone": "outer_west"},
    "Kellyville": {'price': 110, "zone": "north_west"},
    "Kellyville Ridge": {'price': 120, "zone": "north_west"},
    "Kensington": {'price': 70, "zone": "eastern_suburbs"},
    "Kenthurst": {'price': 140, "zone": "north_west"},
    "Killara": {'price': 80, "zone": "north_shore"},
    "Killarney Heights": {'price': 80, "zone": "northern_beaches"},
    "Kings Langley": {'price': 110, "zone": "north_west"},
    "Kings Park": {'price': 120, "zone": "north_west"},
    "Kingsford": {'price': 70, "zone": "eastern_suburbs"},
    "Kingswood": {'price': 170, "zone": "outer_west"},
    "Kirribilli": {'price': 60, "zone": "north_shore"},
    "Kurraba Point": {'price': 70, "zone": "north_shore"},
    "La Perouse": {'price': 100, "zone": "eastern_suburbs"},
    "Lakemba": {'price': 60, "zone": "west"},
    "Lalor Park": {'price': 120, "zone": "north_west"},
    "Lane Cove": {'price': 70, "zone": "north_shore"},
    "Lane Cove North": {'price': 70, "zone": "north_shore"},
    "Lane Cove West": {'price': 70, "zone": "north_shore"},
    "Lansdowne": {'price': 80, "zone": "west"},
    "Lavender Bay": {'price': 70, "zone": "north_shore"},
    "Leichhardt": {'price': 60, "zone": "inner_west"},
    "Lethbridge Park": {'price': 100, "zone": "outer_west"},
    "Liberty Grove": {'price': 60, "zone": "inner_west"},
    "Lidcombe": {'price': 60, "zone": "west"},
    "Lilyfield": {'price': 50, "zone": "inner_west"},
    "Lindfield": {'price': 70, "zone": "north_shore"},
    "Linley Point": {'price': 60, "zone": "north_shore"},
    "Little Bay": {'price': 100, "zone": "eastern_suburbs"},
    "Londonderry": {'price': 180, "zone": "outer_west"},
    "Longueville": {'price': 80, "zone": "north_shore"},
    "Macquarie Park": {'price': 80, "zone": "north_west"},
    "Malabar": {'price': 90, "zone": "eastern_suburbs"},
    "Manly": {'price': 90, "zone": "northern_beaches"},
    "Manly Vale": {'price': 90, "zone": "northern_beaches"},
    "Marayong": {'price': 140, "zone": "outer_west"},
    "Maroubra": {'price': 80, "zone": "eastern_suburbs"},
    "Maroubra Junction": {'price': 80, "zone": "eastern_suburbs"},
    "Marrickville": {'price': 60, "zone": "inner_west"},
    "Marsden Park": {'price': 160, "zone": "outer_west"},
    "Marsfield": {'price': 80, "zone": "north_west"},
    "Mascot": {'price': 70, "zone": "eastern_suburbs"},
    "Matraville": {'price': 90, "zone": "eastern_suburbs"},
    "McGraths Hill": {'price': 160, "zone": "outer_west"},
    "McMahons Point": {'price': 70, "zone": "north_shore"},
    "Meadowbank": {'price': 80, "zone": "north_west"},
    "Melrose Park": {'price': 80, "zone": "north_west"},
    "Merrylands": {'price': 100, "zone": "central_west"},
    "Merrylands West": {'price': 100, "zone": "central_west"},
    "Middle Cove": {'price': 70, "zone": "north_shore"},
    "Millers Point": {'price': 70, "zone": "sydney_city"},
    "Milperra": {'price': 60, "zone": "west"},
    "Milsons Point": {'price': 70, "zone": "sydney_city"},
    "Minchinbury": {'price': 160, "zone": "outer_west"},
    "Mona Vale": {'price': 130, "zone": "northern_beaches"},
    "Mortdale": {'price': 80, "zone": "west"},
    "Mosman": {'price': 80, "zone": "north_shore"},
    "Mount Colah": {'price': 120, "zone": "upper_north_shore"},
    "Mount Kuring-gai": {'price': 120, "zone": "upper_north_shore"},
    "Mt Druitt": {'price': 150, "zone": "outer_west"},
    "Mulgrave": {'price': 160, "zone": "outer_west"},
    "Naremburn": {'price': 70, "zone": "north_shore"},
    "Narrabeen": {'price': 120, "zone": "northern_beaches"},
    "Narraweena": {'price': 110, "zone": "northern_beaches"},
    "Neutral Bay": {'price': 70, "zone": "north_shore"},
    "Newington": {'price': 80, "zone": "central_west"},
    "Newtown": {'price': 60, "zone": "inner_west"},
    "Normanhurst": {'price': 100, "zone": "upper_north_shore"},
    "North Balgowlah": {'price': 90, "zone": "northern_beaches"},
    "North Bondi": {'price': 70, "zone": "eastern_suburbs"},
    "North Curl Curl": {'price': 110, "zone": "northern_beaches"},
    "North Epping": {'price': 90, "zone": "north_west"},
    "North Kellyville": {'price': 130, "zone": "north_west"},
    "North Manly": {'price': 90, "zone": "northern_beaches"},
    "North Parramatta": {'price': 90, "zone": "central_west"},
    "North Richmond": {'price': 190, "zone": "outer_west"},
    "North Ryde": {'price': 80, "zone": "north_west"},
    "North Strathfield": {'price': 70, "zone": "west"},
    "North Sydney": {'price': 70, "zone": "north_shore"},
    "North Turramurra": {'price': 100, "zone": "north_shore"},
    "North Wahroonga": {'price': 110, "zone": "upper_north_shore"},
    "North Willoughby": {'price': 70, "zone": "north_shore"},
    "Northbridge": {'price': 70, "zone": "north_shore"},
    "Northmead": {'price': 100, "zone": "central_west"},
    "Northwood": {'price': 70, "zone": "north_shore"},
    "Oakhurst": {'price': 150, "zone": "outer_west"},
    "Oakville": {'price': 170, "zone": "outer_west"},
    "Oatlands": {'price': 90, "zone": "central_west"},
    "Old Guildford": {'price': 80, "zone": "west"},
    "Old Toongabbie": {'price': 100, "zone": "central_west"},
    "Olympic Park": {'price': 70, "zone": "central_west"},
    "Orchard Hills": {'price': 150, "zone": "outer_west"},
    "Oxley Park": {'price': 150, "zone": "outer_west"},
    "Paddington": {'price': 70, "zone": "sydney_city"},
    "Padstow": {'price': 70, "zone": "west"},
    "Pagewood": {'price': 70, "zone": "eastern_suburbs"},
    "Panania": {'price': 80, "zone": "west"},
    "Parklea": {'price': 110, "zone": "north_west"},
    "Parramatta": {'price': 90, "zone": "central_west"},
    "Peakhurst": {'price': 70, "zone": "west"},
    "Pemulwuy": {'price': 100, "zone": "central_west"},
    "Pendle Hill": {'price': 100, "zone": "central_west"},
    "Pennant Hills": {'price': 100, "zone": "upper_north_shore"},
    "Penrith": {'price': 190, "zone": "outer_west"},
    "Penshurst": {'price': 70, "zone": "west"},
    "Petersham": {'price': 60, "zone": "inner_west"},
    "Pitt Town": {'price': 200, "zone": "outer_west"},
    "Plumpton": {'price': 150, "zone": "outer_west"},
    "Point Piper": {'price': 70, "zone": "eastern_suburbs"},
    "Potts Hill": {'price': 70, "zone": "west"},
    "Potts Point": {'price': 70, "zone": "sydney_city"},
    "Prospect": {'price': 100, "zone": "outer_west"},
    "Punchbowl": {'price': 70, "zone": "west"},
    "Putney": {'price': 80, "zone": "north_west"},
    "Pymble": {'price': 90, "zone": "north_shore"},
    "Pyrmont": {'price': 60, "zone": "sydney_city"},
    "Quakers Hill": {'price': 140, "zone": "outer_west"},
    "Queens Park": {'price': 60, "zone": "eastern_suburbs"},
    "Randwick": {'price': 60, "zone": "eastern_suburbs"},
    "Randwick North": {'price': 60, "zone": "eastern_suburbs"},
    "Randwick West": {'price': 60, "zone": "eastern_suburbs"},
    "Redfern": {'price': 50, "zone": "eastern_suburbs"},
    "Regents Park": {'price': 80, "zone": "west"},
    "Revesby": {'price': 70, "zone": "west"},
    "Rhodes": {'price': 70, "zone": "inner_west"},
    "Richmond": {'price': 180, "zone": "outer_west"},
    "Riverstone": {'price': 150, "zone": "outer_west"},
    "Riverview": {'price': 70, "zone": "north_shore"},
    "Riverwood": {'price': 80, "zone": "west"},
    "Ropes Crossing": {'price': 160, "zone": "outer_west"},
    "Rose Bay": {'price': 70, "zone": "eastern_suburbs"},
    "Rosebery": {'price': 60, "zone": "eastern_suburbs"},
    "Rosehill": {'price': 80, "zone": "central_west"},
    "Roselands": {'price': 60, "zone": "west"},
    "Roseville": {'price': 80, "zone": "north_shore"},
    "Roseville Chase": {'price': 80, "zone": "north_shore"},
    "Rouse Hill": {'price': 150, "zone": "north_west"},
    "Rozelle": {'price': 60, "zone": "inner_west"},
    "Russell Lea": {'price': 70, "zone": "inner_west"},
    "Rydalmere": {'price': 90, "zone": "central_west"},
    "Ryde": {'price': 80, "zone": "north_west"},
    "Schofields": {'price': 150, "zone": "outer_west"},
    "Seaforth": {'price': 90, "zone": "northern_beaches"},
    "Sefton": {'price': 80, "zone": "west"},
    "Seven Hills": {'price': 100, "zone": "north_west"},
    "Shalvey": {'price': 150, "zone": "outer_west"},
    "Silverwater": {'price': 70, "zone": "central_west"},
    "South Coogee": {'price': 70, "zone": "eastern_suburbs"},
    "South Penrith": {'price': 190, "zone": "outer_west"},
    "South Turramurra": {'price': 100, "zone": "north_shore"},
    "South Wentworthville": {'price': 100, "zone": "central_west"},
    "South Windsor": {'price': 240, "zone": "outer_west"},
    "St Clair": {'price': 130, "zone": "outer_west"},
    "St Ives": {'price': 90, "zone": "north_shore"},
    "St Ives Chase": {'price': 100, "zone": "north_shore"},
    "St Leonards": {'price': 60, "zone": "north_shore"},
    "St Marys": {'price': 150, "zone": "outer_west"},
    "St Marys North": {'price': 160, "zone": "outer_west"},
    "Stanhope Gardens": {'price': 130, "zone": "north_west"},
    "Stanmore": {'price': 60, "zone": "inner_west"},
    "Strathfield": {'price': 70, "zone": "west"},
    "Summer Hill": {'price': 60, "zone": "inner_west"},
    "Surry Hills": {'price': 60, "zone": "sydney_city"},
    "Sydney CBD": {'price': 60, "zone": "sydney_city"},
    "Sydney City": {'price': 60, "zone": "sydney_city"},
    "Tamarama": {'price': 70, "zone": "eastern_suburbs"},
    "Telopea": {'price': 90, "zone": "central_west"},
    "Tennyson Point": {'price': 80, "zone": "north_west"},
    "Terrey Hills": {'price': 110, "zone": "northern_beaches"},
    "The Ponds": {'price': 140, "zone": "north_west"},
    "The Rocks": {'price': 60, "zone": "sydney_city"},
    "Thornleigh": {'price': 100, "zone": "upper_north_shore"},
    "Toongabbie": {'price': 100, "zone": "central_west"},
    "Tregear": {'price': 130, "zone": "outer_west"},
    "Turramurra": {'price': 100, "zone": "north_shore"},
    "Ultimo": {'price': 60, "zone": "sydney_city"},
    "Vaucluse": {'price': 80, "zone": "eastern_suburbs"},
    "Villawood": {'price': 80, "zone": "west"},
    "Vineyard": {'price': 160, "zone": "outer_west"},
    "Wahroonga": {'price': 100, "zone": "upper_north_shore"},
    "Waitara": {'price': 100, "zone": "upper_north_shore"},
    "Wareemba": {'price': 70, "zone": "inner_west"},
    "Warrawee": {'price': 100, "zone": "upper_north_shore"},
    "Warriewood": {'price': 120, "zone": "northern_beaches"},
    "Waterloo": {'price': 60, "zone": "eastern_suburbs"},
    "Watsons Bay": {'price': 80, "zone": "eastern_suburbs"},
    "Waverley": {'price': 70, "zone": "eastern_suburbs"},
    "Waverton": {'price': 70, "zone": "north_shore"},
    "Wentworthville": {'price': 90, "zone": "central_west"},
    "Werrington": {'price': 160, "zone": "outer_west"},
    "Werrington County": {'price': 160, "zone": "outer_west"},
    "West Pennant Hills": {'price': 100, "zone": "upper_north_shore"},
    "West Pymble": {'price': 90, "zone": "north_shore"},
    "West Ryde": {'price': 80, "zone": "north_west"},
    "Westleigh": {'price': 100, "zone": "north_west"},
    "Westmead": {'price': 90, "zone": "central_west"},
    "Whalan": {'price': 160, "zone": "outer_west"},
    "Wheeler Heights": {'price': 100, "zone": "northern_beaches"},
    "Wiley Park": {'price': 60, "zone": "west"},
    "Willmot": {'price': 190, "zone": "outer_west"},
    "Willoughby": {'price': 70, "zone": "north_shore"},
    "Willoughby East": {'price': 70, "zone": "north_shore"},
    "Windsor": {'price': 180, "zone": "outer_west"},
    "Winston Hills": {'price': 100, "zone": "north_west"},
    "Wollstonecraft": {'price': 70, "zone": "north_shore"},
    "Woollahra": {'price': 60, "zone": "eastern_suburbs"},
    "Woolloomooloo": {'price': 60, "zone": "sydney_city"},
    "Yagoona": {'price': 90, "zone": "west"},
    "Zetland": {'price': 60, "zone": "eastern_suburbs"},
    # In booking dropdown (area_home.py) but missing from area_full.py
    "Rooty Hill": {'price': 120, "zone": "outer_west"},
}

# Suburbs pinned to the top of the booking dropdown (sort_order determines sequence)
PINNED = {
    "Hotels In City": 0,
    "Sydney Int'l Airport": 1,
    "Sydney Domestic Airport": 2,
    "WhiteBay cruise terminal": 3,
    "Overseas cruise terminal": 4,
}

# Airports/terminals not in area_full.py — booking-only, no pillar page needed
EXTRA_PINNED = [
    {"name": "Sydney Int'l Airport",      "price": 0, "zone": "sydney_city"},
    {"name": "Sydney Domestic Airport",   "price": 0, "zone": "sydney_city"},
    {"name": "WhiteBay cruise terminal",  "price": 0, "zone": "sydney_city"},
    {"name": "Overseas cruise terminal",  "price": 0, "zone": "sydney_city"},
]

class Command(BaseCommand):
    help = 'Import Sydney suburbs into RegionSuburb. Idempotent — safe to re-run.'

    def handle(self, *args, **options):
        from regions.models import Region, RegionSuburb

        sydney, created = Region.objects.get_or_create(
            slug='sydney',
            defaults={
                'name': 'Sydney',
                'airport_code': 'SYD',
                'state_code': 'NSW',
                'timezone': 'Australia/Sydney',
                'phone': '0412 534 237',
                'phone_display': '0412 534 237',
                'is_active': True,
            },
        )
        if created:
            self.stdout.write(self.style.SUCCESS('Created Sydney region'))

        created_count = 0
        updated_count = 0

        # --- Main suburb data ---
        for name, data in SYDNEY_SUBURBS.items():
            slug = slugify(name)
            price = Decimal(str(data['price']))
            zone = data['zone']

            obj, was_created = RegionSuburb.objects.update_or_create(
                region=sydney,
                slug=slug,
                defaults={
                    'name': name,
                    'price': price,
                    'zone': zone,
                    'is_active': True,
                    'is_pinned': name in PINNED,
                    'sort_order': PINNED.get(name, 0),
                    'meta_title': f"{name} Airport Shuttle | EasyGo Sydney",
                    'meta_description': (
                        f"Private airport shuttle from {name} to Sydney Airport (SYD). "
                        f"Fixed price from ${int(price)} per vehicle. "
                        "Door-to-door service. Book online."
                    ),
                },
            )
            if was_created:
                created_count += 1
            else:
                updated_count += 1

        # --- Extra pinned items (airports/terminals not in SYDNEY_SUBURBS) ---
        for item in EXTRA_PINNED:
            name = item['name']
            slug = slugify(name)

            obj, was_created = RegionSuburb.objects.update_or_create(
                region=sydney,
                slug=slug,
                defaults={
                    'name': name,
                    'price': Decimal('0'),
                    'zone': item['zone'],
                    'is_active': True,
                    'is_pinned': True,
                    'sort_order': PINNED[name],
                    'meta_title': f"{name} | EasyGo Sydney",
                    'meta_description': '',
                },
            )
            if was_created:
                created_count += 1
            else:
                updated_count += 1

        # Remove legacy "Sydney City Hotels" entry if present
        deleted, _ = RegionSuburb.objects.filter(
            region=sydney, slug='sydney-city-hotels',
        ).delete()
        if deleted:
            self.stdout.write(f'Removed legacy entry: Sydney City Hotels')

        self.stdout.write(self.style.SUCCESS(
            f'Done. Created: {created_count}, Updated: {updated_count}'
        ))
