# Generated by Django 5.2.15 on 2026-07-24 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0056_rename_sms_reminder_inquiry_no_email_reminder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(verbose_name='서비스 날짜')),
                ('self_serviced', models.BooleanField(default=False, verbose_name='자가정비')),
                ('vendor', models.CharField(blank=True, max_length=100, verbose_name='업체명')),
                ('odometer_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='당시 주행거리(km)')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='총 비용')),
                ('receipt_photo', models.ImageField(blank=True, null=True, upload_to='fleet/receipts/%Y/%m/', verbose_name='영수증 사진')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
            ],
            options={
                'verbose_name': 'Service Visit',
                'verbose_name_plural': 'Service Visits',
                'ordering': ['-service_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('engine_oil', '엔진오일'), ('oil_filter', '엔진오일필터'), ('air_filter', '에어필터'), ('tyre', '타이어'), ('brake_pad', '브레이크패드'), ('transmission_oil', '트랜스미션오일'), ('other', '기타')], max_length=20, verbose_name='항목')),
                ('product_name', models.CharField(blank=True, max_length=100, verbose_name='제품명')),
                ('part_number', models.CharField(blank=True, max_length=100, verbose_name='제품번호')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='비용')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fleet.servicevisit', verbose_name='방문')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_model', models.CharField(max_length=100, verbose_name='차종류')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='차번호')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='등록일')),
                ('rego_expiry_date', models.DateField(blank=True, null=True, verbose_name='Rego 만료일')),
                ('inspection_date', models.DateField(blank=True, null=True, verbose_name='Inspection 만료일')),
                ('green_slip_provider', models.CharField(blank=True, max_length=100, verbose_name='Green slip 업체')),
                ('green_slip_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Green slip 비용')),
                ('green_slip_expiry_date', models.DateField(blank=True, null=True, verbose_name='Green slip 만료일')),
                ('odometer_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='현재 주행거리(km)')),
                ('is_active', models.BooleanField(default=True, verbose_name='운행중')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='blog.driver', verbose_name='담당 기사')),
            ],
            options={
                'ordering': ['plate_number'],
            },
        ),
        migrations.AddField(
            model_name='servicevisit',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_visits', to='fleet.vehicle', verbose_name='차량'),
        ),
    ]
