# Generated by Django 5.2.15 on 2026-07-24 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0058_backfill_phonemapping_post'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Part number'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='service_type',
            field=models.CharField(choices=[('engine_oil', 'Engine oil'), ('oil_filter', 'Oil filter'), ('air_filter', 'Air filter'), ('tyre', 'Tyre'), ('brake_pad', 'Brake pad'), ('transmission_oil', 'Transmission oil'), ('other', 'Other')], max_length=20, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fleet.servicevisit', verbose_name='Visit'),
        ),
        migrations.AlterField(
            model_name='servicevisit',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='servicevisit',
            name='odometer_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Odometer at service (km)'),
        ),
        migrations.AlterField(
            model_name='servicevisit',
            name='receipt_photo',
            field=models.ImageField(blank=True, null=True, upload_to='fleet/receipts/%Y/%m/', verbose_name='Receipt photo'),
        ),
        migrations.AlterField(
            model_name='servicevisit',
            name='self_serviced',
            field=models.BooleanField(default=False, verbose_name='Self serviced'),
        ),
        migrations.AlterField(
            model_name='servicevisit',
            name='service_date',
            field=models.DateField(verbose_name='Service date'),
        ),
        migrations.AlterField(
            model_name='servicevisit',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total cost'),
        ),
        migrations.AlterField(
            model_name='servicevisit',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_visits', to='fleet.vehicle', verbose_name='Vehicle'),
        ),
        migrations.AlterField(
            model_name='servicevisit',
            name='vendor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Vendor'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='blog.driver', verbose_name='Assigned driver'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='green_slip_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Green slip cost'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='green_slip_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Green slip expiry date'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='green_slip_provider',
            field=models.CharField(blank=True, max_length=100, verbose_name='Green slip provider'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Inspection expiry date'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make_model',
            field=models.CharField(max_length=100, verbose_name='Make / Model'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='odometer_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Current odometer (km)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Plate number'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Registration date'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='rego_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Rego expiry date'),
        ),
    ]
