# Generated by Django 5.2.4 on 2025-11-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('Long', 'Long'), ('Short', 'Short')], max_length=10)),
                ('buy_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('sell_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('quantity', models.IntegerField()),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('net_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
