# Generated by Django 5.2.12 on 2026-03-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_paypalpayment_is_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='booker_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='booker_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='booker_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='booker_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
