# Generated by Django 5.2.12 on 2026-03-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_inquiry_booker_email_inquiry_booker_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='paid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='paid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
