# Generated by Django 5.2.4 on 2026-03-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_inquiry_paid_alter_post_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='fuel_surcharge',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='fuel_surcharge',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
