# Generated by Django 5.2.4 on 2026-04-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_inquiry_fuel_surcharge_post_fuel_surcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='google_calendar_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='driver_calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
