# Generated by Django 5.2.4 on 2026-04-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_driver_google_calendar_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='customer_proxy_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='proxy_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='proxy_session_sid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='customer_proxy_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='proxy_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='proxy_session_sid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
