# Generated by Django 5.2.13 on 2026-04-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_add_proxy_session_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_number', models.CharField(db_index=True, max_length=20)),
                ('to_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='customer_proxy_number',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='proxy_number',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='proxy_session_sid',
        ),
        migrations.RemoveField(
            model_name='post',
            name='customer_proxy_number',
        ),
        migrations.RemoveField(
            model_name='post',
            name='proxy_number',
        ),
        migrations.RemoveField(
            model_name='post',
            name='proxy_session_sid',
        ),
    ]
