# Generated by Django 5.2.13 on 2026-04-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_bird_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='use_proxy',
            field=models.BooleanField(default=False),
        ),
    ]
