# Generated by Django 5.2.13 on 2026-04-22 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_add_user_to_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.driver'),
        ),
        migrations.AlterField(
            model_name='post',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.driver'),
        ),
        migrations.AddField(
            model_name='driver',
            name='virtual_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.virtualnumber'),
        ),
    ]
