# Generated by Django 5.2.13 on 2026-04-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_virtualnumber_alter_inquiry_driver_alter_post_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
