# Generated by Django 5.2.13 on 2026-04-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_driver_must_change_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='XrpPayment',
        ),
        migrations.AddField(
            model_name='phonemapping',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='phonemapping',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phonemapping',
            name='pickup_time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
