# Generated by Django 5.2.13 on 2026-04-24 03:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_driversettlement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driversettlement',
            name='settled_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
