# Generated by Django 5.2.13 on 2026-04-29 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_inquiry_region_post_region'),
        ('regions', '0011_seed_melbourne_airport_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regions.region'),
        ),
    ]
