# Generated by Django 5.2.13 on 2026-05-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_inquiry_extra_stop_inquiry_special_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='extra_stop_addresses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
