# Generated by Django 5.2.13 on 2026-05-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_inquiry_extra_stop_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='extra_stop_addresses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
