# Generated by Django 5.2.13 on 2026-05-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_post_extra_stop_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='extra_stop',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='special_items',
            field=models.JSONField(blank=True, default=dict, help_text='Keys: baby, booster, pram, ski, ski_oversize, snowboard, snowboard_oversize, surfboard, surfboard_oversize, bike, bike_oversize, golf, golf_oversize, boxes, boxes_oversize'),
        ),
    ]
