# Generated by Django 5.2.13 on 2026-05-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_inquiry_same_extra_stop_post_same_extra_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='special_items',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='post',
            name='special_items',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
