# Generated by Django 5.2.13 on 2026-05-20 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_inquiry_special_items_alter_post_special_items'),
        ('regions', '0043_populate_all_suburb_distance_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='terminal_pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='regions.terminalpickuppoint'),
        ),
    ]
