# Generated by Django 5.2.13 on 2026-05-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_post_terminal_pickup_point'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='fuel_surcharge',
            new_name='surcharge',
        ),
        migrations.AddField(
            model_name='driver',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
