# Generated by Django 5.2.13 on 2026-06-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_driversettlement_new_fields_driversettlementitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='abn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
