# Generated by Django 5.2.15 on 2026-06-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_rename_meeting_point_to_customer_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='gst_registered',
            field=models.BooleanField(default=False),
        ),
    ]
