# Generated by Django 5.2.15 on 2026-06-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_driver_gst_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='driver_collected_cash',
            field=models.BooleanField(blank=True, default=False, help_text='타 드라이버가 손님에게 직접 현금 수령 (회사 매출 아님, GST 제외)'),
        ),
    ]
