# Generated by Django 5.2.15 on 2026-06-21 09:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_post_driver_collected_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='회사 커미션 %. 예: 10.00 = 10%', max_digits=4),
        ),
    ]
