# Generated by Django 5.2.15 on 2026-06-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_driver_payid_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='payment_match_digits',
            field=models.CharField(blank=True, help_text='PayID 번호 또는 계좌번호 끝자리 등 송금 식별 숫자. 비워두면 숫자 매칭 안 함.', max_length=30, null=True),
        ),
    ]
