# Generated by Django 5.2.15 on 2026-07-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_alter_driver_payment_match_digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deposit_amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='디파짓 인보이스로 청구한 금액. 결제가 이 금액 이상 들어오면 전액에 못 미쳐도 미납 안내 메일을 보내지 않음.', max_digits=10, null=True),
        ),
    ]
