# Generated by Django 5.2.15 on 2026-07-05 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_post_deposit_amount_due'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='2026-07', max_length=20)),
                ('item_status_confirmed', models.BooleanField(default=False)),
                ('item_liability_confirmed', models.BooleanField(default=False)),
                ('item_rcti_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('gst_registered_snapshot', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='blog.driver')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('driver', 'version')},
            },
        ),
    ]
