# Generated by Django 5.2.15 on 2026-07-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_driveragreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='commission_amount_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='이 부킹 한정 커미션 고정 금액($). 입력하면 commission_rate(%) 대신 이 금액을 사용.', max_digits=10, null=True),
        ),
    ]
