# Generated by Django 5.2.15 on 2026-07-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_post_commission_amount_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='driver_price',
            field=models.CharField(blank=True, help_text='드라이버 대시보드 표시 및 커미션/정산 계산에 쓰이는 금액. 비어있으면 저장 시 price 값으로 자동 채워짐. 손님 결제(price/paid)와는 별개.', max_length=100, null=True),
        ),
    ]
