# Generated by Django 5.2.15 on 2026-07-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_backfill_driver_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='agreement_token',
            field=models.CharField(blank=True, editable=False, help_text='로그인 없이 subcontractor agreement 페이지를 열 수 있는 토큰. 자동 생성됨.', max_length=64, null=True, unique=True),
        ),
    ]
