# Generated by Django 5.2.15 on 2026-07-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_backfill_driver_agreement_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_company',
            field=models.BooleanField(default=False, help_text='이 레코드가 개인 드라이버가 아니라 드라이버를 공급하는 협력업체(법인)인 경우 체크. Agreement 페이지 문구가 회사용으로 바뀌고, 확인은 그 회사 담당자 이름/직책으로 기록됨.'),
        ),
        migrations.AddField(
            model_name='driveragreement',
            name='signed_by_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driveragreement',
            name='signed_by_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
