# Generated by Django 5.2.15 on 2026-07-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_driver_is_company_driveragreement_signed_by_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='booker_contact',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='booker_contact',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
