# Generated by Django 5.2.15 on 2026-07-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_inquiry_booker_contact_post_booker_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='final_warning_at',
            field=models.DateTimeField(blank=True, help_text='48h 무응답 최종 경고 메일 발송 시각. 24h 유예 후 자동 취소 판단에 사용.', null=True),
        ),
    ]
