# Generated by Django 5.2.15 on 2026-07-14 07:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_post_final_warning_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='commission_amount_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Flat commission amount ($) for this booking only. If set, used instead of commission_rate(%).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Commission % applied to this booking. Automatically set to the default when a driver is assigned.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='post',
            name='deposit_amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount invoiced as a deposit. If payment received reaches this amount, the unpaid-balance reminder email is not sent even if it falls short of the full price.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='driver_collected_cash',
            field=models.BooleanField(blank=True, default=False, help_text='Another driver collected cash directly from the customer (not company revenue, excluded from GST)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='driver_price',
            field=models.CharField(blank=True, help_text='Amount used for driver dashboard display and commission/settlement calculations. If empty, automatically filled with the price value on save. Separate from customer payment (price/paid).', max_length=100, null=True),
        ),
    ]
