# Generated by Django 5.2.15 on 2026-07-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0048_alter_post_commission_amount_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_payment_notified_at',
            field=models.DateTimeField(blank=True, help_text='잔액 부족(short payment) 안내 메일 발송 시각. final_notice 중복 발송 방지에 사용.', null=True),
        ),
    ]
