# Generated by Django 5.2.15 on 2026-07-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_post_short_payment_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualnumber',
            name='sms_channel_id',
            field=models.CharField(blank=True, help_text='Bird sms-messagebird channel id. Run sync_bird_channels to fill.', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='virtualnumber',
            name='voice_channel_id',
            field=models.CharField(blank=True, help_text='Bird voice-messagebird channel id. Run sync_bird_channels to fill.', max_length=64, null=True, unique=True),
        ),
    ]
