# Generated by Django 5.2.15 on 2026-07-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0050_virtualnumber_sms_channel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='no_payment_notice_sent_at',
            field=models.DateTimeField(blank=True, help_text='결제 미완료 1차 안내(Payment notice) 발송 시각. no_payment_yet 중복 발송 방지에 사용.', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='no_payment_urgent_sent_at',
            field=models.DateTimeField(blank=True, help_text='결제 미완료 최종 안내(Urgent notice for payment) 발송 시각. no_payment_yet 중복 발송 방지에 사용.', null=True),
        ),
    ]
