# Generated by Django 5.2.15 on 2026-07-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0051_post_no_payment_notice_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='discrepancy_final_sent_at',
            field=models.DateTimeField(blank=True, help_text='부분결제 최종 경고(취소/환불불가 안내) 메일 발송 시각(픽업 1일 전). no_payment_yet 중복 발송 방지에 사용.', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='discrepancy_notice_sent_at',
            field=models.DateTimeField(blank=True, help_text='부분결제(디파짓 아닌 진짜 차액) 안내 메일 발송 시각(픽업 2일 전). no_payment_yet 중복 발송 방지에 사용.', null=True),
        ),
    ]
