# Generated by Django 5.2.15 on 2026-07-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0053_post_pickup_date_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='no_review',
            field=models.BooleanField(blank=True, default=False, help_text='체크하면 픽업 5일 후 리뷰 요청(Review-EasyGo) 리마인더 메일을 보내지 않음.'),
        ),
    ]
