# Generated by Django 5.2.15 on 2026-07-18 20:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0054_post_no_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='driver_refund_deduction',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Portion of the customer refund the driver bears ($). Deducted from the driver settlement/payout and the driver dashboard. e.g. a $100 refund where the driver bears 50% -> enter 50 here (and 100 in refund).', max_digits=10),
        ),
        migrations.AddField(
            model_name='post',
            name='refund',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text="Total amount refunded to the customer for this booking ($). Automatically netted off company sales/GST (1A). Separate from the driver's share of the refund (driver_refund_deduction).", max_digits=10),
        ),
    ]
