# Generated by Django 5.2.15 on 2026-07-18 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0055_post_driver_refund_deduction_post_refund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='sms_reminder',
            new_name='no_email_reminder',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='sms_reminder',
            new_name='no_email_reminder',
        ),
    ]
