# Generated by Django 5.2.15 on 2026-07-24 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0056_rename_sms_reminder_inquiry_no_email_reminder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemapping',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_mappings', to='blog.post'),
        ),
    ]
