# Generated by Django 5.2.15 on 2026-07-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0058_backfill_phonemapping_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='extra_stop_area',
            field=models.CharField(blank=True, help_text='Suburb/area only (no street) — shown to the driver in place of the full extra-stop address before the 24h-before-pickup window opens. Admin-entered, separate from extra_stop_addresses since those are free text and cannot be safely reduced to a suburb automatically.', max_length=100, null=True),
        ),
    ]
