# Generated by Django 5.2.15 on 2026-07-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0059_post_extra_stop_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='final_notice_sent_at',
            field=models.DateTimeField(blank=True, help_text='완전 미결제 건 Final notice(자동취소 예고) 메일 발송 시각. dep 픽업 48h 전 / arr 72h 전 1회 발송, 중복 발송 방지에 사용.', null=True),
        ),
    ]
