# Generated by Django 5.2.15 on 2026-07-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0060_post_final_notice_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='final_warning_at',
            field=models.DateTimeField(blank=True, help_text='사다리 창(픽업 21일) 밖 먼 미래 미결제 건의 "예약 pending 상태" 조기 안내(send_final_warning) 발송 시각. 중복 발송 방지에 사용. (픽업 임박 독촉/취소는 no_payment_yet + auto_cancel_pending 담당)', null=True),
        ),
    ]
