# Generated by Django 5.2.15 on 2026-07-29 08:50

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0061_alter_post_final_warning_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='application_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='bank_bsb',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_class',
            field=models.CharField(blank=True, choices=[('C', 'Car (C)'), ('LR', 'Light Rigid (LR)'), ('MR', 'Medium Rigid (MR)'), ('HR', 'Heavy Rigid (HR)'), ('HC', 'Heavy Combination (HC)'), ('MC', 'Multi Combination (MC)'), ('OTHER', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_scan',
            field=models.FileField(blank=True, help_text='드라이버 라이센스 스캔/사진. 오피스 관리자만 열람 가능 (private storage).', null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location='/home/sungk/github/easygo/private_media/driver_docs'), upload_to='driver_licenses/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AddField(
            model_name='driver',
            name='payid_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank', 'Bank Transfer'), ('payid', 'PayID')], max_length=10, null=True),
        ),
    ]
