# Generated by Django 5.2.15 on 2026-07-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0063_alter_driver_license_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deposit_balance_final_sent_at',
            field=models.DateTimeField(blank=True, help_text='디파짓 충족 건의 잔액 안내 2차(최종) 메일 발송 시각(픽업 7일 전). 디파짓 건은 자동취소 대상이 아니므로 취소 예고가 아니라 마지막 안내다.', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='deposit_balance_notice_sent_at',
            field=models.DateTimeField(blank=True, help_text='디파짓 충족 건의 잔액 안내 1차 메일 발송 시각(픽업 14일 전). no_payment_yet 중복 발송 방지에 사용.', null=True),
        ),
    ]
