# Generated by Django 5.2.15 on 2026-07-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0066_alter_driver_license_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='has_vehicle_insurance',
            field=models.BooleanField(default=False, help_text='차량 보험(대인/대물 등) 가입 여부. 지원서에서 본인이 체크한 값이며 증빙 서류 확인은 별도로 해야 함.'),
        ),
    ]
