# Generated by Django 5.2.15 on 2026-07-31 01:10

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0067_driver_has_vehicle_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_scan',
            field=models.FileField(blank=True, help_text='드라이버 라이센스 스캔/사진. 오피스 관리자만 열람 가능 (private storage).', null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location='/home/sungk/github/easygo/private_media/driver_docs'), upload_to='driver_licenses/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
    ]
