# Generated by Django 5.2.15 on 2026-08-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0070_alter_driver_license_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sms_final_sent_at',
            field=models.DateTimeField(blank=True, help_text='마지막 SMS 에스컬레이션(final_notice, 픽업 당일~내일) 발송 시각. 미결제·부분결제 두 경로가 공유하는 중복 발송 방지 필드.', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sms_notice_sent_at',
            field=models.DateTimeField(blank=True, help_text='미결제 건 SMS 독촉(send_sms, 픽업 3일 이내) 발송 시각. 중복 발송 방지에 사용. 예전엔 reminder=True 로 중복을 막았지만, reminder 는 "고객이 답장함"·"결제됨" 의미로도 쓰여서 SMS 발송이 다른 독촉을 잘라먹었다.', null=True),
        ),
    ]
