# Generated by Django 5.2.15 on 2026-08-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0071_post_sms_final_sent_at_post_sms_notice_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='arrival_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='공항 도착 건의 당일 리마인더(arrival_reminder, 도착 예정시각 1시간 전) 발송 시각. 크론이 10분마다 돌기 때문에 중복 발송 방지에 필수. 도착 건은 이 메일이 아침 Reminder-Today를 대체한다.', null=True),
        ),
    ]
