# Generated by Django 5.2.15 on 2026-08-02 02:11

import blog.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0072_post_arrival_reminder_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_scan',
            field=models.FileField(blank=True, help_text='드라이버 라이센스 스캔/사진. 오피스 관리자만 열람 가능 (private storage).', null=True, storage=blog.storage.private_driver_docs_storage, upload_to='driver_licenses/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
    ]
