# Generated by Django 5.2.17 on 2026-08-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0073_license_scan_storage_callable'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveragreement',
            name='item_tax_invoice_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
