# Generated by Django 5.2.17 on 2026-08-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0074_driveragreement_item_tax_invoice_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_car',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
