# Generated by Django 5.2.17 on 2026-08-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0075_driver_car_max_length_40'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='candidate_drivers',
            field=models.ManyToManyField(blank=True, related_name='candidate_posts', to='blog.driver'),
        ),
    ]
