# Generated by Django 5.2.17 on 2026-08-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0076_post_candidate_drivers'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='settle_daily',
            field=models.BooleanField(default=True, help_text='일이 끝나면 그날 바로 정산받는 드라이버. 매일 밤 크론(create_daily_settlements)이 당일 트립을 정산 처리한다. 주/월 단위로 모아서 정산하는 드라이버는 체크를 풀 것 — 체크된 채로 두면 실제로 지급하지도 않은 정산서가 매일 생겨 드라이버 대시보드에 "받을 돈 0"으로 보인다.'),
        ),
    ]
