# Generated by Django 5.2.17 on 2026-08-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0077_driver_settle_daily'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalpayment',
            name='case_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='PayPal dispute/claim case id (PP-R-...), when the IPN is a case notification.', max_length=64),
        ),
        migrations.AddField(
            model_name='paypalpayment',
            name='case_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='paypalpayment',
            name='parent_txn_id',
            field=models.CharField(blank=True, default='', help_text='Original transaction a refund/reversal relates to.', max_length=100),
        ),
        migrations.AddField(
            model_name='paypalpayment',
            name='payment_status',
            field=models.CharField(blank=True, default='', help_text='IPN payment_status: Completed / Refunded / Reversed / Canceled_Reversal … Blank on rows created before 2026-08.', max_length=30),
        ),
        migrations.AddField(
            model_name='paypalpayment',
            name='raw',
            field=models.JSONField(blank=True, help_text='Full verified IPN payload as received.', null=True),
        ),
        migrations.AddField(
            model_name='paypalpayment',
            name='reason_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='paypalpayment',
            name='txn_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='paypal_dispute_case_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='값이 있으면 이 예약의 결제금이 PayPal 분쟁(dispute/chargeback)으로 보류·차감된 상태다. 환불(refund)과 달리 아직 확정된 게 아니므로 refund 필드는 건드리지 않는다. 분쟁이 취소되거나 판매자 승소로 끝나면(Canceled_Reversal) 자동으로 비워진다.', max_length=64),
        ),
        migrations.AddField(
            model_name='post',
            name='paypal_dispute_opened_at',
            field=models.DateTimeField(blank=True, help_text='PayPal 분쟁 알림(IPN)을 받은 시각. 페이팔 응답 기한 관리를 위해 기록한다.', null=True),
        ),
    ]
