# Generated by Django 5.2.17 on 2026-09-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0078_paypalpayment_case_id_paypalpayment_case_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('keyword', models.CharField(max_length=200)),
                ('page', models.CharField(max_length=50)),
                ('landed', models.CharField(max_length=100)),
                ('landed_note', models.CharField(blank=True, max_length=300)),
                ('liked', models.TextField(blank=True)),
                ('improve', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
