# Generated by Django 5.2.17 on 2026-09-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0079_searchsurveyresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchsurveyresponse',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, help_text='달러 정액 할인'),
        ),
        migrations.AddField(
            model_name='searchsurveyresponse',
            name='discount_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='searchsurveyresponse',
            name='discount_emailed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchsurveyresponse',
            name='discount_expires',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchsurveyresponse',
            name='discount_redeemed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchsurveyresponse',
            name='discount_redeemed_note',
            field=models.CharField(blank=True, help_text='어느 예약에 썼는지 메모', max_length=200),
        ),
    ]
