# Generated by Django 5.2.17 on 2026-09-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0081_delete_searchsurveyresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveragreement',
            name='item_luggage_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
