# Generated by Django 5.2.17 on 2026-09-17 03:44

from django.db import migrations, models


def switch_on_don(apps, schema_editor):
    # 기존 드라이버는 건드리지 않는다(기본값 False). Don 만 7/1 이후 트립부터 공제.
    Driver = apps.get_model('blog', 'Driver')
    Driver.objects.filter(driver_name__iexact='don').update(non_gst_deduction=True)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0082_driveragreement_item_luggage_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='non_gst_deduction',
            field=models.BooleanField(default=False, help_text='GST 미등록 드라이버에게서 driver_price 의 10%를 빼고 지급 (2026-07-01 이후 픽업분). GST 등록 드라이버는 체크와 상관없이 공제 안 함. 자동으로 켜지지 않음 — ABN 확인 후 수동으로 체크.'),
        ),
        migrations.RunPython(switch_on_don, migrations.RunPython.noop),
    ]
