# Generated by Django 5.2.17 on 2026-09-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0083_driver_non_gst_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bulk_invoice',
            field=models.BooleanField(blank=True, default=False, help_text='체크하면 여러 부킹을 한 장의 인보이스(날짜 범위 멀티 인보이스)로 청구하는 건으로 보고 부킹별 결제 독촉 메일·SMS·자동취소에서 모두 제외한다. 날짜 범위로 멀티 인보이스를 보내면 포함된 부킹에 자동으로 체크된다.'),
        ),
    ]
