# Generated by Django 5.2.17 on 2026-09-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0085_driver_license_scan_heic'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='always_show_address',
            field=models.BooleanField(default=False, help_text='체크하면 배정된 트립의 풀주소를 전날까지 기다리지 않고 대시보드에 바로 보여준다. 고객 전화번호/프록시 번호는 여전히 전날부터만 열림.'),
        ),
    ]
