# Generated by Django 5.2.17 on 2026-09-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0086_driver_always_show_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='direct_contact',
            field=models.BooleanField(default=False, help_text='체크하면 이 드라이버는 Bird 프록시를 쓰지 않는다 — 외국번호 손님처럼 대시보드에 손님 실제 번호가, 손님 리마인더 이메일에 드라이버 실제 번호가 나간다. 트립의 use_proxy 는 그대로 켜 둘 것(끄면 대시보드에서 사라짐).'),
        ),
    ]
