# Generated by Django 5.2.17 on 2026-10-01 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0088_fully_booked_date'),
        ('regions', '0050_backfill_terminal_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullybookeddate',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Blank = all regions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fully_booked_dates', to='regions.region'),
        ),
        migrations.AlterField(
            model_name='fullybookeddate',
            name='date',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='fullybookeddate',
            constraint=models.UniqueConstraint(fields=('region', 'date'), name='fullybooked_region_date_uniq'),
        ),
        migrations.AddConstraint(
            model_name='fullybookeddate',
            constraint=models.UniqueConstraint(condition=models.Q(('region__isnull', True)), fields=('date',), name='fullybooked_all_regions_date_uniq'),
        ),
    ]
