# Generated by Django 5.2.13 on 2026-04-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0005_seed_melbourne_suburbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='arrival_guide',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='region',
            name='meeting_point',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='region',
            name='terminal_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
