# Generated by Django 5.2.13 on 2026-04-26 22:51

from django.db import migrations

TERMINAL_INFO = [
    {
        "name": "T1 – International",
        "description": (
            "Arrivals at Level 2 (Ground Level). After clearing customs, "
            "exit through the sliding doors into the Arrivals Hall. "
            "Your EasyGo driver will be waiting with a name board near the exit."
        ),
        "icon": "✈️",
    },
    {
        "name": "T2 – Qantas Domestic",
        "description": (
            "Collect your baggage and exit through the main Arrivals door. "
            "Your driver meets you on the kerbside directly outside baggage claim."
        ),
        "icon": "🛬",
    },
    {
        "name": "T3 – Virgin / Rex Domestic",
        "description": (
            "Connected to T2 via a short walkway. Exit at Ground Level. "
            "Your driver meets you at the main kerbside exit."
        ),
        "icon": "🛬",
    },
    {
        "name": "T4 – Budget Airlines (Jetstar & others)",
        "description": (
            "Separate terminal on Departure Drive. After collecting baggage, "
            "exit through the main doors. Driver meets you on the pick-up kerbside."
        ),
        "icon": "🛫",
    },
]

MEETING_POINT = (
    "Your EasyGo driver will be waiting in the Arrivals Hall holding a name board "
    "with your name. After clearing customs and collecting your baggage, look for your "
    "driver near the exit. If you cannot locate your driver, please call or text the "
    "number on your booking confirmation and we will assist you immediately."
)

ARRIVAL_GUIDE = (
    "1. Land at Melbourne Airport (MEL) and follow signs to Arrivals.\n"
    "2. Proceed to Baggage Claim and collect all your luggage.\n"
    "3. Clear Australian Border Force (customs & biosecurity).\n"
    "4. Exit through the sliding doors into the Arrivals Hall.\n"
    "5. Look for your EasyGo driver holding a name board with your name.\n"
    "6. If you cannot find your driver, call or text the number on your confirmation.\n"
    "7. Your driver will escort you to the vehicle and assist with luggage.\n"
    "8. Sit back and enjoy your door-to-door transfer to your destination."
)


def seed_melbourne(apps, schema_editor):
    Region = apps.get_model('regions', 'Region')
    Region.objects.filter(slug='melbourne').update(
        terminal_info=TERMINAL_INFO,
        meeting_point=MEETING_POINT,
        arrival_guide=ARRIVAL_GUIDE,
    )


def reverse_seed(apps, schema_editor):
    Region = apps.get_model('regions', 'Region')
    Region.objects.filter(slug='melbourne').update(
        terminal_info=None,
        meeting_point='',
        arrival_guide='',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0006_add_guides_and_terminals'),
    ]

    operations = [
        migrations.RunPython(seed_melbourne, reverse_seed),
    ]
