# Generated by Django 5.2.13 on 2026-04-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0008_region_add_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionsuburb',
            name='featured_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='regionsuburb',
            name='featured_extra',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='regionsuburb',
            name='featured_image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='regionsuburb',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regionsuburb',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regionsuburb',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
