# Generated by Django 5.2.13 on 2026-04-27 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0009_regionsuburb_sydney_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionsuburb',
            name='featured_description',
        ),
        migrations.RemoveField(
            model_name='regionsuburb',
            name='featured_extra',
        ),
        migrations.RemoveField(
            model_name='regionsuburb',
            name='featured_image_url',
        ),
        migrations.RemoveField(
            model_name='regionsuburb',
            name='is_featured',
        ),
    ]
