# Generated by Django 5.2.13 on 2026-04-30 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0016_region_primary_airport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regionsuburb',
            options={'ordering': ['featured_order', 'name']},
        ),
        migrations.AddField(
            model_name='regionsuburb',
            name='featured_order',
            field=models.PositiveSmallIntegerField(default=999),
        ),
        migrations.AddField(
            model_name='regionsuburb',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
