# Generated by Django 5.2.4 on 2026-05-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0019_region_is_coming_soon'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='service_areas',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
