# Generated by Django 5.2.4 on 2026-05-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0020_add_service_areas_to_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='hero_image',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
