# Generated by Django 5.2.13 on 2026-05-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0021_add_hero_image_to_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionsuburb',
            name='carousel_image',
            field=models.CharField(blank=True, help_text='Carousel card image URL, e.g. /static/regions/photos/chatswood.webp', max_length=255),
        ),
    ]
