# Generated by Django 5.2.14 on 2026-05-12 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0022_regionsuburb_carousel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='pickup_instruction',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='TerminalMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='regions.terminal')),
            ],
            options={
                'ordering': ['terminal', 'title'],
            },
        ),
    ]
