# Generated by Django 5.2.14 on 2026-05-12 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0023_add_pickup_points'),
        ('regions', '0023_terminal_pickup_instruction_terminalmap'),
    ]

    operations = [
    ]
