# Generated by Django 5.2.13 on 2026-05-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0023_add_pickup_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickuppointmap',
            options={'ordering': ['pickup_point', 'type', 'title']},
        ),
        migrations.AddField(
            model_name='pickuppointmap',
            name='type',
            field=models.CharField(choices=[('location', 'Location Map'), ('walking', 'Walking Route'), ('google', 'Google Map'), ('pdf', 'PDF Guide'), ('image', 'Image Map')], default='location', max_length=20),
        ),
    ]
