# Generated by Django 5.2.14 on 2026-05-12 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0024_alter_pickuppointmap_options_pickuppointmap_type'),
        ('regions', '0024_merge_20260512_1347'),
    ]

    operations = [
    ]
