# Generated by Django 5.2.13 on 2026-05-12 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0024_alter_pickuppointmap_options_pickuppointmap_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CruiseTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cruise_terminals', to='regions.region')),
            ],
        ),
    ]
