# Generated by Django 5.2.4 on 2026-05-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0025_cruiseterminal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terminal',
            options={'ordering': ['airport__code', 'sort_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='terminalpickuppoint',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='terminal',
            name='icon',
            field=models.CharField(blank=True, default='✈️', help_text='Emoji shown on the tab button', max_length=10),
        ),
        migrations.AddField(
            model_name='terminal',
            name='note',
            field=models.TextField(blank=True, help_text="Shown as a tip inside the terminal panel (e.g. 'On landing simply turn on your mobile phone')"),
        ),
        migrations.AddField(
            model_name='terminal',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='terminalpickuppoint',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
