# Generated by Django 5.2.14 on 2026-05-12 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0025_merge_20260512_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminal',
            name='pickup_instruction',
        ),
        migrations.DeleteModel(
            name='TerminalMap',
        ),
    ]
