# Generated by Django 5.2.14 on 2026-05-12 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0025_cruiseterminal'),
        ('regions', '0026_remove_terminal_pickup_instruction_and_more'),
    ]

    operations = [
    ]
