# Generated by Django 5.2.14 on 2026-05-14 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0026_terminal_icon_note_sort_order'),
        ('regions', '0027_merge_20260512_1555'),
    ]

    operations = [
    ]
