# Generated by Django 5.2.14 on 2026-05-14 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0027_backfill_carousel_image_paths'),
        ('regions', '0028_merge_20260514_1411'),
    ]

    operations = [
    ]
