# Generated by Django 5.2.14 on 2026-05-14 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0029_merge_20260515_0845'),
        ('regions', '0030_seed_region_carousel_suburbs'),
    ]

    operations = [
    ]
