# Generated by Django 5.2.13 on 2026-05-15 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0031_merge_20260515_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('fee', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('capacity_pax', models.PositiveSmallIntegerField()),
                ('price_multiplier', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['capacity_pax'],
            },
        ),
        migrations.AddField(
            model_name='regionsuburb',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Drive distance from airport in km (used for distance-based pricing)', max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_km', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('extra_bag_fee', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('oversize_fee', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('second_stop_fee', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('pax_surcharge_mid_fee', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('pax_surcharge_large_fee', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('peak_windows', models.JSONField(default=list, help_text='List of time windows with surcharges. Example: [{"type":"peak","start":6,"end":9,"surcharge_rate":0.20}]')),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rule', to='regions.region')),
            ],
            options={
                'verbose_name': 'Pricing Rule',
            },
        ),
    ]
