# Generated by Django 5.2.13 on 2026-05-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0032_specialitemtype_vehicletype_regionsuburb_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrule',
            name='special_item_fee',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='special_item_oversize_fee',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
    ]
