# Generated by Django 5.2.13 on 2026-05-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0034_backfill_suburb_distances_and_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
