# Generated by Django 5.2.14 on 2026-05-18 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0035_backfill_sydney_distances_and_prices'),
        ('regions', '0035_requestlog_add_email'),
    ]

    operations = [
    ]
