# Generated by Django 5.2.4 on 2026-05-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0036_merge_20260519_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionsuburb',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='WGS84 latitude of the suburb/terminal centroid', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='regionsuburb',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='WGS84 longitude of the suburb/terminal centroid', max_digits=9, null=True),
        ),
    ]
