# Generated by Django 5.2.14 on 2026-05-19 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0036_merge_20260519_1454'),
        ('regions', '0037_regionsuburb_add_lat_lng'),
    ]

    operations = [
    ]
