# Generated by Django 5.2.14 on 2026-05-19 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0038_merge_20260519_1456'),
        ('regions', '0038_round_suburb_prices_to_nearest_5'),
    ]

    operations = [
    ]
