# Generated by Django 5.2.13 on 2026-05-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0040_merge_20260519'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruiseterminal',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base price = distance_km × $3', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='cruiseterminal',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Distance from terminal to airport (km)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='cruiseterminal',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cruiseterminal',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True),
        ),
    ]
