from decouple import config


EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT')
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_BACKEND = config('EMAIL_BACKEND')

GMAIL_SERVICE_ACCOUNT_FILE = config('GMAIL_SERVICE_ACCOUNT_FILE')
CALENDAR_SERVICE_ACCOUNT_FILE = config('CALENDAR_SERVICE_ACCOUNT_FILE')

RECIPIENT_EMAIL = config('RECIPIENT_EMAIL')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')
