# Generated by Django 5.2.4 on 2026-03-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('seo_content', models.TextField(help_text='Django 블로그용 SEO 롱폼 글')),
                ('social_content', models.TextField(help_text='Facebook/Instagram용 짧은 글')),
                ('gmb_content', models.TextField(help_text='Google Business용 짧은 글')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_posts/')),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('blog_status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('facebook_status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('instagram_status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('gmb_status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
