# Generated by Django 5.2.17 on 2026-08-05 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting_agent', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
