# Generated by Django 5.2.15 on 2026-06-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DividendRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declared_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('franking_credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('retained', 'Retained'), ('paid', 'Paid')], default='retained', max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('employee_name', models.CharField(default='Sung Kam', max_length=120)),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paygw_withheld', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('super_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Payroll entries',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('direction', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('brand', models.CharField(choices=[('shuttle', 'Shuttle'), ('coaches', 'Coaches')], default='shuttle', max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_code', models.CharField(choices=[('gst', 'GST'), ('gst_free', 'GST Free'), ('no_gst', 'No GST')], default='no_gst', max_length=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.CharField(max_length=50)),
                ('source', models.CharField(choices=[('paypal', 'PayPal'), ('bank', 'Bank'), ('cash', 'Cash'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('counterparty', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'brand', 'direction'], name='accounting__date_b0e811_idx')],
            },
        ),
    ]
