# Generated by Django 5.2.15 on 2026-06-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe'), ('bank', 'Bank'), ('cash', 'Cash'), ('manual', 'Manual')], default='manual', max_length=10),
        ),
    ]
