# Generated by Django 5.2.15 on 2026-06-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_transaction_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='gst_auto_estimated',
            field=models.BooleanField(default=False, help_text='True if gst_code/gst_amount were auto-guessed on import and still need human review before BAS.'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='import_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 fingerprint of the source bank row (dedup key). Empty for manually-entered transactions.', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('import_hash__gt', '')), fields=('import_hash',), name='uniq_bank_import_hash'),
        ),
    ]
