# Generated by Django 5.2.15 on 2026-06-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_transaction_gst_auto_estimated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='excluded',
            field=models.BooleanField(db_index=True, default=False, help_text='Permanently excluded from BAS/P&L — e.g. a driver payout already recorded via DriverSettlement (avoids double count).'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='needs_review',
            field=models.BooleanField(db_index=True, default=False, help_text='Held for human triage (e.g. a large bank withdrawal). Excluded from BAS 1B and P&L totals until approved.'),
        ),
    ]
