# Generated by Django 5.2.15 on 2026-07-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_directorloan'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_tax_deductible',
            field=models.BooleanField(db_index=True, default=True, help_text='False for expenses that are imported for record-keeping but must not be claimed as a business expense — e.g. fines/infringements (non_deductible_fine). Excluded from P&L expense totals and BAS 1B regardless of gst_code.'),
        ),
    ]
