# Generated by Django 5.2.17 on 2026-08-11 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_transaction_is_tax_deductible'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorloan',
            name='source_transaction',
            field=models.OneToOneField(blank=True, help_text='Set when this entry was derived from a personal expense paid off the company account; empty for hand-entered loan movements. Doubles as the idempotency key — the OneToOne guarantees at most one loan entry per transaction, so a re-import or a repeated admin action can never double-count the balance.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='director_loan_entry', to='accounting.transaction'),
        ),
    ]
