# Generated by Django 5.2.17 on 2026-08-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_directorloan_source_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentFeeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('direction', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('brand', models.CharField(choices=[('shuttle', 'Shuttle'), ('coaches', 'Coaches')], default='shuttle', max_length=10)),
                ('source', models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe')], max_length=10)),
                ('description', models.CharField(db_index=True, max_length=255)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_code', models.CharField(choices=[('gst', 'GST'), ('gst_free', 'GST Free'), ('no_gst', 'No GST')], default='no_gst', max_length=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('counterparty', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'date'], name='accounting__source_ffdc4d_idx')],
            },
        ),
    ]
